import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

const RESOLVED=new Set(['completed','retired','abandoned','not_played']);
const LOCK_MS=90*1000;
const CORRECTION_MS=90*1000;
function clean(v:any,max=240){return String(v??'').trim().slice(0,max);}
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('');}
function int0(v:any){const n=Number(v);return Number.isInteger(n)&&n>=0?n:null;}
function lockActive(m:any){return !!(m?.scoring_lock_owner&&m?.scoring_lock_expires_at&&Date.parse(m.scoring_lock_expires_at)>Date.now());}
function correctionOpen(m:any,owner:string){return RESOLVED.has(m?.status)&&String(m?.scorer_correction_owner_client_id||'')===owner&&!!m?.completed_at&&Date.now()-Date.parse(m.completed_at)<=CORRECTION_MS;}
function validScore(body:any,session:any){const a=int0(body.teamAScore),b=int0(body.teamBScore);if(a==null||b==null)return {error:'Scores must be non-negative whole numbers.'};if(a>99||b>99)return {error:'KOTC scores cannot exceed 99.'};if(session.scoring_mode==='timed'){if(a===b){if(!['A','B'].includes(body.servingSideAtHorn))return {error:'A tied timed match requires the serving side at the horn.'};return {a,b,winner:body.servingSideAtHorn,method:'timed_serving_tiebreak'};}return {a,b,winner:a>b?'A':'B',method:'normal'};}if(a===b)return {error:'First-to scoring requires a winner.'};const target=Number(session.score_target||11),cap=Number(session.score_cap||0),winner=Math.max(a,b),loser=Math.min(a,b);if(winner<target)return {error:`Winner must reach at least ${target}.`};if(cap>0&&winner>cap)return {error:`Score cannot exceed cap of ${cap}.`};if(session.win_by_two&&winner-loser<2&&!(cap>0&&winner===cap))return {error:'Winner must lead by 2 unless the score cap is reached.'};if(!session.win_by_two&&winner>target&&!(cap>0&&winner===cap))return {error:`Match should finish when a team reaches ${target}.`};return {a,b,winner:a>b?'A':'B',method:'normal'};}
async function resolve(base44:any,shareToken:string,deviceToken:string){const share=(await base44.asServiceRole.entities.KotcSessionShare.filter({token:shareToken,status:'active'}))?.[0];if(!share)throw new Error('Player Link is invalid or revoked.');if(String(share.scoring_access||'read_only')!=='verified_players')throw new Error('Player scoring is not enabled for this KOTC.');const session=(await base44.asServiceRole.entities.KotcSession.filter({id:share.session_id}))?.[0];if(!session)throw new Error('KOTC session not found.');const hash=await sha256(deviceToken);const access=(await base44.asServiceRole.entities.KotcPlayerDeviceAccess.filter({session_id:session.id,share_id:share.id,device_token_hash:hash,status:'approved'}))?.[0];if(!access||access.expires_at&&Date.parse(access.expires_at)<Date.now())throw new Error('Verify your player identity before entering a score.');const participant=(await base44.asServiceRole.entities.KotcSessionParticipant.filter({id:access.participant_id,session_id:session.id}))?.[0];if(!participant)throw new Error('Verified player is no longer in this session.');return{share,session,access,participant};}
async function ownMatch(base44:any,session:any,participant:any){if(!session.current_round_id)return null;const matches=await base44.asServiceRole.entities.KotcMatch.filter({session_id:session.id,round_id:session.current_round_id},'ladder_court_rank',30);return (matches||[]).find((m:any)=>[...(m.team_a_participant_ids||[]),...(m.team_b_participant_ids||[])].map(String).includes(String(participant.id)))||null;}

Deno.serve(async req=>{try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const shareToken=clean(body.shareToken||body.token,180),deviceToken=clean(body.deviceToken,180),action=clean(body.action||'state',40);if(!shareToken||!deviceToken)return Response.json({error:'Player verification required.'},{status:401});const {session,access,participant}=await resolve(base44,shareToken,deviceToken);const owner=`player:${access.id}`;const match=await ownMatch(base44,session,participant);
 if(action==='state'){if(!match)return Response.json({success:true,verified:true,participant:{id:participant.id,display_name:participant.display_name},match:null,bench:true});return Response.json({success:true,verified:true,participant:{id:participant.id,display_name:participant.display_name},match:{id:match.id,court:Number(match.ladder_court_rank),round_number:Number(match.round_number),status:match.status,revision:Number(match.revision||0),team_a_participant_ids:match.team_a_participant_ids||[],team_b_participant_ids:match.team_b_participant_ids||[],team_a_score:match.team_a_score,team_b_score:match.team_b_score,winner_side:match.winner_side,serving_side_at_horn:match.serving_side_at_horn,locked_by_me:lockActive(match)&&String(match.scoring_lock_owner)===owner,locked_by_other:lockActive(match)&&String(match.scoring_lock_owner)!==owner,can_correct:correctionOpen(match,owner)},bench:false});}
 if(!match)return Response.json({error:'You are on the bench this round; there is no court score for you to enter.'},{status:409});if(session.status!=='in_progress')return Response.json({error:'Player scoring is only available while the KOTC is live.'},{status:409});
 if(action==='claim'){
   if(RESOLVED.has(match.status)&&!correctionOpen(match,owner))return Response.json({error:'This court result is already saved. Ask the host if it needs changing.',read_only:true},{status:423});
   if(lockActive(match)&&String(match.scoring_lock_owner)!==owner)return Response.json({error:`Court ${match.ladder_court_rank} is being scored on another device.`,locked:true},{status:423});
   const now=new Date().toISOString(),expires=new Date(Date.now()+LOCK_MS).toISOString();await base44.asServiceRole.entities.KotcMatch.update(match.id,{scoring_lock_owner:owner,scoring_lock_acquired_at:match.scoring_lock_acquired_at||now,scoring_lock_expires_at:expires});return Response.json({success:true,claimed:true,expires_at:expires});
 }
 if(action==='release'){if(String(match.scoring_lock_owner||'')===owner)await base44.asServiceRole.entities.KotcMatch.update(match.id,{scoring_lock_owner:null,scoring_lock_acquired_at:null,scoring_lock_expires_at:null});return Response.json({success:true,released:true});}
 if(action==='save'||action==='correct'){
   if(!lockActive(match)||String(match.scoring_lock_owner)!==owner)return Response.json({error:'This court is not locked to your device. Tap Enter Score again.'},{status:423});const correcting=action==='correct';if(correcting&&!correctionOpen(match,owner))return Response.json({error:'The player correction window has closed. Ask the host to correct the result.'},{status:423});if(!correcting&&RESOLVED.has(match.status))return Response.json({error:'This court result is already saved.'},{status:409});if(Number(body.expectedRevision)!==Number(match.revision||0))return Response.json({error:'This score changed since you opened it. Refresh and check the saved result.',conflict:true},{status:409});const result:any=validScore(body,session);if(result.error)return Response.json({error:result.error},{status:400});const now=new Date().toISOString();const update:any={team_a_score:result.a,team_b_score:result.b,winner_side:result.winner,result_method:result.method,serving_side_at_horn:result.method==='timed_serving_tiebreak'?body.servingSideAtHorn:undefined,status:'completed',completed_at:match.completed_at||now,revision:Number(match.revision||0)+1,command_id:`player-${access.id}-${Date.now()}`,scoring_lock_owner:null,scoring_lock_acquired_at:null,scoring_lock_expires_at:null,scorer_correction_owner_client_id:owner};if(correcting)Object.assign(update,{correction_count:Number(match.correction_count||0)+1,last_corrected_at:now,last_corrected_by_user_id:owner,last_correction_reason:'Verified player corrected saved KOTC score'});const saved=await base44.asServiceRole.entities.KotcMatch.update(match.id,update);return Response.json({success:true,corrected:correcting,match:saved,message:correcting?'Updated score saved':'Score saved'});
 }
 return Response.json({error:'Unknown player scoring action.'},{status:400});
}catch(error){console.error('kotcPlayerScore',error);return Response.json({error:(error as any)?.message||'Unable to load or save this KOTC score.'},{status:500});}});
