import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('');}
function nowIso(){return new Date().toISOString();}
function validAccess(a:any,tenantId:string,sessionId:string){if(!a||a.status!=='active'||String(a.tenant_id)!==String(tenantId)||String(a.session_id)!==String(sessionId)||a.role!=='session_host')return false;const now=Date.now();if(a.starts_at&&Date.parse(a.starts_at)>now)return false;if(a.ends_at&&Date.parse(a.ends_at)<now)return false;return true;}
function standings(matches:any[],participants:any[]){const s:any=Object.fromEntries((participants||[]).map(p=>[p.id,{id:p.id,player_id:p.player_id,name:p.display_name,wins:0,losses:0,points_for:0,points_against:0,rounds_played:0,court1_rounds:0}]));for(const m of (matches||[]).filter(x=>x.status==='completed')){const a=m.team_a_participant_ids||[],b=m.team_b_participant_ids||[];for(const id of [...a,...b])if(s[id]){s[id].rounds_played++;if(Number(m.ladder_court_rank)===1)s[id].court1_rounds++;}for(const id of a)if(s[id]){s[id].points_for+=Number(m.team_a_score||0);s[id].points_against+=Number(m.team_b_score||0);m.winner_side==='A'?s[id].wins++:s[id].losses++;}for(const id of b)if(s[id]){s[id].points_for+=Number(m.team_b_score||0);s[id].points_against+=Number(m.team_a_score||0);m.winner_side==='B'?s[id].wins++:s[id].losses++;}}return Object.values(s).sort((x:any,y:any)=>y.wins-x.wins||((y.points_for-y.points_against)-(x.points_for-x.points_against))||y.court1_rounds-x.court1_rounds||x.name.localeCompare(y.name)).map((x:any,i)=>({...x,rank:i+1,differential:x.points_for-x.points_against}));}

Deno.serve(async req=>{try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const action=String(body.action||'');
 if(action==='public_state'){
  const shareToken=String(body.token||'');if(!shareToken)return Response.json({error:'Token required'},{status:400});
  const shares=await base44.asServiceRole.entities.KotcSessionShare.filter({token:shareToken,status:'active'});const share=shares?.[0];if(!share)return Response.json({error:'Results link is invalid or revoked.'},{status:404});if(share.expires_at&&Date.parse(share.expires_at)<Date.now())return Response.json({error:'Results link has expired.'},{status:410});
  const sessions=await base44.asServiceRole.entities.KotcSession.filter({id:share.session_id});const session=sessions?.[0];if(!session)return Response.json({error:'Session not found.'},{status:404});
  const [participants,matches,rounds]=await Promise.all([base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id}),base44.asServiceRole.entities.KotcMatch.filter({session_id:session.id}),base44.asServiceRole.entities.KotcRound.filter({session_id:session.id})]);
  const playerIds=[...new Set((participants||[]).map(p=>p.player_id).filter(Boolean))];const aggregates=playerIds.length?await base44.asServiceRole.entities.KotcPlayerAggregate.filter({player_id:{$in:playerIds}}):[];const aggregateByPlayer=Object.fromEntries((aggregates||[]).map(a=>[a.player_id,a]));
  const names=Object.fromEntries((participants||[]).map(p=>[p.id,p.display_name]));
  const publicMatches=(matches||[]).filter(m=>m.status==='completed').sort((a,b)=>Number(a.round_number)-Number(b.round_number)||Number(a.ladder_court_rank)-Number(b.ladder_court_rank)).map(m=>({round_number:m.round_number,court:m.ladder_court_rank,team_a:(m.team_a_participant_ids||[]).map(id=>names[id]||'Player'),team_b:(m.team_b_participant_ids||[]).map(id=>names[id]||'Player'),team_a_score:m.team_a_score,team_b_score:m.team_b_score,winner_side:m.winner_side,result_method:m.result_method}));
  try{await base44.asServiceRole.entities.KotcPublicResultView.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,share_id:share.id,viewed_at:nowIso(),user_agent:req.headers.get('user-agent')||''});}catch{}
  const table=standings(matches||[],participants||[]).map((row:any)=>({...row,cumulative:row.player_id&&aggregateByPlayer[row.player_id]?{sessions_played:aggregateByPlayer[row.player_id].sessions_played||0,wins:aggregateByPlayer[row.player_id].wins||0,losses:aggregateByPlayer[row.player_id].losses||0,matches_played:aggregateByPlayer[row.player_id].matches_played||0,court1_rounds:aggregateByPlayer[row.player_id].court1_rounds||0,best_session_rank:aggregateByPlayer[row.player_id].best_session_rank}:null}));
  return Response.json({session:{name:session.name,status:session.status,actual_session_end:session.actual_session_end},completed_rounds:(rounds||[]).filter(r=>r.status==='completed').length,standings:table,matches:publicMatches});
 }
 const user=await base44.auth.me();if(!user)return Response.json({error:'Unauthorized'},{status:401});const sessionId=String(body.sessionId||'');if(!sessionId)return Response.json({error:'sessionId required'},{status:400});const session=(await base44.asServiceRole.entities.KotcSession.filter({id:sessionId}))?.[0];if(!session)return Response.json({error:'Session not found'},{status:404});
 let allowed=user.role==='admin';if(!allowed){const grants=await base44.asServiceRole.entities.KotcSessionAccess.filter({session_id:session.id,user_id:user.id,status:'active'});allowed=(grants||[]).some(a=>validAccess(a,session.tenant_id,session.id));}if(!allowed)return Response.json({error:'Primary session host access required'},{status:403});
 let shares=await base44.asServiceRole.entities.KotcSessionShare.filter({session_id:session.id,status:'active'});let share=(shares||[]).sort((a,b)=>Date.parse(b.created_date||0)-Date.parse(a.created_date||0))[0]||null;
 if(action==='revoke'){if(share)await base44.asServiceRole.entities.KotcSessionShare.update(share.id,{status:'revoked'});return Response.json({success:true});}
 if(!share){share=await base44.asServiceRole.entities.KotcSessionShare.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,tournament_id:session.tournament_id,token:token(),status:'active',created_by_user_id:user.id});}
 if(action==='get_or_create')return Response.json({success:true,token:share.token,shareId:share.id});
 if(action==='email_players'){
  const baseUrl=String(body.baseUrl||'').replace(/\/$/,'');if(!baseUrl)return Response.json({error:'baseUrl required'},{status:400});const link=`${baseUrl}/kotc-results/${share.token}`;
  const participants=await base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id});const playerIds=[...new Set((participants||[]).map(p=>p.player_id).filter(Boolean))];const players=playerIds.length?await base44.asServiceRole.entities.Player.filter({id:{$in:playerIds}}):[];const byId=Object.fromEntries((players||[]).map(p=>[p.id,p]));const seen=new Set();let sent=0,skipped=0,failed=0;
  for(const p of participants||[]){const email=String(byId[p.player_id]?.email||'').trim().toLowerCase();if(!email||seen.has(email)){skipped++;continue;}seen.add(email);let status='pending',error='';try{await base44.asServiceRole.integrations.Core.SendEmail({to:email,subject:`${session.name} — results`,body:`Your RallyHub results are available here:\n\n${link}\n\nThis is a read-only results link.`});status='sent';sent++;}catch(e){status='failed';error=e?.message||'Email failed';failed++;}await base44.asServiceRole.entities.KotcSessionShareRecipient.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,share_id:share.id,player_id:p.player_id,email,sent_at:status==='sent'?nowIso():undefined,delivery_status:status,error_message:error||undefined});}
  return Response.json({success:true,token:share.token,link,sent,skipped,failed});
 }
 return Response.json({error:'Unknown action'},{status:400});
}catch(error){return Response.json({error:error?.message||'Unexpected results-share error'},{status:500});}});
