import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { sendClubEmail } from './emailRouter.ts';
const clean=(v:any,max=4000)=>String(v??'').trim().slice(0,max); const now=()=>new Date().toISOString();
function esc(v:any){return String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function clareEmailHtml({clubName,logo,title,message,url}:any){const navy='#0b2e59',yellow='#f3c623',light='#f4f8fc';return `<!doctype html><html><body style="margin:0;padding:0;background:#eef3f7;font-family:Arial,Helvetica,sans-serif;color:#172033"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef3f7;padding:24px 10px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#fff;border:1px solid #d6e0ea;border-radius:18px;overflow:hidden"><tr><td style="height:7px;background:${yellow}"></td></tr><tr><td style="background:${navy};padding:24px 28px;text-align:center;color:#fff">${logo?`<img src="${esc(logo)}" alt="${esc(clubName)}" width="76" height="76" style="display:block;margin:0 auto 10px;object-fit:contain">`:''}<div style="font-size:27px;font-weight:900;line-height:1.1">${esc(clubName)}</div><div style="margin-top:7px;color:${yellow};font-size:11px;font-weight:800;letter-spacing:1.8px;text-transform:uppercase">Clare v Galway · Interclub</div></td></tr><tr><td style="padding:30px 30px 28px"><h1 style="margin:0 0 18px;color:${navy};font-size:25px;line-height:1.25">${esc(title)}</h1><div style="font-size:16px;line-height:1.65;color:#25334a;white-space:pre-line">${esc(message)}</div><div style="margin:22px 0 8px;padding:14px 16px;background:${light};border-left:5px solid ${yellow};border-radius:8px;font-size:13px;line-height:1.55;color:#52627d">Please open your player link to make sure you have seen the latest event information.</div><div style="text-align:center;margin:24px 0 8px"><a href="${esc(url)}" style="display:inline-block;background:${navy};color:#fff;text-decoration:none;padding:13px 22px;border-radius:9px;font-size:15px;font-weight:800">View Player Link</a></div><div style="margin-top:28px;font-size:14px;line-height:1.55;color:#334155">Yours in sport,<br><strong style="color:${navy}">Brian Moore</strong><br>Chairperson, Clare Pickleball</div></td></tr><tr><td style="background:${navy};padding:20px 24px;text-align:center;color:#fff"><img src="/assets/brian-moore-profile.png" alt="Brian Moore" width="54" height="54" style="display:block;margin:0 auto 8px;border-radius:50%;object-fit:cover;border:2px solid ${yellow}"><div style="font-size:13px;font-weight:800">Brian Moore · Chairperson</div><div style="margin-top:3px;font-size:12px;color:#dbe7f3">Clare Pickleball</div><div style="margin-top:10px;font-size:10px;color:#b9cce0">Powered by RallyHub</div></td></tr><tr><td style="height:5px;background:${yellow}"></td></tr></table></td></tr></table></body></html>`;}
function validGrant(a:any,tenantId:string){if(!a||a.status!=='active'||String(a.tenant_id||'')!==tenantId)return false;const t=Date.now();return !(a.starts_at&&Date.parse(a.starts_at)>t)&&!(a.ends_at&&Date.parse(a.ends_at)<t);}
async function authorised(base44:any,user:any,event:any){if(user?.role==='admin')return true;const rows=await base44.asServiceRole.entities.TournamentUserAccess.filter({tournament_id:event.tournament_id,user_id:user.id,status:'active'});return (rows||[]).some((a:any)=>validGrant(a,String(event.tenant_id))&&['event_manager','event_host'].includes(a.role));}
async function displayUrl(base44:any,event:any,origin:string){let rows=await base44.asServiceRole.entities.ClubChallengeDisplayToken.filter({challenge_event_id:event.id,active:true},'-created_at',5);let row=rows?.[0];if(!row){row=await base44.asServiceRole.entities.ClubChallengeDisplayToken.create({tenant_id:event.tenant_id,challenge_event_id:event.id,token:`ccd_${crypto.randomUUID().replaceAll('-','')}`,active:true,created_at:now()});}const base=origin&&/^https?:\/\//i.test(origin)?origin.replace(/\/$/,''):'https://rallyhub.ie';return `${base}/club-challenge/display/${row.token}`;}
Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req),user=await base44.auth.me();if(!user)return Response.json({error:'Authentication required'},{status:401});const body=await req.json().catch(()=>({}));const eventId=clean(body.eventId,180),action=clean(body.action||'status',40);if(!eventId)return Response.json({error:'eventId required'},{status:400});
 const event=(await base44.asServiceRole.entities.ClubChallengeEvent.filter({id:eventId}))?.[0];if(!event)return Response.json({error:'Interclub event not found'},{status:404});if(!(await authorised(base44,user,event)))return Response.json({error:'Event manager permission required'},{status:403});
 const current=async()=> (await base44.asServiceRole.entities.InterclubTournamentUpdate.filter({challenge_event_id:event.id,status:'published'},'-published_at',5))?.[0]||null;
 const participants=await base44.asServiceRole.entities.ClubChallengeParticipant.filter({challenge_event_id:event.id},'event_rank',200);const active=(participants||[]).filter((p:any)=>['club_a','club_b'].includes(p.side)&&!['withdrawn','replaced'].includes(p.status));const emails=[...new Set(active.map((p:any)=>clean(p.email,320).toLowerCase()).filter((e:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)))];
 if(action==='status'||action==='preview'){const url=await displayUrl(base44,event,clean(body.origin,500));const club=(event.host_club_id?(await base44.asServiceRole.entities.Club.filter({id:event.host_club_id,tenant_id:event.tenant_id}))?.[0]:null);const clubName=club?.name||event.club_a_name||'Host Club',clubLogo=clean(club?.logo_url||event.club_a_logo_url,1200);const previewMessage=clean(body.message,2000);return Response.json({success:true,update:await current(),eligiblePlayers:active.length,emailRecipients:emails.length,playerLinkUrl:url,clubName,clubLogo,previewHtml:previewMessage?clareEmailHtml({clubName,logo:clubLogo,title:'Tournament Update',message:previewMessage,url}):null});}
 if(action==='remove'){const c=await current();if(c)await base44.asServiceRole.entities.InterclubTournamentUpdate.update(c.id,{status:'removed'});return Response.json({success:true});}
 if(action!=='publish')return Response.json({error:'Unknown action'},{status:400});const title=clean(body.title||'Tournament Update',120),message=clean(body.message,2000);if(!message)return Response.json({error:'Enter a tournament update first.'},{status:400});
 const publishedAt=now();const prior=await current();if(prior)await base44.asServiceRole.entities.InterclubTournamentUpdate.update(prior.id,{status:'removed'});
 const row=await base44.asServiceRole.entities.InterclubTournamentUpdate.create({tenant_id:event.tenant_id,club_id:event.host_club_id||undefined,challenge_event_id:event.id,tournament_id:event.tournament_id,title,message,status:'published',published_at:publishedAt,published_by_user_id:user.id,email_recipient_count:emails.length,email_sent_count:0,email_failed_count:0});
 let sent=0,failed=0;const failures:any[]=[];if(body.sendEmail===true&&emails.length){const url=await displayUrl(base44,event,clean(body.origin,500));const club=(event.host_club_id?(await base44.asServiceRole.entities.Club.filter({id:event.host_club_id,tenant_id:event.tenant_id}))?.[0]:null);const clubName=club?.name||event.club_a_name||'Host Club';const logo=clean(club?.logo_url||event.club_a_logo_url,1200);const subject=`Tournament Update · ${event.club_a_name} vs ${event.club_b_name}`;const text=`Tournament Update\n\n${message}\n\nPlease open your player link to make sure you have the latest event information:\n${url}\n\n${clubName}\nPowered by RallyHub`;
 const html=clareEmailHtml({clubName,logo,title:'Tournament Update',message,url});
 const scope={scopeType:'tenant' as const,purpose:'club_comms',tenantId:String(event.tenant_id),clubId:event.host_club_id?String(event.host_club_id):null};for(const email of emails){try{await sendClubEmail(base44,scope,{to:email,subject,textBody:text,htmlBody:html});sent++;}catch(e){failed++;failures.push({email,error:clean((e as any)?.message||'Send failed',300)});}}
 await base44.asServiceRole.entities.InterclubTournamentUpdate.update(row.id,{email_sent_at:now(),email_sent_count:sent,email_failed_count:failed});}
 try{await base44.asServiceRole.entities.ClubChallengeAudit.create({tenant_id:event.tenant_id,challenge_event_id:event.id,action:'tournament_update_published',user_id:user.id,occurred_at:publishedAt,new_value_json:JSON.stringify({update_id:row.id,email_requested:body.sendEmail===true,email_recipients:emails.length,email_sent:sent,email_failed:failed}),note:'Tournament Update published to Player Link.'});}catch{}
 return Response.json({success:true,update:{...row,email_sent_count:sent,email_failed_count:failed},eligiblePlayers:active.length,emailRecipients:emails.length,sent,failed,failures:failures.slice(0,5)});
}catch(e){console.error('interclubTournamentUpdate',e);return Response.json({error:(e as any)?.message||'Could not publish tournament update.'},{status:500});}});
