import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { sendClubEmail } from './emailRouter.ts';
const clean=(v:any,max=4000)=>String(v??'').trim().slice(0,max); const now=()=>new Date().toISOString();
function esc(v:any){return String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function validGrant(a:any,tenantId:string){if(!a||a.status!=='active'||String(a.tenant_id||'')!==tenantId)return false;const t=Date.now();return !(a.starts_at&&Date.parse(a.starts_at)>t)&&!(a.ends_at&&Date.parse(a.ends_at)<t);}
async function authorised(base44:any,user:any,event:any){if(user?.role==='admin')return true;const rows=await base44.asServiceRole.entities.TournamentUserAccess.filter({tournament_id:event.tournament_id,user_id:user.id,status:'active'});return (rows||[]).some((a:any)=>validGrant(a,String(event.tenant_id))&&['event_manager','event_host'].includes(a.role));}
async function displayUrl(base44:any,event:any,origin:string){let rows=await base44.asServiceRole.entities.ClubChallengeDisplayToken.filter({challenge_event_id:event.id,active:true},'-created_at',5);let row=rows?.[0];if(!row){row=await base44.asServiceRole.entities.ClubChallengeDisplayToken.create({tenant_id:event.tenant_id,challenge_event_id:event.id,token:`ccd_${crypto.randomUUID().replaceAll('-','')}`,active:true,created_at:now()});}const base=origin&&/^https?:\/\//i.test(origin)?origin.replace(/\/$/,''):'https://rallyhub.ie';return `${base}/club-challenge/display/${row.token}`;}
Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req),user=await base44.auth.me();if(!user)return Response.json({error:'Authentication required'},{status:401});const body=await req.json().catch(()=>({}));const eventId=clean(body.eventId,180),action=clean(body.action||'status',40);if(!eventId)return Response.json({error:'eventId required'},{status:400});
 const event=(await base44.asServiceRole.entities.ClubChallengeEvent.filter({id:eventId}))?.[0];if(!event)return Response.json({error:'Interclub event not found'},{status:404});if(!(await authorised(base44,user,event)))return Response.json({error:'Event manager permission required'},{status:403});
 const current=async()=> (await base44.asServiceRole.entities.InterclubTournamentUpdate.filter({challenge_event_id:event.id,status:'published'},'-published_at',5))?.[0]||null;
 const participants=await base44.asServiceRole.entities.ClubChallengeParticipant.filter({challenge_event_id:event.id},'event_rank',200);const active=(participants||[]).filter((p:any)=>['club_a','club_b'].includes(p.side)&&!['withdrawn','replaced'].includes(p.status));const emails=[...new Set(active.map((p:any)=>clean(p.email,320).toLowerCase()).filter((e:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)))];
 if(action==='status')return Response.json({success:true,update:await current(),eligiblePlayers:active.length,emailRecipients:emails.length});
 if(action==='remove'){const c=await current();if(c)await base44.asServiceRole.entities.InterclubTournamentUpdate.update(c.id,{status:'removed'});return Response.json({success:true});}
 if(action!=='publish')return Response.json({error:'Unknown action'},{status:400});const title=clean(body.title||'Tournament Update',120),message=clean(body.message,2000);if(!message)return Response.json({error:'Enter a tournament update first.'},{status:400});
 const publishedAt=now();const prior=await current();if(prior)await base44.asServiceRole.entities.InterclubTournamentUpdate.update(prior.id,{status:'removed'});
 const row=await base44.asServiceRole.entities.InterclubTournamentUpdate.create({tenant_id:event.tenant_id,club_id:event.host_club_id||undefined,challenge_event_id:event.id,tournament_id:event.tournament_id,title,message,status:'published',published_at:publishedAt,published_by_user_id:user.id,email_recipient_count:emails.length,email_sent_count:0,email_failed_count:0});
 let sent=0,failed=0;const failures:any[]=[];if(body.sendEmail===true&&emails.length){const url=await displayUrl(base44,event,clean(body.origin,500));const club=(event.host_club_id?(await base44.asServiceRole.entities.Club.filter({id:event.host_club_id,tenant_id:event.tenant_id}))?.[0]:null);const clubName=club?.name||event.club_a_name||'Host Club';const logo=clean(club?.logo_url||event.club_a_logo_url,1200);const subject=`Tournament Update · ${event.club_a_name} vs ${event.club_b_name}`;const text=`Tournament Update\n\n${message}\n\nPlease open your player link to make sure you have the latest event information:\n${url}\n\n${clubName}\nPowered by RallyHub`;
 const html=`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#111827"><div style="text-align:center;padding:18px;border-bottom:1px solid #e5e7eb">${logo?`<img src="${esc(logo)}" alt="${esc(clubName)}" style="max-height:72px;max-width:180px">`:''}<div style="font-size:20px;font-weight:700;margin-top:8px">${esc(clubName)}</div></div><div style="padding:26px"><h1 style="font-size:24px;margin:0 0 16px">Tournament Update</h1><p style="font-size:16px;line-height:1.6;white-space:pre-line">${esc(message)}</p><p style="font-size:14px;line-height:1.5;color:#4b5563">Please open your player link to make sure you have seen the latest event information.</p><p style="margin:24px 0"><a href="${esc(url)}" style="display:inline-block;background:#111827;color:#fff;text-decoration:none;padding:12px 20px;border-radius:8px;font-weight:700">View Player Link</a></p></div><div style="text-align:center;border-top:1px solid #e5e7eb;padding:16px;font-size:12px;color:#6b7280">${esc(clubName)} · Powered by RallyHub</div></div>`;
 const scope={scopeType:'tenant' as const,purpose:'club_comms',tenantId:String(event.tenant_id),clubId:event.host_club_id?String(event.host_club_id):null};for(const email of emails){try{await sendClubEmail(base44,scope,{to:email,subject,textBody:text,htmlBody:html});sent++;}catch(e){failed++;failures.push({email,error:clean((e as any)?.message||'Send failed',300)});}}
 await base44.asServiceRole.entities.InterclubTournamentUpdate.update(row.id,{email_sent_at:now(),email_sent_count:sent,email_failed_count:failed});}
 try{await base44.asServiceRole.entities.ClubChallengeAudit.create({tenant_id:event.tenant_id,challenge_event_id:event.id,action:'tournament_update_published',user_id:user.id,occurred_at:publishedAt,new_value_json:JSON.stringify({update_id:row.id,email_requested:body.sendEmail===true,email_recipients:emails.length,email_sent:sent,email_failed:failed}),note:'Tournament Update published to Player Link.'});}catch{}
 return Response.json({success:true,update:{...row,email_sent_count:sent,email_failed_count:failed},eligiblePlayers:active.length,emailRecipients:emails.length,sent,failed,failures:failures.slice(0,5)});
}catch(e){console.error('interclubTournamentUpdate',e);return Response.json({error:(e as any)?.message||'Could not publish tournament update.'},{status:500});}});
