import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { sendClubEmail } from './emailRouter.ts';
const clean=(v:any,max=4000)=>String(v??'').trim().slice(0,max); const now=()=>new Date().toISOString();
function esc(v:any){return String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
const EMAIL_TEMPLATES={clare_interclub_approved:{id:'clare_interclub_approved',name:'Clare v Galway Interclub — Approved',description:'Approved 3 Oct 2026 master artwork. Header and footer are locked image assets from the approved results email.'}};
function clareInterclubApprovedHtml({title,message,url,origin}:any){const base=origin&&/^https?:\/\//i.test(origin)?String(origin).replace(/\/$/,''):'https://rallyhub.ie';const header=`${base}/email-templates/clare-interclub/header.png`,footer=`${base}/email-templates/clare-interclub/footer.png`;return `<!doctype html><html><body style="margin:0;padding:0;background:#f3f3f3"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f3f3f3"><tr><td align="center" style="padding:0"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:720px;background:#fff;border-collapse:collapse"><tr><td style="padding:0"><img src="${esc(header)}" alt="Clare v Galway Interclub" width="720" style="display:block;width:100%;max-width:720px;height:auto;border:0"></td></tr><tr><td style="padding:26px 28px 30px;font-family:Arial,Helvetica,sans-serif;color:#17347c;font-size:16px;line-height:1.55"><h1 style="margin:0 0 18px;color:#0755a8;font-size:25px;line-height:1.2">${esc(title)}</h1><div style="white-space:pre-line">${esc(message)}</div><div style="text-align:center;margin:26px 0 4px"><a href="${esc(url)}" style="display:inline-block;background:#0755a8;color:#fff;text-decoration:none;font-weight:700;font-size:17px;padding:14px 26px;border-radius:10px">View Player Link &nbsp;›</a></div></td></tr><tr><td style="padding:0"><img src="${esc(footer)}" alt="Brian Moore · Clare Pickleball · RallyHub" width="720" usemap="#clareInterclubFooterLinks" style="display:block;width:100%;max-width:720px;height:auto;border:0"><map name="clareInterclubFooterLinks"><area shape="rect" coords="180,195,305,255" href="https://wa.me/353878100333" target="_blank" alt="WhatsApp Brian Moore"><area shape="rect" coords="305,195,535,255" href="mailto:clarepb2025@gmail.com" alt="Email Clare Pickleball"><area shape="rect" coords="535,195,720,255" href="https://clarepickleball.ie/" target="_blank" alt="Clare Pickleball website"><area shape="rect" coords="305,300,380,370" href="https://www.facebook.com/clarepickleball" target="_blank" alt="Clare Pickleball on Facebook"><area shape="rect" coords="380,300,455,370" href="https://www.instagram.com/clarepickleball/" target="_blank" alt="Clare Pickleball on Instagram"><area shape="rect" coords="455,300,535,370" href="https://clarepickleball.ie/" target="_blank" alt="Clare Pickleball website"><area shape="rect" coords="535,285,720,380" href="https://rallyhub.ie/" target="_blank" alt="RallyHub"></map></td></tr></table></td></tr></table></body></html>`;}
function renderEmailTemplate(templateId:string,args:any){if(templateId==='clare_interclub_approved')return clareInterclubApprovedHtml(args);throw new Error('Unknown email template');}
function validGrant(a:any,tenantId:string){if(!a||a.status!=='active'||String(a.tenant_id||'')!==tenantId)return false;const t=Date.now();return !(a.starts_at&&Date.parse(a.starts_at)>t)&&!(a.ends_at&&Date.parse(a.ends_at)<t);}
async function authorised(base44:any,user:any,event:any){if(user?.role==='admin')return true;const rows=await base44.asServiceRole.entities.TournamentUserAccess.filter({tournament_id:event.tournament_id,user_id:user.id,status:'active'});return (rows||[]).some((a:any)=>validGrant(a,String(event.tenant_id))&&['event_manager','event_host'].includes(a.role));}
async function displayUrl(base44:any,event:any,origin:string){let rows=await base44.asServiceRole.entities.ClubChallengeDisplayToken.filter({challenge_event_id:event.id,active:true},'-created_at',5);let row=rows?.[0];if(!row){row=await base44.asServiceRole.entities.ClubChallengeDisplayToken.create({tenant_id:event.tenant_id,challenge_event_id:event.id,token:`ccd_${crypto.randomUUID().replaceAll('-','')}`,active:true,created_at:now()});}const base=origin&&/^https?:\/\//i.test(origin)?origin.replace(/\/$/,''):'https://rallyhub.ie';return `${base}/club-challenge/display/${row.token}`;}
Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req),user=await base44.auth.me();if(!user)return Response.json({error:'Authentication required'},{status:401});const body=await req.json().catch(()=>({}));const eventId=clean(body.eventId,180),action=clean(body.action||'status',40);if(!eventId)return Response.json({error:'eventId required'},{status:400});
 const event=(await base44.asServiceRole.entities.ClubChallengeEvent.filter({id:eventId}))?.[0];if(!event)return Response.json({error:'Interclub event not found'},{status:404});if(!(await authorised(base44,user,event)))return Response.json({error:'Event manager permission required'},{status:403});
 const current=async()=> (await base44.asServiceRole.entities.InterclubTournamentUpdate.filter({challenge_event_id:event.id,status:'published'},'-published_at',5))?.[0]||null;
 const participants=await base44.asServiceRole.entities.ClubChallengeParticipant.filter({challenge_event_id:event.id},'event_rank',200);const active=(participants||[]).filter((p:any)=>['club_a','club_b'].includes(p.side));const emails=[...new Set(active.map((p:any)=>clean(p.email,320).toLowerCase()).filter((e:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)))];
 if(action==='status'||action==='preview'){const origin=clean(body.origin,500);const url=await displayUrl(base44,event,origin);const club=(event.host_club_id?(await base44.asServiceRole.entities.Club.filter({id:event.host_club_id,tenant_id:event.tenant_id}))?.[0]:null);const clubName=club?.name||event.club_a_name||'Host Club',clubLogo=clean(club?.logo_url||event.club_a_logo_url,1200);const previewMessage=clean(body.message,2000),templateId=clean(body.templateId||'clare_interclub_approved',80);return Response.json({success:true,update:await current(),eligiblePlayers:active.length,emailRecipients:emails.length,playerLinkUrl:url,clubName,clubLogo,templates:Object.values(EMAIL_TEMPLATES),selectedTemplateId:templateId,previewHtml:previewMessage?renderEmailTemplate(templateId,{title:'Tournament Update',message:previewMessage,url,origin}):null});}
 if(action==='remove'){const c=await current();if(c)await base44.asServiceRole.entities.InterclubTournamentUpdate.update(c.id,{status:'removed'});return Response.json({success:true});}
 if(action!=='publish')return Response.json({error:'Unknown action'},{status:400});const title=clean(body.title||'Tournament Update',120),message=clean(body.message,2000);if(!message)return Response.json({error:'Enter a tournament update first.'},{status:400});
 const publishedAt=now();const prior=await current();if(prior)await base44.asServiceRole.entities.InterclubTournamentUpdate.update(prior.id,{status:'removed'});
 const row=await base44.asServiceRole.entities.InterclubTournamentUpdate.create({tenant_id:event.tenant_id,club_id:event.host_club_id||undefined,challenge_event_id:event.id,tournament_id:event.tournament_id,title,message,status:'published',published_at:publishedAt,published_by_user_id:user.id,email_recipient_count:emails.length,email_sent_count:0,email_failed_count:0});
 let sent=0,failed=0;const failures:any[]=[];if(body.sendEmail===true&&emails.length){const url=await displayUrl(base44,event,clean(body.origin,500));const club=(event.host_club_id?(await base44.asServiceRole.entities.Club.filter({id:event.host_club_id,tenant_id:event.tenant_id}))?.[0]:null);const clubName=club?.name||event.club_a_name||'Host Club';const logo=clean(club?.logo_url||event.club_a_logo_url,1200);const subject=`Tournament Update · ${event.club_a_name} vs ${event.club_b_name}`;const text=`Tournament Update\n\n${message}\n\nPlease open your player link to make sure you have the latest event information:\n${url}\n\n${clubName}\nPowered by RallyHub`;
 const templateId=clean(body.templateId||'clare_interclub_approved',80);const html=renderEmailTemplate(templateId,{title:'Tournament Update',message,url,origin:clean(body.origin,500)});
 const scope={scopeType:'tenant' as const,purpose:'club_comms',tenantId:String(event.tenant_id),clubId:event.host_club_id?String(event.host_club_id):null};for(const email of emails){try{await sendClubEmail(base44,scope,{to:email,subject,textBody:text,htmlBody:html});sent++;}catch(e){failed++;failures.push({email,error:clean((e as any)?.message||'Send failed',300)});}}
 await base44.asServiceRole.entities.InterclubTournamentUpdate.update(row.id,{email_sent_at:now(),email_sent_count:sent,email_failed_count:failed});}
 try{await base44.asServiceRole.entities.ClubChallengeAudit.create({tenant_id:event.tenant_id,challenge_event_id:event.id,action:'tournament_update_published',user_id:user.id,occurred_at:publishedAt,new_value_json:JSON.stringify({update_id:row.id,email_requested:body.sendEmail===true,email_recipients:emails.length,email_sent:sent,email_failed:failed}),note:'Tournament Update published to Player Link.'});}catch{}
 return Response.json({success:true,update:{...row,email_sent_count:sent,email_failed_count:failed},eligiblePlayers:active.length,emailRecipients:emails.length,sent,failed,failures:failures.slice(0,5)});
}catch(e){console.error('interclubTournamentUpdate',e);return Response.json({error:(e as any)?.message||'Could not publish tournament update.'},{status:500});}});
