import { createClientFromRequest } from 'npm:@base44/sdk@0.8.29';

function teamScore(matches:any[],event:any){let a=0,b=0;for(const m of matches.filter((x:any)=>!x.is_showcase&&['completed','draw'].includes(x.status))){if(m.winner==='club_a'){a+=Number(event.win_points??2);b+=Number(event.loss_points??0);}else if(m.winner==='club_b'){b+=Number(event.win_points??2);a+=Number(event.loss_points??0);}else{a+=Number(event.draw_points??1);b+=Number(event.draw_points??1);}}return {clubA:a,clubB:b};}
function stats(matches:any[],participants:any[]){const out:any={};const ensure=(id:string,side:string)=>out[id]||(out[id]={id,side,gamesPlayed:0,pointsFor:0,pointsAgainst:0,wins:0,draws:0,losses:0,pointDiff:0});for(const m of matches){if(m.is_showcase||!['completed','draw','retired','forfeit'].includes(m.status))continue;const a=Number(m.score_a||0),b=Number(m.score_b||0);for(const id of (m.club_a_participant_ids||[])){const s=ensure(String(id),'club_a');s.gamesPlayed++;s.pointsFor+=a;s.pointsAgainst+=b;m.winner==='club_a'?s.wins++:m.winner==='draw'?s.draws++:s.losses++;}for(const id of (m.club_b_participant_ids||[])){const s=ensure(String(id),'club_b');s.gamesPlayed++;s.pointsFor+=b;s.pointsAgainst+=a;m.winner==='club_b'?s.wins++:m.winner==='draw'?s.draws++:s.losses++;}}Object.values(out).forEach((s:any)=>s.pointDiff=s.pointsFor-s.pointsAgainst);return out;}
function sidePodium(statMap:any,participants:any[],side:string){return participants.filter((p:any)=>p.side===side&&statMap[String(p.id)]?.gamesPlayed>0).map((p:any)=>({id:p.id,display_name:p.display_name,...statMap[String(p.id)]})).sort((a:any,b:any)=>b.pointsFor-a.pointsFor||b.wins-a.wins||b.pointDiff-a.pointDiff||String(a.display_name||'').localeCompare(String(b.display_name||''),'en',{sensitivity:'base'})).slice(0,3);}

Deno.serve(async(req)=>{
 try{
  const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const resultToken=String(body.token||'').trim();
  if(!/^ipr_[0-9a-f]{32}$/i.test(resultToken))return Response.json({error:'Private results link is invalid.'},{status:404});
  const accessRows=await base44.asServiceRole.entities.InterclubParticipantResultToken.filter({token:resultToken,status:'active'},'-created_at',5);const access=accessRows?.[0];if(!access)return Response.json({error:'Private results link is invalid or inactive.'},{status:404});
  const [events,participantRows,participants,matches]=await Promise.all([base44.asServiceRole.entities.ClubChallengeEvent.filter({id:access.challenge_event_id}),base44.asServiceRole.entities.ClubChallengeParticipant.filter({id:access.participant_id}),base44.asServiceRole.entities.ClubChallengeParticipant.filter({challenge_event_id:access.challenge_event_id},'event_rank',100),base44.asServiceRole.entities.ClubChallengeMatch.filter({challenge_event_id:access.challenge_event_id},'round_number',200)]);
  const event=events?.[0],participant=participantRows?.[0];if(!event||!participant||!['completed','archived'].includes(event.status))return Response.json({error:'These personal results are not available yet.'},{status:409});
  const statMap=stats(matches,participants),own=statMap[String(participant.id)]||{gamesPlayed:0,pointsFor:0,pointsAgainst:0,wins:0,draws:0,losses:0,pointDiff:0};const team=teamScore(matches,event);
  const ownMatches=matches.filter((m:any)=>!m.is_showcase&&[...(m.club_a_participant_ids||[]),...(m.club_b_participant_ids||[])].map(String).includes(String(participant.id))&&['completed','draw','retired','forfeit'].includes(m.status)).sort((a:any,b:any)=>Number(a.round_number)-Number(b.round_number)).map((m:any)=>({round:m.round_number,court:m.court_number,scoreA:m.score_a,scoreB:m.score_b,side:participant.side,won:m.winner===participant.side,draw:m.winner==='draw'}));
  try{await base44.asServiceRole.entities.InterclubParticipantResultToken.update(access.id,{last_used_at:new Date().toISOString()});}catch{}
  return Response.json({success:true,event:{id:event.id,clubA:event.club_a_name,clubB:event.club_b_name,status:event.status,scoreA:team.clubA,scoreB:team.clubB},player:{id:participant.id,name:participant.display_name,side:participant.side,stats:own},podiums:{clubA:sidePodium(statMap,participants,'club_a'),clubB:sidePodium(statMap,participants,'club_b')},rounds:ownMatches});
 }catch(error){console.error('getInterclubParticipantResult failed',error);return Response.json({error:'Unable to load personal Interclub results right now.'},{status:500});}
});