import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

const RESOLVED=new Set(['completed','retired','abandoned','not_played']);
const RUNTIME_VERSION='kotc-prepare-2026-09-10-r8';
function nowIso(){return new Date().toISOString();}
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
function isRateLimit(error:any){return /rate limit|too many requests|\b429\b/i.test(String(error?.message||error||''));}
async function retry<T>(label:string,fn:()=>Promise<T>,attempts=5){let last:any;for(let i=0;i<attempts;i++){try{return await fn();}catch(error){last=error;if(!isRateLimit(error)||i===attempts-1)throw error;const delay=Math.min(2400,300*Math.pow(2,i))+Math.floor(Math.random()*120);console.warn('KOTC prepare rate limit — retrying',{label,attempt:i+1,delay});await sleep(delay);}}throw last;}
function stableHash(value:any){const text=String(value??'');let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function pairKey(a:string,b:string){return [a,b].sort().join('|');}
function validAccess(a:any,tenantId:string,sessionId:string){if(!a||a.status!=='active'||String(a.tenant_id)!==String(tenantId)||String(a.session_id)!==String(sessionId)||a.role!=='session_host')return false;const now=Date.now();if(a.starts_at&&Date.parse(a.starts_at)>now)return false;if(a.ends_at&&Date.parse(a.ends_at)<now)return false;return true;}
function keepsLocks(teams:string[][],locks:any[]){return (locks||[]).every((l:any)=>{const a=String(l.participant1_id),b=String(l.participant2_id),flat=teams.flat();return !(flat.includes(a)&&flat.includes(b))||teams.some(t=>t.includes(a)&&t.includes(b));});}
function splitFour(ids:string[],partnerCounts:any,seed:string,locks:any[]=[]){const [a,b,c,d]=ids;const opts=[[[a,b],[c,d]],[[a,c],[b,d]],[[a,d],[b,c]]].filter((x:any)=>keepsLocks(x,locks)).map((x:any)=>({teamA:x[0],teamB:x[1],pen:(partnerCounts[pairKey(x[0][0],x[0][1])]||0)+(partnerCounts[pairKey(x[1][0],x[1][1])]||0),key:`${x[0].join(',')}|${x[1].join(',')}`}));if(!opts.length)throw new Error('Locked-pair constraints cannot be satisfied on this court.');return opts.sort((x:any,y:any)=>x.pen-y.pen||stableHash(`${seed}|${x.key}`)-stableHash(`${seed}|${y.key}`)||x.key.localeCompare(y.key))[0];}
function crossSplit(pairOne:string[],pairTwo:string[],partnerCounts:any,seed:string,locks:any[]=[]){const [a,b]=pairOne,[c,d]=pairTwo;const opts=[[[a,c],[b,d]],[[a,d],[b,c]],[[a,b],[c,d]]].filter((x:any)=>keepsLocks(x,locks)).map((x:any)=>({teamA:x[0],teamB:x[1],pen:(partnerCounts[pairKey(x[0][0],x[0][1])]||0)+(partnerCounts[pairKey(x[1][0],x[1][1])]||0),key:`${x[0].join(',')}|${x[1].join(',')}`}));if(!opts.length)throw new Error('Locked-pair constraints cannot be satisfied on this court.');return opts.sort((x:any,y:any)=>x.pen-y.pen||stableHash(`${seed}|${x.key}`)-stableHash(`${seed}|${y.key}`)||x.key.localeCompare(y.key))[0];}
function sportingDestinations(courts:any[],results:any){const n=courts.length,w:any={},l:any={};for(const c of courts){const side=results[c.courtRank];w[c.courtRank]=side==='A'?[...c.teamA]:[...c.teamB];l[c.courtRank]=side==='A'?[...c.teamB]:[...c.teamA];}const d:any={};if(n===1){d[1]={pairOne:w[1],pairTwo:l[1]};return d;}for(let r=1;r<=n;r++){if(r===1)d[r]={pairOne:w[1],pairTwo:w[2]};else if(r===n)d[r]={pairOne:l[n-1],pairTwo:l[n]};else d[r]={pairOne:l[r-1],pairTwo:w[r+1]};}return d;}
function enforceLocks(slots:any[],locks:any[],eligible:Set<string>){const out=slots.map(s=>({...s}));const lockedIds=new Set((locks||[]).flatMap((l:any)=>[String(l.participant1_id),String(l.participant2_id)]));const together=(a:string,b:string)=>{const sa=out.find((s:any)=>String(s.participant_id)===a),sb=out.find((s:any)=>String(s.participant_id)===b);return !!sa&&!!sb&&Number(sa.ladder_court_rank)===Number(sb.ladder_court_rank)&&String(sa.team_side)===String(sb.team_side);};for(const lock of locks||[]){const a=String(lock.participant1_id),b=String(lock.participant2_id),ia=out.findIndex((s:any)=>String(s.participant_id)===a),ib=out.findIndex((s:any)=>String(s.participant_id)===b);if(eligible.has(a)&&eligible.has(b)&&((ia<0)!==(ib<0)))throw new Error(`Locked pair ${lock.pair_name||''} was split between court and bench.`);if(ia<0||ib<0||together(a,b))continue;if(Number(out[ia].ladder_court_rank)!==Number(out[ib].ladder_court_rank))throw new Error(`Locked pair ${lock.pair_name||''} reached different destination courts.`);const candidates:any[]=[];for(const [anchorIndex,otherIndex] of [[ia,ib],[ib,ia]] as any){const anchor=out[anchorIndex],mateIndex=out.findIndex((s:any,idx:number)=>idx!==anchorIndex&&Number(s.ladder_court_rank)===Number(anchor.ladder_court_rank)&&String(s.team_side)===String(anchor.team_side));if(mateIndex>=0&&!lockedIds.has(String(out[mateIndex].participant_id)))candidates.push({anchorIndex,otherIndex,mateIndex});}if(!candidates.length)throw new Error(`Locked pair ${lock.pair_name||''} could not be kept together on their earned court.`);const c=candidates.sort((x:any,y:any)=>x.anchorIndex-y.anchorIndex)[0],locked=out[c.otherIndex].participant_id,single=out[c.mateIndex].participant_id;out[c.mateIndex]={...out[c.mateIndex],participant_id:locked,assignment_type:'locked_pair_override'};out[c.otherIndex]={...out[c.otherIndex],participant_id:single,assignment_type:'locked_pair_override'};if(!together(a,b))throw new Error(`Locked pair ${lock.pair_name||''} could not be kept together.`);}return out;}

Deno.serve(async req=>{try{
 const base44=createClientFromRequest(req),user=await base44.auth.me();if(!user)return Response.json({error:'Unauthorized'},{status:401});
 const body=await req.json().catch(()=>({})),sessionId=String(body.sessionId||''),fromRoundId=String(body.fromRoundId||''),fromRoundNumber=Number(body.fromRoundNumber||0);if(!sessionId||!fromRoundId||!fromRoundNumber)return Response.json({error:'sessionId, fromRoundId and fromRoundNumber are required'},{status:400});
 const session=(await retry('session read',()=>base44.asServiceRole.entities.KotcSession.filter({id:sessionId})))?.[0];if(!session)return Response.json({error:'KOTC session not found'},{status:404});
 let allowed=user.role==='admin';if(!allowed){const grants=await retry('host access read',()=>base44.asServiceRole.entities.KotcSessionAccess.filter({session_id:session.id,user_id:user.id,status:'active'}));allowed=(grants||[]).some((a:any)=>validAccess(a,session.tenant_id,session.id));}if(!allowed)return Response.json({error:'Primary host permission required'},{status:403});
 // A lost response/repeated tap after a successful preparation must return the already-created round.
 if(Number(session.current_round_number)>fromRoundNumber&&String(session.current_round_id)!==fromRoundId){const ready=(await retry('existing prepared round read',()=>base44.asServiceRole.entities.KotcRound.filter({id:session.current_round_id,session_id:session.id})))?.[0];if(ready)return Response.json({success:true,alreadyPrepared:true,session,round:ready,runtimeVersion:RUNTIME_VERSION});}
 if(Number(body.expectedSessionRevision)!==Number(session.revision||0))return Response.json({error:'Session changed since you opened it. Refreshing is required before preparing another round.',conflict:true,currentSessionRevision:Number(session.revision||0)},{status:409});
 const currentRound=(await retry('current round read',()=>base44.asServiceRole.entities.KotcRound.filter({id:fromRoundId,session_id:session.id})))?.[0];if(!currentRound||Number(currentRound.round_number)!==fromRoundNumber)return Response.json({error:'Current round not found'},{status:404});if(!['started','completed'].includes(currentRound.status))return Response.json({error:'Current round must be live before preparing the next round.'},{status:409});
 const matches=(await retry('current matches read',()=>base44.asServiceRole.entities.KotcMatch.filter({round_id:currentRound.id,session_id:session.id}))).sort((a:any,b:any)=>Number(a.ladder_court_rank)-Number(b.ladder_court_rank));const unresolved=matches.filter((m:any)=>!RESOLVED.has(m.status));if(unresolved.length)return Response.json({error:`${unresolved.length} current-round match result(s) unresolved.`},{status:409});const playable=matches.filter((m:any)=>m.status==='completed');if(!playable.length)return Response.json({error:'No completed sporting results are available.'},{status:409});
 const participants=await retry('participants read',()=>base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id}));const fixedPairs=await retry('fixed pairs read',()=>base44.asServiceRole.entities.KotcFixedPair.filter({session_id:session.id,status:'active'}));const locks=(fixedPairs||[]).filter((p:any)=>p.pair_source==='host_selected'),nextNumber=fromRoundNumber+1;
 const eligible=participants.filter((p:any)=>{if(['injured','left','no_show','withdrawn','replaced'].includes(p.status))return false;const effective=Number(p.availability_effective_from_round||0),again=Number(p.available_again_from_round||0);if(['temporarily_unavailable','voluntary_rest'].includes(p.status))return again>0&&nextNumber>=again;if(p.status==='leaving_early')return !(effective>0&&nextNumber>=effective);return ['registered','confirmed','present'].includes(p.status);});
 const activeCourts=Math.min(Number(session.available_court_limit||session.venue_court_limit||4),Math.floor(eligible.length/4));if(activeCourts<1)return Response.json({error:'Fewer than four available players remain.'},{status:409});const currentActive=Number(currentRound.active_court_count||playable.length),courts=playable.map((m:any)=>({courtRank:Number(m.ladder_court_rank),teamA:[...(m.team_a_participant_ids||[])],teamB:[...(m.team_b_participant_ids||[])]})),results:any=Object.fromEntries(playable.map((m:any)=>[Number(m.ladder_court_rank),m.winner_side]));
 const history=await retry('completed history read',()=>base44.asServiceRole.entities.KotcMatch.filter({session_id:session.id,status:'completed'}));const partnerCounts:any={};for(const m of history)for(const pair of [m.team_a_participant_ids||[],m.team_b_participant_ids||[]])if(pair.length===2){const k=pairKey(pair[0],pair[1]);partnerCounts[k]=(partnerCounts[k]||0)+1;}
 const currentIds=new Set(courts.flatMap((c:any)=>[...c.teamA,...c.teamB])),benchIds=new Set(eligible.map((p:any)=>p.id).filter((id:string)=>!currentIds.has(id))),court1=new Set(courts.find((c:any)=>c.courtRank===1)?[...courts.find((c:any)=>c.courtRank===1).teamA,...courts.find((c:any)=>c.courtRank===1).teamB]:[]),currentRank:any={};for(const c of courts)for(const id of [...c.teamA,...c.teamB])currentRank[id]=c.courtRank;const destination:any={};for(const c of courts){const winners=results[c.courtRank]==='A'?c.teamA:c.teamB,losers=results[c.courtRank]==='A'?c.teamB:c.teamA;for(const id of winners)destination[id]=Math.max(1,c.courtRank-1);for(const id of losers)destination[id]=Math.min(currentActive,c.courtRank+1);}for(const p of eligible)if(destination[p.id]==null)destination[p.id]=currentActive;
 const projected=eligible.map((p:any)=>({...p,rounds_played:Number(p.rounds_played||0)+(currentIds.has(p.id)?1:0),fairness_benches:Number(p.fairness_benches||0)+(benchIds.has(p.id)?1:0),consecutive_rounds_played:currentIds.has(p.id)?Number(p.consecutive_rounds_played||0)+1:0,consecutive_court1_rounds:currentIds.has(p.id)&&court1.has(p.id)?Number(p.consecutive_court1_rounds||0)+1:0,court1_rounds:Number(p.court1_rounds||0)+(currentIds.has(p.id)&&court1.has(p.id)?1:0),_previousBench:benchIds.has(p.id)}));const benchPlaces=eligible.length-activeCourts*4,lockedIds=new Set(locks.flatMap((l:any)=>[String(l.participant1_id),String(l.participant2_id)]));const selected=[...projected].sort((a:any,b:any)=>Number(lockedIds.has(String(a.id)))-Number(lockedIds.has(String(b.id)))||Number(a.fairness_benches)-Number(b.fairness_benches)||Number(a._previousBench)-Number(b._previousBench)||Number(b.consecutive_rounds_played)-Number(a.consecutive_rounds_played)||Number(b.rounds_played)-Number(a.rounds_played)||stableHash(`${session.random_seed}|r${nextNumber}|${a.id}`)-stableHash(`${session.random_seed}|r${nextNumber}|${b.id}`)).slice(0,benchPlaces).map((p:any)=>p.id),selectedSet=new Set(selected);let finalSlots:any[]=[];
 if(activeCourts===currentActive){const destinations=sportingDestinations(courts,results),sporting:any[]=[];for(const [rankText,d] of Object.entries(destinations) as any){const rank=Number(rankText),split=crossSplit(d.pairOne,d.pairTwo,partnerCounts,`${session.random_seed}|r${nextNumber}|c${rank}`,locks);for(const [side,ids] of [['A',split.teamA],['B',split.teamB]] as any)for(let i=0;i<2;i++)sporting.push({participant_id:ids[i],ladder_court_rank:rank,team_side:side,slot_number:i+1,destination_from_prior_round:rank});}const sportingSet=new Set(sporting.map((s:any)=>s.participant_id)),outgoing=sporting.filter((s:any)=>selectedSet.has(s.participant_id)).sort((a:any,b:any)=>a.ladder_court_rank-b.ladder_court_rank||String(a.team_side).localeCompare(String(b.team_side))||a.slot_number-b.slot_number),replacements=projected.filter((p:any)=>!sportingSet.has(p.id)&&!selectedSet.has(p.id)).map((p:any)=>p.id).sort((a:string,b:string)=>stableHash(`${session.random_seed}|r${nextNumber}|${a}`)-stableHash(`${session.random_seed}|r${nextNumber}|${b}`));if(outgoing.length!==replacements.length)return Response.json({error:'Fairness substitution invariant failed.'},{status:409});const replacementFor=new Map(outgoing.map((s:any,i:number)=>[s.participant_id,replacements[i]]));finalSlots=sporting.map((s:any)=>replacementFor.has(s.participant_id)?{...s,replacement_for_participant_id:s.participant_id,participant_id:replacementFor.get(s.participant_id),assignment_type:'fairness_return'}:{...s,assignment_type:'sporting_movement'});}else{const activeIds=projected.filter((p:any)=>!selectedSet.has(p.id)).map((p:any)=>p.id).sort((a:string,b:string)=>Number(destination[a]||99)-Number(destination[b]||99)||Number(currentRank[a]||99)-Number(currentRank[b]||99)||stableHash(`${session.random_seed}|transition|r${nextNumber}|${a}`)-stableHash(`${session.random_seed}|transition|r${nextNumber}|${b}`));if(activeIds.length!==activeCourts*4)return Response.json({error:'Court transition invariant failed.'},{status:409});for(let rank=1;rank<=activeCourts;rank++){const four=activeIds.slice((rank-1)*4,rank*4),split=splitFour(four,partnerCounts,`${session.random_seed}|transition|r${nextNumber}|c${rank}`,locks);for(const [side,ids] of [['A',split.teamA],['B',split.teamB]] as any)for(let i=0;i<2;i++)finalSlots.push({participant_id:ids[i],ladder_court_rank:rank,team_side:side,slot_number:i+1,assignment_type:'sporting_movement',destination_from_prior_round:destination[ids[i]]});}}
 finalSlots=enforceLocks(finalSlots,locks,new Set(eligible.map((p:any)=>String(p.id))));
 const existing=(await retry('existing next round read',()=>base44.asServiceRole.entities.KotcRound.filter({session_id:session.id,round_number:nextNumber}))).filter((r:any)=>!['superseded','abandoned'].includes(r.status)).sort((a:any,b:any)=>Number(b.proposal_revision||0)-Number(a.proposal_revision||0))[0];if(existing){const updatedSession=await retry('reconcile session',()=>base44.asServiceRole.entities.KotcSession.update(session.id,{revision:Number(session.revision||0)+1,last_command_id:String(body.commandId||'prepare-next'),current_round_number:nextNumber,current_round_id:existing.id}));return Response.json({success:true,alreadyPrepared:true,session:updatedSession,round:existing,runtimeVersion:RUNTIME_VERSION});}
 const commandId=String(body.commandId||`prepare-${Date.now()}`),now=nowIso(),newRound=await retry('create round',()=>base44.asServiceRole.entities.KotcRound.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_number:nextNumber,status:'proposed',proposal_revision:1,active_court_count:activeCourts,bench_count:benchPlaces,generated_by_command_id:commandId,engine_input_hash:String(stableHash(JSON.stringify({results,selected,currentActive,activeCourts}))),engine_output_hash:String(stableHash(JSON.stringify(finalSlots)))}));
 const slotPayload=finalSlots.map((s:any)=>({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_id:newRound.id,round_number:nextNumber,ladder_court_rank:s.ladder_court_rank,team_side:s.team_side,slot_number:s.slot_number,participant_id:s.participant_id,assignment_type:s.assignment_type,assignment_revision:1,replacement_for_participant_id:s.replacement_for_participant_id,destination_from_prior_round:s.destination_from_prior_round})),matchPayload=Array.from({length:activeCourts},(_,i)=>{const rank=i+1,ss=finalSlots.filter((s:any)=>s.ladder_court_rank===rank);return{tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_id:newRound.id,round_number:nextNumber,ladder_court_rank:rank,team_a_participant_ids:ss.filter((s:any)=>s.team_side==='A').sort((a:any,b:any)=>a.slot_number-b.slot_number).map((s:any)=>s.participant_id),team_b_participant_ids:ss.filter((s:any)=>s.team_side==='B').sort((a:any,b:any)=>a.slot_number-b.slot_number).map((s:any)=>s.participant_id),status:'scheduled',revision:0,correction_count:0};}),returning=new Set((participants||[]).filter((p:any)=>['temporarily_unavailable','voluntary_rest'].includes(p.status)&&Number(p.available_again_from_round||0)>0&&nextNumber>=Number(p.available_again_from_round)).map((p:any)=>String(p.id))),participantPayload=projected.map((p:any)=>({id:p.id,rounds_played:p.rounds_played,fairness_benches:p.fairness_benches,consecutive_rounds_played:p.consecutive_rounds_played,consecutive_court1_rounds:p.consecutive_court1_rounds,court1_rounds:p.court1_rounds,...(returning.has(String(p.id))?{status:'present',availability_effective_from_round:null,available_again_from_round:null}:{})})),eventPayload=[...selected.map((id:string)=>({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,participant_id:id,round_id:newRound.id,round_number:nextNumber,event_type:'fairness_bench',effective_from_round:nextNumber,effective_to_round:nextNumber,fairness_credit:true,command_id:commandId,recorded_by_user_id:user.id,occurred_at:now})),...[...returning].map((id:string)=>({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,participant_id:id,round_id:newRound.id,round_number:nextNumber,event_type:'returned_available',effective_from_round:nextNumber,fairness_credit:false,command_id:commandId,recorded_by_user_id:user.id,occurred_at:now}))];
 const newSlots=slotPayload.length?await retry('create slots',()=>base44.asServiceRole.entities.KotcRoundSlot.bulkCreate(slotPayload)):[];const newMatches=matchPayload.length?await retry('create matches',()=>base44.asServiceRole.entities.KotcMatch.bulkCreate(matchPayload)):[];const updatedParticipants=participantPayload.length?await retry('update participants',()=>base44.asServiceRole.entities.KotcSessionParticipant.bulkUpdate(participantPayload)):[];if(eventPayload.length)await retry('create participation events',()=>base44.asServiceRole.entities.KotcParticipationEvent.bulkCreate(eventPayload));if(currentRound.status!=='completed')await retry('complete current round',()=>base44.asServiceRole.entities.KotcRound.update(currentRound.id,{status:'completed',completed_at:now}));const updatedSession=await retry('advance session',()=>base44.asServiceRole.entities.KotcSession.update(session.id,{revision:Number(session.revision||0)+1,last_command_id:commandId,current_round_number:nextNumber,current_round_id:newRound.id}));
 return Response.json({success:true,session:updatedSession,round:newRound,slots:newSlots,matches:newMatches,participants:updatedParticipants,benchParticipantIds:selected,runtimeVersion:RUNTIME_VERSION});
}catch(error){return Response.json({error:(error as any)?.message||'Could not prepare the next KOTC round'},{status:isRateLimit(error)?503:500});}});