import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

const RESOLVED=new Set(['completed','retired','abandoned','not_played']);
function int0(v:any){const n=Number(v);return Number.isInteger(n)&&n>=0?n:null;}
function validScore(body:any,session:any){const a=int0(body.teamAScore),b=int0(body.teamBScore);if(a==null||b==null)return {error:'Scores must be non-negative whole numbers.'};if(session.scoring_mode==='timed'){if(a===b){if(!['A','B'].includes(body.servingSideAtHorn))return {error:'A tied timed match requires the serving side at the horn.'};return {a,b,winner:body.servingSideAtHorn,method:'timed_serving_tiebreak'};}return {a,b,winner:a>b?'A':'B',method:'normal'};}if(a===b)return {error:'First-to scoring requires a winner.'};const target=Number(session.score_target||11),cap=Number(session.score_cap||0),winner=Math.max(a,b),loser=Math.min(a,b);if(winner<target)return {error:`Winner must reach at least ${target}.`};if(cap>0&&winner>cap)return {error:`Score cannot exceed cap of ${cap}.`};if(session.win_by_two&&winner-loser<2&&!(cap>0&&winner===cap))return {error:'Winner must lead by 2 unless the score cap is reached.'};if(!session.win_by_two&&winner>target&&!(cap>0&&winner===cap))return {error:`Match should finish when a team reaches ${target}.`};return {a,b,winner:a>b?'A':'B',method:'normal'};}
async function resolveToken(base44:any,token:string){const row=(await base44.asServiceRole.entities.KotcScorerToken.filter({token,status:'active'}))?.[0];if(!row)throw new Error('Scorer link is invalid or revoked.');if(row.expires_at&&Date.parse(row.expires_at)<Date.now())throw new Error('Scorer link has expired.');return row;}
function timerState(session:any){let t:any={};try{t=session.timer_state_json?JSON.parse(session.timer_state_json):{};}catch{}if(t.running&&t.deadlineAt)t.remainingSeconds=Math.max(0,Math.ceil((Date.parse(t.deadlineAt)-Date.now())/1000));return t;}
function lockActive(match:any){return !!(match?.scoring_lock_owner&&match?.scoring_lock_expires_at&&Date.parse(match.scoring_lock_expires_at)>Date.now());}
function lockSeconds(match:any){return match?.scoring_lock_expires_at?Math.max(0,Math.ceil((Date.parse(match.scoring_lock_expires_at)-Date.now())/1000)):0;}

Deno.serve(async req=>{try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const token=String(body.token||'');if(!token)return Response.json({error:'Token required'},{status:400});
 const scorer=await resolveToken(base44,token);const session=(await base44.asServiceRole.entities.KotcSession.filter({id:scorer.session_id}))?.[0];if(!session)return Response.json({error:'Session not found'},{status:404});
 const round=(await base44.asServiceRole.entities.KotcRound.filter({id:session.current_round_id,session_id:session.id}))?.[0]||null;
 const participants=await base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id});const names=Object.fromEntries((participants||[]).map((p:any)=>[p.id,p.display_name]));
 const requestedAction=String(body.action||'state');
 if(requestedAction==='save'||requestedAction==='correct'){
  if(session.status!=='in_progress'||round?.status!=='started')return Response.json({error:'Scores can only be entered or corrected while this round is still open with the host.'},{status:409});
  const match=(await base44.asServiceRole.entities.KotcMatch.filter({id:String(body.matchId||''),session_id:session.id,round_id:round.id}))?.[0];if(!match)return Response.json({error:'Current-round match not found'},{status:404});
  const correcting=requestedAction==='correct';
  if(correcting&&!RESOLVED.has(match.status))return Response.json({error:'This score has not been saved yet.'},{status:409});
  if(!correcting&&RESOLVED.has(match.status))return Response.json({error:'This result is already saved. Use Undo / Update on the scorer screen.'},{status:409});
  const current=Number(match.revision||0);if(Number(body.expectedRevision)!==current)return Response.json({error:'This score changed since you opened it. Refresh and check the saved result.',conflict:true,currentRevision:current},{status:409});
  const result:any=validScore(body,session);if(result.error)return Response.json({error:result.error},{status:400});const now=new Date().toISOString();
  const original=correcting?(match.original_result_json||JSON.stringify({team_a_score:match.team_a_score,team_b_score:match.team_b_score,winner_side:match.winner_side,result_method:match.result_method,revision:current})):undefined;
  const update:any={team_a_score:result.a,team_b_score:result.b,winner_side:result.winner,result_method:result.method,serving_side_at_horn:result.method==='timed_serving_tiebreak'?body.servingSideAtHorn:undefined,status:'completed',completed_at:match.completed_at||now,revision:current+1,command_id:`scorer-${scorer.id}-${Date.now()}`};
  if(correcting)Object.assign(update,{correction_count:Number(match.correction_count||0)+1,last_corrected_at:now,last_corrected_by_user_id:`scorer-token:${scorer.id}`,last_correction_reason:'Scorer corrected saved score before next round',original_result_json:original});
  const updated=await base44.asServiceRole.entities.KotcMatch.update(match.id,update);
  try{await base44.asServiceRole.entities.KotcScorerToken.update(scorer.id,{last_used_at:now,use_count:Number(scorer.use_count||0)+1});await base44.asServiceRole.entities.AuditLog.create({tenant_id:session.tenant_id,club_id:session.club_id,user_id:`scorer-token:${scorer.id}`,action:correcting?'kotc_score_corrected_by_scorer_link':'kotc_score_completed_by_scorer_link',entity_type:'KotcMatch',entity_id:match.id,scope_type:'KotcSession',scope_id:session.id,before_state:correcting?JSON.stringify({team_a_score:match.team_a_score,team_b_score:match.team_b_score,winner_side:match.winner_side,revision:current}):undefined,after_state:JSON.stringify({team_a_score:result.a,team_b_score:result.b,winner_side:result.winner,revision:current+1}),reason:correcting?'Scorer corrected saved score before host prepared the next round':undefined});}catch{}
  return Response.json({success:true,corrected:correcting,match:updated,message:correcting?'Updated score saved':'Score saved'});
 }
 const matches=round?await base44.asServiceRole.entities.KotcMatch.filter({round_id:round.id,session_id:session.id},'ladder_court_rank',30):[];const assigned=new Set((matches||[]).flatMap((m:any)=>[...(m.team_a_participant_ids||[]),...(m.team_b_participant_ids||[])]));const bench=(participants||[]).filter((p:any)=>['registered','confirmed','present','leaving_early'].includes(p.status)&&!assigned.has(p.id)).map((p:any)=>p.display_name);
 const publicMatches=(matches||[]).map((m:any)=>({id:m.id,court:Number(m.ladder_court_rank),status:m.status,revision:Number(m.revision||0),team_a:(m.team_a_participant_ids||[]).map((id:string)=>names[id]||'Player'),team_b:(m.team_b_participant_ids||[]).map((id:string)=>names[id]||'Player'),team_a_score:m.team_a_score,team_b_score:m.team_b_score,winner_side:m.winner_side}));
 return Response.json({success:true,session:{name:session.name,status:session.status,current_round_number:session.current_round_number,scoring_mode:session.scoring_mode,score_target:session.score_target,win_by_two:session.win_by_two},round:round?{id:round.id,round_number:round.round_number,status:round.status}:null,matches:publicMatches,bench,timer:timerState(session)});
}catch(error){return Response.json({error:error?.message||'Unexpected scorer-link error'},{status:500});}});