import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

const ENGINE_VERSION='2.0.0-rc.1';
const RULES_VERSION='1.2.0';
function activeCourtCount(players:number, limit:number){return Math.min(limit,Math.floor(players/4));}
function stableHash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function pairKey(a:string,b:string){return [a,b].sort().join('|');}
function splitFour(ids:string[],seed:string){const [a,b,c,d]=ids;const opts=[[[a,b],[c,d]],[[a,c],[b,d]],[[a,d],[b,c]]];return opts.map((x:any)=>({teamA:x[0],teamB:x[1],key:`${x[0].join(',')}|${x[1].join(',')}`})).sort((x:any,y:any)=>stableHash(`${seed}|${x.key}`)-stableHash(`${seed}|${y.key}`)||x.key.localeCompare(y.key))[0];}

Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req); const user=await base44.auth.me(); if(!user)return Response.json({error:'Unauthorized'},{status:401});
 if(user.role!=='admin')return Response.json({error:'Platform admin access required to create a KOTC V2 session.'},{status:403});
 const body=await req.json().catch(()=>({})); const tournamentId=String(body.tournamentId||''); if(!tournamentId)return Response.json({error:'tournamentId required'},{status:400});
 const tournament=(await base44.asServiceRole.entities.Tournament.filter({id:tournamentId}))?.[0]; if(!tournament)return Response.json({error:'Tournament not found'},{status:404});
 const existing=(await base44.asServiceRole.entities.KotcSession.filter({tournament_id:tournamentId})).filter((s:any)=>!['cancelled','abandoned'].includes(s.status)); if(existing.length)return Response.json({error:'A KOTC V2 session already exists for this tournament.',session:existing[0]},{status:409});
 const playerIds=[...(body.playerOrder?.length?body.playerOrder:(tournament.player_ids||[]))].map(String); if(playerIds.length<4)return Response.json({error:'At least 4 players are required.'},{status:400}); if(new Set(playerIds).size!==playerIds.length)return Response.json({error:'Player order contains duplicates.'},{status:400});
 const venueLimit=Math.max(1,Math.min(4,Number(body.venueCourtLimit||4))); const courts=activeCourtCount(playerIds.length,venueLimit); if(courts<1)return Response.json({error:'Not enough players for a complete doubles court.'},{status:400});
 const benchCount=playerIds.length-courts*4; const requestedBench=(body.round1BenchIds||[]).map(String); if(requestedBench.length!==benchCount||requestedBench.some((id:string)=>!playerIds.includes(id))||new Set(requestedBench).size!==requestedBench.length)return Response.json({error:`Round 1 requires exactly ${benchCount} valid bench player${benchCount===1?'':'s'}.`},{status:400});
 const playerRecords=await base44.asServiceRole.entities.Player.filter({id:{$in:playerIds}}); const byId=Object.fromEntries((playerRecords||[]).map((p:any)=>[p.id,p]));
 const scoringMode=body.scoringMode==='first_to'?'first_to':'timed'; const seed=String(body.randomSeed||`${tournamentId}|${Date.now()}`); const now=new Date().toISOString();
 const session=await base44.asServiceRole.entities.KotcSession.create({tenant_id:tournament.tenant_id,club_id:tournament.host_club_id||user.active_club_id||'',tournament_id:tournamentId,name:tournament.name||'King of the Court',status:'ready',venue_id:tournament.venue_id||'',planned_duration_minutes:Number(body.plannedDurationMinutes||90),venue_court_limit:venueLimit,available_court_limit:venueLimit,max_registrations:playerIds.length,planned_rounds:Number(body.plannedRounds||9),partnership_mode:'rotating_doubles',scoring_mode:scoringMode,score_target:scoringMode==='first_to'?Number(body.scoreTarget||11):undefined,win_by_two:Boolean(body.winByTwo),score_cap:body.scoreCap?Number(body.scoreCap):undefined,play_minutes:Number(body.playMinutes||8),changeover_minutes:Number(body.changeoverMinutes||2),seeding_mode:'manual',random_seed:seed,fairness_policy_json:JSON.stringify({version:RULES_VERSION}),leaderboard_policy_json:JSON.stringify({version:RULES_VERSION}),court1_champions_enabled:true,dupr_export_enabled:false,engine_version:ENGINE_VERSION,rules_version:RULES_VERSION,revision:0,current_round_number:1});
 const participants=[]; for(let i=0;i<playerIds.length;i++){const id=playerIds[i],p=byId[id];participants.push(await base44.asServiceRole.entities.KotcSessionParticipant.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,player_id:id,display_name:p?.full_name||p?.name||id,source_type:'member',status:'present',rating_snapshot:Number(p?.skill_rating||3),seed_rank:i+1,rounds_played:0,fairness_benches:0,voluntary_rest_rounds:0,consecutive_rounds_played:0,consecutive_court1_rounds:0,court1_rounds:0,recent_fairness_burden:0,joined_at_round:1}));}
 const benchSet=new Set(requestedBench); const courtIds=playerIds.filter((id:string)=>!benchSet.has(id)); const round=await base44.asServiceRole.entities.KotcRound.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_number:1,status:'proposed',proposal_revision:1,active_court_count:courts,bench_count:benchCount,generated_by_command_id:'create-session',engine_input_hash:String(stableHash(`${seed}|${playerIds.join('|')}|${requestedBench.join('|')}`))});
 const participantByPlayer=Object.fromEntries(participants.map((p:any)=>[p.player_id,p])); const createdSlots=[]; const createdMatches=[];
 for(let c=0;c<courts;c++){const four=courtIds.slice(c*4,c*4+4);const split=splitFour(four,`${seed}|r1|c${c+1}`);const teams=[['A',split.teamA],['B',split.teamB]] as any;for(const [side,ids] of teams){for(let s=0;s<2;s++){createdSlots.push(await base44.asServiceRole.entities.KotcRoundSlot.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_id:round.id,round_number:1,ladder_court_rank:c+1,team_side:side,slot_number:s+1,participant_id:participantByPlayer[ids[s]].id,assignment_type:'initial_seed',assignment_revision:1}));}}createdMatches.push(await base44.asServiceRole.entities.KotcMatch.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_id:round.id,round_number:1,ladder_court_rank:c+1,team_a_participant_ids:split.teamA.map((id:string)=>participantByPlayer[id].id),team_b_participant_ids:split.teamB.map((id:string)=>participantByPlayer[id].id),status:'scheduled',revision:0,correction_count:0}));}
 for(const id of requestedBench){await base44.asServiceRole.entities.KotcParticipationEvent.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,participant_id:participantByPlayer[id].id,round_id:round.id,round_number:1,event_type:'fairness_bench',effective_from_round:1,effective_to_round:1,fairness_credit:true,recorded_by_user_id:user.id,occurred_at:now});}
 await base44.asServiceRole.entities.KotcSessionAccess.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,user_id:user.id,role:'session_host',status:'active',starts_at:now,granted_by_user_id:user.id});
 const lease=await base44.asServiceRole.entities.KotcHostLease.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,holder_user_id:user.id,lease_revision:1,status:'active',acquired_at:now,last_heartbeat_at:now});
 await base44.asServiceRole.entities.KotcSession.update(session.id,{current_round_id:round.id}); await base44.asServiceRole.entities.Tournament.update(tournament.id,{status:'In Progress'});
 return Response.json({success:true,session:{...session,current_round_id:round.id},round,participants,slots:createdSlots,matches:createdMatches,lease});
}catch(error){return Response.json({error:error?.message||'Unexpected KOTC V2 session creation error'},{status:500});}});