import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

const ENGINE_VERSION='2.0.0-rc.1';
const RULES_VERSION='1.2.0';
function activeCourtCount(players:number, limit:number){return Math.min(limit,Math.floor(players/4));}
function stableHash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
function isRateLimit(error:any){return /rate limit|too many requests|\b429\b/i.test(String(error?.message||error||''));}
async function retry<T>(label:string,fn:()=>Promise<T>,attempts=5){let last:any;for(let i=0;i<attempts;i++){try{return await fn();}catch(error){last=error;if(!isRateLimit(error)||i===attempts-1)throw error;const delay=Math.min(2200,300*Math.pow(2,i))+Math.floor(Math.random()*120);console.warn('KOTC create rate limit — retrying',{label,attempt:i+1,delay});await sleep(delay);}}throw last;}
function splitFour(ids:string[],seed:string){const [a,b,c,d]=ids;const opts=[[[a,b],[c,d]],[[a,c],[b,d]],[[a,d],[b,c]]];return opts.map((x:any)=>({teamA:x[0],teamB:x[1],key:`${x[0].join(',')}|${x[1].join(',')}`})).sort((x:any,y:any)=>stableHash(`${seed}|${x.key}`)-stableHash(`${seed}|${y.key}`)||x.key.localeCompare(y.key))[0];}
function normalisePhases(input:any[],planned:number){const src=Array.isArray(input)&&input.length?input:[{start_round:1,end_round:planned,mode:'rotating'}];const phases=src.map((p:any,i:number)=>({phase_order:i+1,start_round:Number(p.start_round),end_round:p.end_round==null?planned:Number(p.end_round),mode:p.mode==='fixed'?'fixed':'rotating',fixed_pair_source:p.mode==='fixed'&&['preselected','pair_at_transition','host_select_at_transition'].includes(p.fixed_pair_source)?p.fixed_pair_source:(p.mode==='fixed'?'preselected':undefined)})).sort((a:any,b:any)=>a.start_round-b.start_round);let next=1;for(const p of phases){if(!Number.isInteger(p.start_round)||!Number.isInteger(p.end_round)||p.start_round!==next||p.end_round<p.start_round||p.end_round>planned)throw new Error('Partnership phases must cover all planned rounds with no gaps or overlaps.');next=p.end_round+1;}if(next!==planned+1)throw new Error('Partnership phases must cover all planned rounds.');return phases.map((p:any,i:number)=>({...p,phase_order:i+1}));}
function validatePairInputs(playerIds:string[],pairs:any[],phaseOrder:number,complete=true){const chosen=(pairs||[]).filter((p:any)=>Number(p.phaseOrder||p.phase_order||1)===phaseOrder);const allowed=new Set(playerIds),used=new Set<string>();for(const p of chosen){const a=String(p.player1Id||p.player1_id||p.participant1_id||''),b=String(p.player2Id||p.player2_id||p.participant2_id||'');if(!a||!b||a===b||!allowed.has(a)||!allowed.has(b)||used.has(a)||used.has(b))throw new Error(`Invalid or duplicate fixed pair in phase ${phaseOrder}.`);used.add(a);used.add(b);}if(complete&&used.size!==playerIds.length)throw new Error(`Fixed phase ${phaseOrder} requires every player to belong to exactly one pair.`);return chosen;}

Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req); const user=await base44.auth.me(); if(!user)return Response.json({error:'Unauthorized'},{status:401});
 if(user.role!=='admin')return Response.json({error:'Platform admin access required to create a KOTC V2 session.'},{status:403});
 const body=await req.json().catch(()=>({})); const tournamentId=String(body.tournamentId||''); if(!tournamentId)return Response.json({error:'tournamentId required'},{status:400});
 const tournament=(await retry('tournament read',()=>base44.asServiceRole.entities.Tournament.filter({id:tournamentId})))?.[0]; if(!tournament)return Response.json({error:'Tournament not found'},{status:404});
 const existing=(await retry('existing session read',()=>base44.asServiceRole.entities.KotcSession.filter({tournament_id:tournamentId}))).filter((s:any)=>!['cancelled','abandoned'].includes(s.status)); if(existing.length)return Response.json({error:'A KOTC V2 session already exists for this tournament.',session:existing[0]},{status:409});
 const guestRoster=Array.isArray(tournament.kotc_guest_roster)?tournament.kotc_guest_roster:[]; const guestById=Object.fromEntries(guestRoster.map((g:any)=>[String(g.guest_id),g]));
 const playerIds=[...(body.playerOrder?.length?body.playerOrder:(tournament.kotc_player_order?.length?tournament.kotc_player_order:[...(tournament.player_ids||[]),...guestRoster.map((g:any)=>g.guest_id)]))].map(String); if(playerIds.length<4)return Response.json({error:'At least 4 players are required.'},{status:400}); if(new Set(playerIds).size!==playerIds.length)return Response.json({error:'Player order contains duplicates.'},{status:400});
 const plannedRounds=Math.max(1,Number(body.plannedRounds||9)); const phases=normalisePhases(body.partnershipPhases||[],plannedRounds); const firstPhase=phases.find((p:any)=>p.start_round===1); const partnershipMode=phases.length>1?'phased_doubles':firstPhase?.mode==='fixed'?'fixed_doubles':'rotating_doubles'; const requestedSeeding=String(body.seedingMode||'roster_order'); const seedingMode=['roster_order','internal_rating','dupr','manual','previous_kotc','random_seeded'].includes(requestedSeeding)?requestedSeeding:'roster_order';
 const venueLimit=Math.max(1,Math.min(20,Number(body.venueCourtLimit||4))); const courts=activeCourtCount(playerIds.length,venueLimit); if(courts<1)return Response.json({error:'Not enough players for a complete doubles court.'},{status:400});
 const memberIds=playerIds.filter((id:string)=>!guestById[id]); const playerRecords=memberIds.length?await retry('player roster read',()=>base44.asServiceRole.entities.Player.filter({id:{$in:memberIds}})):[]; const byId=Object.fromEntries((playerRecords||[]).map((p:any)=>[p.id,p]));
 const missingMembers=memberIds.filter((id:string)=>!byId[id]); if(missingMembers.length)return Response.json({error:`${missingMembers.length} roster player(s) could not be resolved. Refresh the roster and try again.`},{status:409});
 const scoringMode=body.scoringMode==='first_to'?'first_to':'timed'; const seed=String(body.randomSeed||`${tournamentId}|${Date.now()}`); const now=new Date().toISOString(); const clubId=tournament.host_club_id||user.active_club_id||'';
 // Participant identity is not the same thing as membership. Snapshot the player's
 // current club relationship for this event so guests, waiting-list and booking-only
 // players can compete fully without ever leaking into the member aggregate leaderboard.
 const personIds=[...new Set((playerRecords||[]).map((p:any)=>p.person_id).filter(Boolean))];
 const relationshipRows=personIds.length&&clubId?await retry('club relationship read',()=>base44.asServiceRole.entities.ClubRelationship.filter({tenant_id:tournament.tenant_id,club_id:clubId,person_id:{$in:personIds},status:'active'})):[];
 const relationshipByPerson=Object.fromEntries((relationshipRows||[]).map((r:any)=>[String(r.person_id),r]));
 const participantTypeFor=(p:any)=>{const rel=String(relationshipByPerson[String(p?.person_id||'')]?.relationship_type||p?.relationship_type||'guest');if(rel==='member')return 'member';if(rel==='waiting_list')return 'waiting_list';if(rel==='booking_only')return 'booking_only';if(rel==='guest')return 'guest';return 'guest';};
 const venueId=body.venueId&&body.venueId!=='other'?String(body.venueId):''; const customLocation=body.venueId==='other'?String(body.customLocation||'').trim():String(body.customLocation||'').trim(); if(body.venueId==='other'&&!customLocation)return Response.json({error:'Enter the custom session location.'},{status:400});
 const sessionName=String(body.sessionName||tournament.name||'King of the Court').trim();
 const benchPriority=['latest_registration','fairness_engine','manual'].includes(body.round1BenchPriority)?body.round1BenchPriority:'manual';
 const testMode=Boolean(body.testMode);
 const session=await retry('session create',()=>base44.asServiceRole.entities.KotcSession.create({tenant_id:tournament.tenant_id,club_id:clubId,tournament_id:tournamentId,name:sessionName,status:'ready',venue_id:venueId,custom_location:customLocation||undefined,scheduled_start:body.scheduledStart||undefined,planned_duration_minutes:Number(body.plannedDurationMinutes||90),venue_court_limit:venueLimit,available_court_limit:venueLimit,max_registrations:playerIds.length,planned_rounds:plannedRounds,partnership_mode:partnershipMode,round1_bench_priority:benchPriority,scoring_mode:scoringMode,score_target:scoringMode==='first_to'?Number(body.scoreTarget||11):undefined,win_by_two:Boolean(body.winByTwo),score_cap:body.scoreCap?Number(body.scoreCap):undefined,play_minutes:Number(body.playMinutes||8),changeover_minutes:Number(body.changeoverMinutes||2),seeding_mode:seedingMode,random_seed:seed,fairness_policy_json:JSON.stringify({version:RULES_VERSION,round1BenchPriority:benchPriority,fixedPairBenchFairness:'individual_history_pair_constrained'}),leaderboard_policy_json:JSON.stringify({version:RULES_VERSION}),court1_champions_enabled:true,dupr_export_enabled:false,demo_mode:testMode,exclude_from_aggregates:testMode,engine_version:ENGINE_VERSION,rules_version:RULES_VERSION,revision:0,current_round_number:1}));
 const phasePayload=phases.map((p:any)=>({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,...p,status:p.start_round===1?'active':'planned',created_by_user_id:user.id}));const phaseRecords:any[]=phasePayload.length?await retry('partnership phases bulk create',()=>base44.asServiceRole.entities.KotcPartnershipPhase.bulkCreate(phasePayload)):[];
 const registrationOrder=(Array.isArray(body.registrationOrder)&&body.registrationOrder.length?body.registrationOrder:(tournament.player_ids||playerIds)).map(String); const regRank=Object.fromEntries(registrationOrder.map((id:string,i:number)=>[id,i+1]));
 const participantPayload=playerIds.map((id:string,i:number)=>{const guest=guestById[id],p=byId[id],participantType=guest?'guest':participantTypeFor(p);return{tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,player_id:guest?undefined:id,display_name:guest?.display_name||p?.full_name||p?.name||id,participant_type:participantType,source_type:guest?'guest':participantType==='member'?'member':'imported',registration_source:guest?'manual_guest':(tournament.kotc_spond_event_id?'spond':'tournament'),registration_order:Number(regRank[id]||i+1),status:'present',rating_snapshot:p?.skill_rating!=null?Number(p.skill_rating):undefined,dupr_rating_snapshot:p?.dupr_rating!=null?Number(p.dupr_rating):undefined,seed_rank:i+1,rounds_played:0,fairness_benches:0,voluntary_rest_rounds:0,consecutive_rounds_played:0,consecutive_court1_rounds:0,court1_rounds:0,recent_fairness_burden:0,joined_at_round:1};});
 const participants:any[]=participantPayload.length?await retry('participants bulk create',()=>base44.asServiceRole.entities.KotcSessionParticipant.bulkCreate(participantPayload)):[]; const participantByPlayer:any={};for(let i=0;i<playerIds.length;i++)participantByPlayer[playerIds[i]]=participants[i];
 const rosterIdByParticipantId=Object.fromEntries(Object.entries(participantByPlayer).map(([rosterId,p]:any)=>[p.id,rosterId]));
 const fixedPairRecords:any[]=[];for(const p of phases.filter((x:any)=>x.mode==='fixed')){const requiresNow=p.start_round===1||p.fixed_pair_source==='preselected';const selected=validatePairInputs(playerIds,body.fixedPairs||[],p.phase_order,requiresNow);const phaseRecord=phaseRecords.find((x:any)=>Number(x.phase_order)===Number(p.phase_order));for(let i=0;i<selected.length;i++){const pair=selected[i],a=participantByPlayer[String(pair.player1Id||pair.player1_id||pair.participant1_id)],b=participantByPlayer[String(pair.player2Id||pair.player2_id||pair.participant2_id)];fixedPairRecords.push(await base44.asServiceRole.entities.KotcFixedPair.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,phase_id:phaseRecord.id,phase_order:p.phase_order,pair_name:String(pair.pairName||`${a.display_name} / ${b.display_name}`),participant1_id:a.id,participant2_id:b.id,seed_rank:i+1,pair_source:p.fixed_pair_source==='host_select_at_transition'?'host_selected':p.fixed_pair_source,status:'active'}));}}
 let requestedBench=(body.round1BenchIds||[]).map(String); const individualBenchCount=playerIds.length-courts*4;
 if(firstPhase?.mode==='fixed'){
   if(playerIds.length%2!==0)return Response.json({error:'A fixed Round 1 requires an even number of available players.'},{status:400});
   const phasePairRecords=fixedPairRecords.filter((p:any)=>Number(p.phase_order)===Number(firstPhase.phase_order)); const pairBenchCount=(playerIds.length/2)-courts*2;
   if(pairBenchCount<0)return Response.json({error:'Invalid fixed-pair court arithmetic.'},{status:400});
   if(requestedBench.length){const req=new Set(requestedBench.map((id:string)=>participantByPlayer[id]?.id||id));const whole=phasePairRecords.filter((p:any)=>req.has(p.participant1_id)&&req.has(p.participant2_id));if(whole.length!==pairBenchCount||req.size!==pairBenchCount*2)return Response.json({error:`Round 1 fixed play requires exactly ${pairBenchCount} complete bench pair${pairBenchCount===1?'':'s'}.`},{status:400});requestedBench=whole.flatMap((p:any)=>[rosterIdByParticipantId[p.participant1_id],rosterIdByParticipantId[p.participant2_id]]).filter(Boolean);}else if(pairBenchCount>0){const sorted=[...phasePairRecords].sort((a:any,b:any)=>Number(b.seed_rank)-Number(a.seed_rank));requestedBench=sorted.slice(0,pairBenchCount).flatMap((p:any)=>[rosterIdByParticipantId[p.participant1_id],rosterIdByParticipantId[p.participant2_id]]).filter(Boolean);}
 } else {
   if(benchPriority==='latest_registration'&&!requestedBench.length)requestedBench=[...playerIds].sort((a,b)=>Number(regRank[b]||0)-Number(regRank[a]||0)).slice(0,individualBenchCount);
   if(benchPriority==='fairness_engine'&&!requestedBench.length)requestedBench=[...playerIds].sort((a,b)=>stableHash(`${seed}|r1bench|${a}`)-stableHash(`${seed}|r1bench|${b}`)).slice(0,individualBenchCount);
   if(requestedBench.length!==individualBenchCount||requestedBench.some((id:string)=>!playerIds.includes(id))||new Set(requestedBench).size!==requestedBench.length)return Response.json({error:`Round 1 requires exactly ${individualBenchCount} valid bench player${individualBenchCount===1?'':'s'}.`},{status:400});
 }
 const benchSet=new Set(requestedBench); const courtIds=playerIds.filter((id:string)=>!benchSet.has(id)); const round=await retry('round1 create',()=>base44.asServiceRole.entities.KotcRound.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_number:1,status:'proposed',proposal_revision:1,active_court_count:courts,bench_count:requestedBench.length,generated_by_command_id:'create-session',engine_input_hash:String(stableHash(`${seed}|${playerIds.join('|')}|${requestedBench.join('|')}|${partnershipMode}`))}));
 let roundCourts:any[]=[];
 if(firstPhase?.mode==='fixed'){
   const phasePairs=fixedPairRecords.filter((p:any)=>Number(p.phase_order)===Number(firstPhase.phase_order));const benchParticipantIds=new Set(requestedBench.map((id:string)=>participantByPlayer[id].id));const activePairs=phasePairs.filter((p:any)=>!benchParticipantIds.has(p.participant1_id)&&!benchParticipantIds.has(p.participant2_id));for(let c=0;c<courts;c++){const pa=activePairs[c*2],pb=activePairs[c*2+1];roundCourts.push({courtRank:c+1,teamA:[pa.participant1_id,pa.participant2_id],teamB:[pb.participant1_id,pb.participant2_id]});}
 }else{for(let c=0;c<courts;c++){const four=courtIds.slice(c*4,c*4+4);const split=splitFour(four,`${seed}|r1|c${c+1}`);roundCourts.push({courtRank:c+1,teamA:split.teamA.map((id:string)=>participantByPlayer[id].id),teamB:split.teamB.map((id:string)=>participantByPlayer[id].id)});}}
 const slotPayload:any[]=[];const matchPayload:any[]=[];for(const rc of roundCourts){for(const [side,ids] of [['A',rc.teamA],['B',rc.teamB]] as any){for(let s=0;s<2;s++)slotPayload.push({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_id:round.id,round_number:1,ladder_court_rank:rc.courtRank,team_side:side,slot_number:s+1,participant_id:ids[s],assignment_type:'initial_seed',assignment_revision:1,is_locked:firstPhase?.mode==='fixed'});}matchPayload.push({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,round_id:round.id,round_number:1,ladder_court_rank:rc.courtRank,team_a_participant_ids:rc.teamA,team_b_participant_ids:rc.teamB,status:'scheduled',revision:0,correction_count:0});}
 const createdSlots:any[]=slotPayload.length?await retry('round1 slots bulk create',()=>base44.asServiceRole.entities.KotcRoundSlot.bulkCreate(slotPayload)):[];const createdMatches:any[]=matchPayload.length?await retry('round1 matches bulk create',()=>base44.asServiceRole.entities.KotcMatch.bulkCreate(matchPayload)):[];
 const benchEventPayload=requestedBench.map((playerId:string)=>{const participant=participantByPlayer[playerId];return{tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,participant_id:participant.id,round_id:round.id,round_number:1,event_type:'fairness_bench',effective_from_round:1,effective_to_round:1,fairness_credit:true,reason:firstPhase?.mode==='fixed'?'fixed_pair_fairness_bench':benchPriority,recorded_by_user_id:user.id,occurred_at:now};});if(benchEventPayload.length)await retry('round1 bench events',()=>base44.asServiceRole.entities.KotcParticipationEvent.bulkCreate(benchEventPayload));
 await retry('host access create',()=>base44.asServiceRole.entities.KotcSessionAccess.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,user_id:user.id,role:'session_host',status:'active',starts_at:now,granted_by_user_id:user.id}));
 const lease=await retry('host lease create',()=>base44.asServiceRole.entities.KotcHostLease.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,holder_user_id:user.id,lease_revision:1,status:'active',acquired_at:now,last_heartbeat_at:now}));
 const updatedSession=await retry('session round pointer update',()=>base44.asServiceRole.entities.KotcSession.update(session.id,{current_round_id:round.id})); await retry('tournament session update',()=>base44.asServiceRole.entities.Tournament.update(tournament.id,{status:'In Progress',venue_id:venueId||tournament.venue_id,location:customLocation||tournament.location,name:sessionName}));
 return Response.json({success:true,session:updatedSession,round,participants,slots:createdSlots,matches:createdMatches,lease,partnershipPhases:phaseRecords,fixedPairs:fixedPairRecords});
}catch(error){return Response.json({error:error?.message||'Unexpected KOTC V2 session creation error'},{status:500});}});