function dateMs(value:any){if(!value)return null;const n=Date.parse(String(value));return Number.isFinite(n)?n:null;}
function isWindowActive(row:any,now=Date.now()){if(!row||!['active','grace'].includes(String(row.status||'')))return false;const start=dateMs(row.starts_at),end=dateMs(row.ends_at),grace=dateMs(row.grace_ends_at);if(start!==null&&start>now)return false;if(row.status==='grace')return grace===null||grace>=now;if(end!==null&&end<now)return false;return true;}
function contextMatches(row:any,clubId:string|null,eventId:string|null){if(row.club_id&&String(row.club_id)!==String(clubId||''))return false;if(row.entitlement_type==='one_event'&&String(row.one_event_id||'')!==String(eventId||''))return false;return true;}
function includesCapability(source:string,target:string,caps:Map<string,any>,seen=new Set<string>()){if(source===target)return true;if(seen.has(source))return false;seen.add(source);const cap=caps.get(source);for(const dep of cap?.depends_on_keys||[]){if(dep===target||includesCapability(String(dep),target,caps,seen))return true;}return false;}
export async function tenantCapabilityDecision(base44:any,user:any,capabilityKey:string,opts:any={}){
 const tenantId=String(opts.tenantId||user?.active_tenant_id||''),clubId=String(opts.clubId||user?.active_club_id||'')||null,eventId=String(opts.eventId||'')||null;
 if(!user)return {allowed:false,reason:'unauthenticated'};if(user.role==='admin')return {allowed:true,reason:'platform_admin'};if(!tenantId||tenantId!==String(user.active_tenant_id||''))return {allowed:false,reason:'tenant_context_mismatch'};if(clubId&&clubId!==String(user.active_club_id||''))return {allowed:false,reason:'club_context_mismatch'};
 const policies=await base44.asServiceRole.entities.TenantAccessPolicy.filter({tenant_id:tenantId}),policy=policies?.[0]||null,mode=policy?.enforcement_mode||'legacy_full_access';if(mode==='legacy_full_access')return {allowed:true,reason:'legacy_full_access',policy};
 const capRows=await base44.asServiceRole.entities.RallyHubCapability.list('sort_order',500),caps=new Map((capRows||[]).map((r:any)=>[String(r.key),r]));const rows=await base44.asServiceRole.entities.TenantEntitlement.filter({tenant_id:tenantId});const active=(rows||[]).filter((r:any)=>contextMatches(r,clubId,eventId)&&isWindowActive(r)&&includesCapability(String(r.capability_key),capabilityKey,caps));if(active.length)return {allowed:true,reason:'active_entitlement',matchedEntitlement:active[0],policy};return {allowed:false,reason:'capability_not_entitled',policy};
}
