import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

const SPREADSHEET_ID='1BK8Y3qBzaMWdZOHQpORI2vXvXr0kIJVBur3aNH5WNY0';
const FORM_RANGE="'Form Responses 1'!A1:AT1000";
const MASTER_RANGE="'2026-27 Member Master'!A7:S1000";
const TENANT_ID='6a9b7790bc4a8d299938bda9';
const CLUB_ID='6a9b779684daba85b3ffdeb5';
const SOURCE='google_membership_2026_27';
const SEASON='2026-27';

function clean(v:any){return String(v??'').trim();}
function email(v:any){return clean(v).toLowerCase();}
function digits(v:any){return clean(v).replace(/\D/g,'');}
function phone(v:any){const d=digits(v);if(!d)return'';if(d.startsWith('353')&&d.length>=11)return '0'+d.slice(3);return d;}
function nameKey(v:any){return clean(v).toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9]+/g,' ').trim();}
function dateIso(v:any){const s=clean(v);if(!s)return'';const m=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);if(!m)return'';const y=Number(m[3]),mo=Number(m[2]),d=Number(m[1]);if(y<1900||y>2100||mo<1||mo>12||d<1||d>31)return'';return String(y).padStart(4,'0')+'-'+String(mo).padStart(2,'0')+'-'+String(d).padStart(2,'0');}
function split(v:any){return clean(v).split(/[,;\n]/).map((x:string)=>x.trim()).filter(Boolean);}
function first(...v:any[]){return v.find(x=>clean(x))??'';}
function uniq(a:any[]){return [...new Set(a.filter(Boolean))];}
function hmap(row:any[]){const o:any={};row.forEach((v,i)=>{const k=clean(v);if(!o[k])o[k]=[];o[k].push(i);});return o;}
function idx(h:any,k:string,last=false){const a=h[k]||[];return a.length?(last?a[a.length-1]:a[0]):-1;}
function idxs(h:any,k:string){return h[k]||[];}
function val(r:any[],i:number){return i>=0?r[i]:'';}
function firstFromIndices(r:any[],indices:number[]){for(const i of indices||[]){const v=clean(val(r,i));if(v)return v;}return'';}
function firstEmailFromIndices(r:any[],indices:number[]){for(const i of indices||[]){const v=email(val(r,i));if(v&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))return v;}return'';}

async function readSheet(token:string,range:string){
 const url='https://sheets.googleapis.com/v4/spreadsheets/'+SPREADSHEET_ID+'/values/'+encodeURIComponent(range)+'?majorDimension=ROWS&valueRenderOption=FORMATTED_VALUE';
 const res=await fetch(url,{headers:{Authorization:'Bearer '+token}});
 const p=await res.json().catch(()=>({}));
 if(!res.ok)throw new Error(p?.error?.message||('Google Sheets read failed ('+res.status+')'));
 return p.values||[];
}

function parseMaster(rows:any[][]){
 if(!rows.length)return[];const h=hmap(rows[0]);
 const I={name:idx(h,'MEMBER NAME'),email:idx(h,'PRIMARY EMAIL'),mobile:idx(h,'MOBILE NUMBER'),dob:idx(h,'DATE OF BIRTH'),status:idx(h,'2026–27 STATUS'),mid:idx(h,'CURRENT CP26 ID'),mtype:idx(h,'MEMBERSHIP TYPE'),pstatus:idx(h,'PAYMENT STATUS'),pdate:idx(h,'PAYMENT DATE'),amount:idx(h,'AMOUNT'),alts:idx(h,'ALTERNATE EMAILS'),source:idx(h,'SOURCE ROWS'),ename:idx(h,'EMERGENCY CONTACT / RELATIONSHIP'),emobile:idx(h,'EMERGENCY MOBILE')};
 return rows.slice(1).map((r,n)=>({source:'master',row:8+n,fullName:clean(val(r,I.name)),primaryEmail:email(val(r,I.email)),mobile:phone(val(r,I.mobile)),dob:dateIso(val(r,I.dob)),status:clean(val(r,I.status)).toUpperCase(),membershipId:clean(val(r,I.mid)),membershipType:clean(val(r,I.mtype)),paymentStatus:clean(val(r,I.pstatus)).toUpperCase(),paymentDate:dateIso(val(r,I.pdate)),amount:Number(String(val(r,I.amount)).replace(/[^0-9.]/g,''))||null,alternateEmails:split(val(r,I.alts)).map(email),sourceRows:split(val(r,I.source)),emergencyName:clean(val(r,I.ename)),emergencyMobile:phone(val(r,I.emobile))})).filter(x=>x.fullName&&x.status==='PAID / ACTIVE');
}

function parseForm(rows:any[][]){
 if(!rows.length)return[];const h=hmap(rows[0]);
 const I={names:idxs(h,'Your Full Name in First name, Surname Order'),address:idx(h,'Your full postal address'),eir:idx(h,'Your Eircode '),emails:idxs(h,'Email Address'),email1:idx(h,'Your Email Address'),email0:idx(h,'Email address'),mobile:idx(h,'Your Mobile phone number'),dob:idx(h,'Date of Birth, Please ensure your DOB is correct!'),eraw:idx(h,'Name and Contact details of relative or friend, in case of emergency? Please state Relationship?'),mid:idx(h,'Membership ID'),mtype:idx(h,'Membership Type'),amount:idx(h,'Payment Amount'),pstatus:idx(h,'Payment Status'),pdate:idx(h,'Payment Date'),mstatus:idx(h,'Membership Status'),mname:idx(h,'Member Name'),memail:idx(h,'Member Email')};
 return rows.slice(1).map((r,n)=>({source:'form',row:2+n,fullName:clean(first(val(r,I.mname),firstFromIndices(r,[...(I.names||[])].reverse()))),primaryEmail:email(first((/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email(val(r,I.memail)))?val(r,I.memail):''),firstEmailFromIndices(r,[...(I.emails||[])].reverse()),val(r,I.email1),val(r,I.email0))),mobile:phone(val(r,I.mobile)),dob:dateIso(val(r,I.dob)),address:clean(val(r,I.address)),eircode:clean(val(r,I.eir)),emergencyRaw:clean(val(r,I.eraw)),membershipId:clean(val(r,I.mid)),membershipType:clean(val(r,I.mtype)),amount:Number(String(val(r,I.amount)).replace(/[^0-9.]/g,''))||null,paymentStatus:clean(val(r,I.pstatus)).toUpperCase(),paymentDate:dateIso(val(r,I.pdate)),membershipStatus:clean(val(r,I.mstatus)).toUpperCase()})).filter(x=>x.fullName&&x.paymentStatus==='PAID'&&x.membershipStatus==='ACTIVE');
}

function combine(master:any[],forms:any[]){
 // The 2026-27 Member Master is the membership authority. Form Responses are
 // enrichment only (address/contact/emergency details) and must never create an
 // additional paid member that is not present in the master.
 const byId=new Map(forms.filter(x=>x.membershipId).map(x=>[x.membershipId,x]));const byEmail=new Map(forms.filter(x=>x.primaryEmail).map(x=>[x.primaryEmail,x]));const byName=new Map(forms.map(x=>[nameKey(x.fullName),x]));const out:any[]=[];
 for(const m of master){const f=byId.get(m.membershipId)||byEmail.get(m.primaryEmail)||byName.get(nameKey(m.fullName));out.push({...f,...m,fullName:first(m.fullName,f?.fullName),primaryEmail:email(first(m.primaryEmail,f?.primaryEmail)),mobile:phone(first(m.mobile,f?.mobile)),dob:first(m.dob,f?.dob),address:first(f?.address,''),eircode:first(f?.eircode,''),emergencyRaw:first(f?.emergencyRaw,''),emergencyName:first(m.emergencyName,''),emergencyMobile:phone(first(m.emergencyMobile,'')),membershipId:first(m.membershipId,f?.membershipId),membershipType:first(m.membershipType,f?.membershipType),paymentStatus:first(m.paymentStatus,f?.paymentStatus),paymentDate:first(m.paymentDate,f?.paymentDate),amount:m.amount??f?.amount??null,sourceRows:uniq([...(m.sourceRows||[]),...(f?[String(f.row)]:[])]),source:f?'master+form':'master'});}
 const seen=new Set<string>();return out.filter(r=>{const k=r.membershipId?('id:'+r.membershipId):r.primaryEmail?('e:'+r.primaryEmail):r.mobile?('p:'+r.mobile):('n:'+nameKey(r.fullName));if(seen.has(k))return false;seen.add(k);return true;});
}

Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user)return Response.json({error:'Unauthorized'},{status:401});if(user.role!=='admin')return Response.json({error:'Administrator access required'},{status:403});
 const body=await req.json().catch(()=>({}));const mode=String(body.mode||'sync');if(!['preview','sync'].includes(mode))return Response.json({error:'Invalid mode'},{status:400});
 let token='';try{const c=await base44.asServiceRole.connectors.getConnection('googlesheets');token=String(c?.accessToken||'');}catch{}
 if(!token)return Response.json({error:'Google Sheets is not connected to RallyHub yet.',code:'GOOGLE_SHEETS_NOT_CONNECTED'},{status:409});
 const [fr,mr]=await Promise.all([readSheet(token,FORM_RANGE),readSheet(token,MASTER_RANGE)]);const forms=parseForm(fr),masters=parseMaster(mr),records=combine(masters,forms);
 const [people,rels,players]=await Promise.all([base44.asServiceRole.entities.Person.filter({tenant_id:TENANT_ID}),base44.asServiceRole.entities.ClubRelationship.filter({tenant_id:TENANT_ID,club_id:CLUB_ID}),base44.asServiceRole.entities.Player.filter({tenant_id:TENANT_ID,club_id:CLUB_ID})]);
 const byPid=new Map((people||[]).map((p:any)=>[String(p.id),p]));const relByPerson=new Map((rels||[]).filter((r:any)=>r.relationship_type==='member').map((r:any)=>[String(r.person_id),r]));const playerByPerson=new Map((players||[]).filter((p:any)=>p.person_id).map((p:any)=>[String(p.person_id),p]));
 const peopleByEmail=new Map<string,any>(),peopleByPhone=new Map<string,any>(),peopleByName=new Map<string,any[]>();for(const p of people||[]){for(const e of uniq([email(p.primary_email),...((p.alternate_emails||[]).map(email))]))if(e)peopleByEmail.set(e,p);for(const ph of uniq([phone(p.mobile),...((p.alternate_phones||[]).map(phone))]))if(ph)peopleByPhone.set(ph,p);const nk=nameKey(p.full_name);if(nk){if(!peopleByName.has(nk))peopleByName.set(nk,[]);peopleByName.get(nk)!.push(p);}}
 const relByMid=new Map((rels||[]).filter((r:any)=>r.membership_id).map((r:any)=>[String(r.membership_id),r]));const plan:any[]=[],review:any[]=[];
 for(const r of records){let person:any=null,reason='';const ir=r.membershipId?relByMid.get(String(r.membershipId)):null;if(ir){person=byPid.get(String(ir.person_id));reason='membership_id';}if(!person&&r.primaryEmail&&peopleByEmail.has(r.primaryEmail)){person=peopleByEmail.get(r.primaryEmail);reason='email';}if(!person&&r.mobile&&peopleByPhone.has(r.mobile)){person=peopleByPhone.get(r.mobile);reason='mobile';}if(!person){const same=peopleByName.get(nameKey(r.fullName))||[];const dm=r.dob?same.filter((p:any)=>clean(p.date_of_birth)===r.dob):[];if(dm.length===1){person=dm[0];reason='name+dob';}else if(same.length>0){review.push({name:r.fullName,email:r.primaryEmail,mobile:r.mobile,membershipId:r.membershipId,reason:'Possible existing person with same name; not auto-matched.'});continue;}}plan.push({r,person,reason,rel:person?relByPerson.get(String(person.id)):null,player:person?playerByPerson.get(String(person.id)):null});}
 const currentActive=(rels||[]).filter((r:any)=>r.relationship_type==='member'&&r.status==='active').length;
 const currentPending=(rels||[]).filter((r:any)=>r.relationship_type==='member'&&r.status==='pending').length;
 const current=currentActive+currentPending;
 const incrementalPlan=plan.map(item=>{const known=new Set((item.person?.source_rows||[]).map((x:any)=>String(x)));const hasNewSource=!item.person||(item.r.sourceRows||[]).some((x:any)=>!known.has(String(x)));return {...item,hasNewSource};}).sort((a,b)=>Number(!b.person)-Number(!a.person));
 if(mode==='preview')return Response.json({success:true,mode,source:{masterPaidActive:masters.length,formPaidActiveReferenceOnly:forms.length,combinedActive:records.length,authority:'2026-27 Member Master'},currentRallyHubMembers:current,newMembers:incrementalPlan.filter(x=>!x.person).map(x=>({name:x.r.fullName,email:x.r.primaryEmail,membershipId:x.r.membershipId,source:x.r.source})),matchedExisting:incrementalPlan.filter(x=>x.person).length,newOrChangedSourceRows:incrementalPlan.filter(x=>x.hasNewSource).length,needsReview:review});
 let added=0,updated=0,unchanged=0;const addedMembers:any[]=[];const stamp=new Date().toISOString();
 for(const item of incrementalPlan){const r=item.r;let person=item.person;let changed=false;const shouldReconcile=!!item.hasNewSource;if(!person){person=await base44.asServiceRole.entities.Person.create({tenant_id:TENANT_ID,full_name:r.fullName,primary_email:r.primaryEmail||undefined,mobile:r.mobile||undefined,date_of_birth:r.dob||undefined,full_postal_address:r.address||undefined,postal_code:r.eircode||undefined,emergency_contact_raw:r.emergencyRaw||undefined,emergency_contact_name:r.emergencyName||undefined,emergency_mobile:r.emergencyMobile||undefined,source_system:SOURCE,source_rows:r.sourceRows||[],last_synced_at:stamp,profile_visibility:'club',photo_visibility:'club'});added++;changed=true;addedMembers.push({name:r.fullName,email:r.primaryEmail,membershipId:r.membershipId,source:r.source});}else if(shouldReconcile){const patch:any={last_synced_at:stamp,source_system:SOURCE,source_rows:uniq([...(person.source_rows||[]),...(r.sourceRows||[])])};if(r.fullName&&r.fullName!==person.full_name)patch.full_name=r.fullName;if(r.primaryEmail&&r.primaryEmail!==email(person.primary_email))patch.primary_email=r.primaryEmail;if(r.mobile&&r.mobile!==phone(person.mobile))patch.mobile=r.mobile;if(r.dob&&r.dob!==clean(person.date_of_birth))patch.date_of_birth=r.dob;if(r.address&&r.address!==clean(person.full_postal_address))patch.full_postal_address=r.address;if(r.eircode&&r.eircode!==clean(person.postal_code))patch.postal_code=r.eircode;if(r.emergencyRaw&&!person.emergency_contact_raw)patch.emergency_contact_raw=r.emergencyRaw;if(r.emergencyName&&!person.emergency_contact_name)patch.emergency_contact_name=r.emergencyName;if(r.emergencyMobile&&!person.emergency_mobile)patch.emergency_mobile=r.emergencyMobile;person=await base44.asServiceRole.entities.Person.update(person.id,patch);changed=true;}
 let rel=item.rel||relByPerson.get(String(person.id));const rp:any={relationship_type:'member',status:'active',entry_route:'direct_membership',source_system:SOURCE,membership_id:r.membershipId||undefined,membership_type:r.membershipType||undefined,membership_category:'paid',membership_season:SEASON,payment_status:r.paymentStatus||undefined,payment_date:r.paymentDate||undefined,membership_amount:r.amount??undefined,source_row_refs:r.sourceRows||[],last_synced_at:stamp};if(rel){if(shouldReconcile){const diff=['status','membership_id','membership_type','membership_category','membership_season','payment_status','payment_date','membership_amount'].some(k=>clean(rel[k])!==clean(rp[k]));const oldRefs=(rel.source_row_refs||[]).map((x:any)=>String(x)).sort().join('|');const newRefs=(r.sourceRows||[]).map((x:any)=>String(x)).sort().join('|');if(diff||oldRefs!==newRefs){await base44.asServiceRole.entities.ClubRelationship.update(rel.id,rp);changed=true;}}}else{rel=await base44.asServiceRole.entities.ClubRelationship.create({tenant_id:TENANT_ID,club_id:CLUB_ID,person_id:person.id,...rp});changed=true;}
 let player=item.player||playerByPerson.get(String(person.id));if(player){if(shouldReconcile){const pp:any={relationship_type:'member',relationship_status:'active',status:'Active'};if(r.fullName&&r.fullName!==player.full_name)pp.full_name=r.fullName;if(r.primaryEmail&&r.primaryEmail!==email(player.email))pp.email=r.primaryEmail;if(r.mobile&&r.mobile!==phone(player.phone))pp.phone=r.mobile;const diff=Object.keys(pp).some(k=>clean(player[k])!==clean(pp[k]));if(diff){await base44.asServiceRole.entities.Player.update(player.id,pp);changed=true;}}}else{await base44.asServiceRole.entities.Player.create({person_id:person.id,full_name:r.fullName,email:r.primaryEmail||undefined,phone:r.mobile||undefined,status:'Active',tenant_id:TENANT_ID,club_id:CLUB_ID,club:'Clare Pickleball',relationship_type:'member',relationship_status:'active',wins:0,losses:0,matches_played:0,guest_visits_used:0});changed=true;}
 if(item.person){if(changed)updated++;else unchanged++;}}
 const finalMemberRels=await base44.asServiceRole.entities.ClubRelationship.filter({tenant_id:TENANT_ID,club_id:CLUB_ID,relationship_type:'member'});
 const finalActive=(finalMemberRels||[]).filter((r:any)=>r.status==='active').length;
 const finalPending=(finalMemberRels||[]).filter((r:any)=>r.status==='pending').length;
 const finalCurrent=finalActive+finalPending;
 try{await base44.asServiceRole.entities.AuditLog.create({tenant_id:TENANT_ID,club_id:CLUB_ID,user_id:user.id,action:'clare_membership_google_sync',entity_type:'ClubRelationship',entity_id:CLUB_ID,scope_type:'Club',scope_id:CLUB_ID,before_state:JSON.stringify({sourceActive:records.length}),after_state:JSON.stringify({added,updated,unchanged,needsReview:review.length,activeMembers:finalActive,pendingMembers:finalPending,currentMembers:finalCurrent}),reason:'Administrator synced Clare Pickleball 2026-27 membership from Google membership spreadsheet'});}catch{}
 const msg='Sync complete — '+records.length+' paid/active Member Master records checked · '+added+' new member'+(added===1?'':'s')+' added · '+updated+' existing record'+(updated===1?'':'s')+' reconciled · '+review.length+' need review · RallyHub now has '+finalActive+' active + '+finalPending+' pending = '+finalCurrent+' current Clare member'+(finalCurrent===1?'':'s')+'.';
 return Response.json({success:true,mode,added,updated,unchanged,needsReview:review,addedMembers,source:{masterPaidActive:masters.length,formPaidActiveReferenceOnly:forms.length,combinedActive:records.length,authority:'2026-27 Member Master'},activeMembers:finalActive,pendingMembers:finalPending,currentMembers:finalCurrent,message:msg});
}catch(error){return Response.json({error:(error as any)?.message||'Membership sync failed'},{status:500});}});