import React,{useEffect,useMemo,useState} from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { CheckCircle2,LockKeyhole,RefreshCw,ShieldCheck,X } from 'lucide-react';

function err(e){return e?.response?.data?.error||e?.data?.error||e?.message||'Player verification failed.';}
function storageKey(token){return `rallyhub-kotc-player-device:${token}`;}
function clientKey(token){return `rallyhub-kotc-player-client:${token}`;}
function getClientId(token){let id=localStorage.getItem(clientKey(token));if(!id){id=`kp_${crypto.randomUUID().replaceAll('-','')}`;localStorage.setItem(clientKey(token),id);}return id;}

export default function KotcMyPlayerPanel({shareToken,data,onRefresh,onIdentity}){
 const [deviceToken,setDeviceToken]=useState(()=>localStorage.getItem(storageKey(shareToken))||'');const [identityState,setIdentityState]=useState(null);const [selected,setSelected]=useState('');const [busy,setBusy]=useState(false);const [scoreState,setScoreState]=useState(null);const [a,setA]=useState('');const [b,setB]=useState('');const [serving,setServing]=useState('');const [editing,setEditing]=useState(false);const clientId=useMemo(()=>getClientId(shareToken),[shareToken]);
 const participants=data?.participants||[];const config=data?.player_link||{};const scoringEnabled=config.scoring_access==='verified_players';
 const loadIdentity=async({silent=false}={})=>{if(!deviceToken){setIdentityState(null);onIdentity?.(null);return null;}try{if(!silent)setBusy(true);const r=await base44.functions.invoke('kotcPlayerIdentity',{action:'state',shareToken,deviceToken});const state=r.data||null;setIdentityState(state);onIdentity?.(state?.verified?state.identity:null);if(state?.status==='expired'||state?.status==='revoked'||state?.status==='none'){localStorage.removeItem(storageKey(shareToken));setDeviceToken('');}return state;}catch(e){if(!silent)toast.error(err(e));return null;}finally{if(!silent)setBusy(false);}};
 const loadScore=async({silent=false}={})=>{if(!deviceToken||!identityState?.verified||!scoringEnabled){setScoreState(null);return null;}try{const r=await base44.functions.invoke('kotcPlayerScore',{action:'state',shareToken,deviceToken});setScoreState(r.data||null);const m=r.data?.match;if(m&&!editing){setA(m.team_a_score??'');setB(m.team_b_score??'');setServing(m.serving_side_at_horn||'');}return r.data;}catch(e){if(!silent)toast.error(err(e));return null;}};
 useEffect(()=>{loadIdentity();},[deviceToken,shareToken]);
 useEffect(()=>{if(identityState?.verified)loadScore();},[identityState?.verified,data?.session?.current_round_number,data?.current_matches?.map(m=>`${m.id}:${m.revision}`).join('|'),scoringEnabled]);
 useEffect(()=>{if(identityState?.status!=='pending')return;const t=setInterval(async()=>{const state=await loadIdentity({silent:true});if(state?.verified)toast.success('You are verified for this KOTC');},4000);return()=>clearInterval(t);},[identityState?.status,deviceToken]);
 const request=async()=>{if(!selected)return toast.error('Choose your name first.');try{setBusy(true);const r=await base44.functions.invoke('kotcPlayerIdentity',{action:'request',shareToken,participantId:selected,clientId});const raw=r.data?.deviceToken;if(!raw)throw new Error('Verification token was not created.');localStorage.setItem(storageKey(shareToken),raw);setDeviceToken(raw);setIdentityState({status:r.data?.status,verified:r.data?.status==='approved',verificationCode:r.data?.verificationCode,requestId:r.data?.requestId,identity:r.data?.status==='approved'?{participant_id:selected,display_name:r.data?.displayName}:null});if(r.data?.autoVerified)toast.success(`Verified as ${r.data?.displayName}`);}catch(e){toast.error(err(e));}finally{setBusy(false);}};
 const reset=()=>{localStorage.removeItem(storageKey(shareToken));setDeviceToken('');setIdentityState(null);setScoreState(null);onIdentity?.(null);setSelected('');};
 const claim=async(forCorrection=false)=>{try{setBusy(true);await base44.functions.invoke('kotcPlayerScore',{action:'claim',shareToken,deviceToken});setEditing(true);const m=scoreState?.match;if(forCorrection&&m){setA(m.team_a_score??'');setB(m.team_b_score??'');setServing(m.serving_side_at_horn||'');}toast.success(`Court ${scoreState?.match?.court||''} ready for your score`);}catch(e){toast.error(err(e));await loadScore({silent:true});}finally{setBusy(false);}};
 const release=async()=>{try{await base44.functions.invoke('kotcPlayerScore',{action:'release',shareToken,deviceToken});}catch{}setEditing(false);await loadScore({silent:true});};
 const save=async()=>{const m=scoreState?.match;if(!m)return;if(data?.session?.scoring_mode==='timed'&&Number(a)===Number(b)&&!serving)return toast.error('Choose which team was serving at the horn.');try{setBusy(true);const action=['completed','retired','abandoned','not_played'].includes(m.status)?'correct':'save';const r=await base44.functions.invoke('kotcPlayerScore',{action,shareToken,deviceToken,expectedRevision:Number(m.revision||0),teamAScore:Number(a),teamBScore:Number(b),servingSideAtHorn:Number(a)===Number(b)?serving:undefined});toast.success(r.data?.message||'Score saved');setEditing(false);await Promise.all([loadScore({silent:true}),onRefresh?.()]);}catch(e){toast.error(err(e));await Promise.all([loadScore({silent:true}),onRefresh?.()]);}finally{setBusy(false);}};

 if(config.identification_mode==='none')return null;
 if(!identityState?.verified){return <section className="rounded-xl border border-primary/20 bg-primary/5 p-3 space-y-3" data-testid="kotc-my-player-identify"><div className="flex items-start gap-2"><ShieldCheck className="w-4 h-4 text-primary mt-0.5"/><div><p className="text-sm font-bold">My KOTC</p><p className="text-xs text-muted-foreground mt-0.5">Choose your name once to personalise this Player Link.</p></div></div>{identityState?.status==='pending'?<div className="rounded-lg border border-amber-400/30 bg-amber-500/10 p-4 text-center"><p className="text-xs font-semibold">Show this code to the host</p><p className="font-mono text-4xl font-black tracking-[.2em] mt-2">{identityState.verificationCode}</p><p className="text-[11px] text-muted-foreground mt-2">Waiting for the host to verify this device. No text message or paid service is used.</p><div className="grid grid-cols-2 gap-2 mt-3"><Button variant="outline" onClick={()=>loadIdentity()} disabled={busy}><RefreshCw className={`w-4 h-4 mr-1 ${busy?'animate-spin':''}`}/>Check</Button><Button variant="ghost" onClick={reset}>Start Again</Button></div></div>:<><Select value={selected} onValueChange={setSelected}><SelectTrigger><SelectValue placeholder="Choose your name"/></SelectTrigger><SelectContent>{participants.map(p=><SelectItem key={p.id} value={p.id}>{p.display_name}</SelectItem>)}</SelectContent></Select><Button className="w-full min-h-11" onClick={request} disabled={busy||!selected}>{busy?'Checking…':"I'm Playing — Verify This Device"}</Button><p className="text-[10px] text-muted-foreground">If your RallyHub account is already linked to this player, verification can happen automatically. Otherwise the host confirms the 4-digit code.</p></>}</section>}
 }
 const me=identityState.identity;const myMatch=(data?.current_matches||[]).find(m=>[...(m.team_a_participant_ids||[]),...(m.team_b_participant_ids||[])].map(String).includes(String(me?.participant_id)));const teamSide=myMatch?.team_a_participant_ids?.map(String).includes(String(me?.participant_id))?'A':myMatch?'B':'';const partner=myMatch?(teamSide==='A'?myMatch.team_a:myMatch.team_b).find(n=>n!==me?.display_name):null;const opponents=myMatch?(teamSide==='A'?myMatch.team_b:myMatch.team_a):[];
 return <section className="rounded-xl border border-green-500/25 bg-green-500/5 p-3 space-y-3" data-testid="kotc-my-player"><div className="flex items-start justify-between gap-2"><div className="flex items-start gap-2"><CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5"/><div><p className="text-sm font-bold">My KOTC · {me?.display_name}</p><p className="text-[11px] text-muted-foreground">This device is verified for this session.</p></div></div><Button size="sm" variant="ghost" onClick={reset}>Not me</Button></div>{myMatch?<div className="rounded-lg border bg-background p-3"><div className="flex items-center justify-between"><p className="text-xs font-bold">Round {data?.session?.current_round_number} · Court {myMatch.court}</p><Badge variant="outline">{String(myMatch.status||'').toUpperCase()}</Badge></div><p className="text-sm mt-2"><b>Partner:</b> {partner||'—'}</p><p className="text-sm mt-1"><b>Opponents:</b> {(opponents||[]).join(' & ')}</p></div>:<div className="rounded-lg border border-amber-400/30 bg-amber-500/10 p-3 text-sm font-semibold">You are on the bench/resting this round.</div>}
 {scoringEnabled&&scoreState?.match&&<div className="rounded-lg border bg-background p-3 space-y-3" data-testid="kotc-my-score"><div className="flex items-center justify-between"><p className="text-xs font-bold">My Court Score</p>{scoreState.match.locked_by_other&&<Badge variant="outline"><LockKeyhole className="w-3 h-3 mr-1"/>Another scorer</Badge>}</div>{editing?<><div className="grid grid-cols-[1fr_80px] gap-2 items-center"><span className="text-sm">{myMatch?.team_a?.join(' & ')}</span><Input inputMode="numeric" value={a} onChange={e=>setA(e.target.value.replace(/\D/g,'').slice(0,2))} className="text-center font-bold"/></div><div className="grid grid-cols-[1fr_80px] gap-2 items-center"><span className="text-sm">{myMatch?.team_b?.join(' & ')}</span><Input inputMode="numeric" value={b} onChange={e=>setB(e.target.value.replace(/\D/g,'').slice(0,2))} className="text-center font-bold"/></div>{data?.session?.scoring_mode==='timed'&&a!==''&&b!==''&&Number(a)===Number(b)&&<Select value={serving} onValueChange={setServing}><SelectTrigger><SelectValue placeholder="Who was serving at the horn?"/></SelectTrigger><SelectContent><SelectItem value="A">Team A serving</SelectItem><SelectItem value="B">Team B serving</SelectItem></SelectContent></Select>}<div className="grid grid-cols-2 gap-2"><Button onClick={save} disabled={busy||a===''||b===''}>{busy?'Saving…':'Save Result'}</Button><Button variant="outline" onClick={release} disabled={busy}><X className="w-4 h-4 mr-1"/>Cancel</Button></div></>:<><div className="flex justify-between text-sm"><span>{myMatch?.team_a?.join(' & ')}</span><b>{scoreState.match.team_a_score??'—'}</b></div><div className="flex justify-between text-sm"><span>{myMatch?.team_b?.join(' & ')}</span><b>{scoreState.match.team_b_score??'—'}</b></div><Button className="w-full" variant={scoreState.match.status==='completed'?'outline':'default'} onClick={()=>claim(scoreState.match.status==='completed')} disabled={busy||scoreState.match.locked_by_other}>{scoreState.match.status==='completed'?(scoreState.match.can_correct?'Update My Court Score':'Score Saved — Host Can Correct'):'Enter My Court Score'}</Button></>}</div>}
 </section>;
}
