import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { sendClubEmail } from './emailRouter.ts';

const APP_BASE_URL='https://rallyhub.ie';
function clean(v:any,max=3000){return String(v??'').trim().slice(0,max);}
function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('');}
function validHostAccess(a:any,tenantId:string,sessionId:string){if(!a||a.status!=='active'||!['session_host','assistant_host'].includes(a.role))return false;if(String(a.tenant_id||'')!==String(tenantId)||String(a.session_id||'')!==String(sessionId))return false;const now=Date.now();if(a.starts_at&&Date.parse(a.starts_at)>now)return false;if(a.ends_at&&Date.parse(a.ends_at)<now)return false;return true;}
async function authorised(base44:any,user:any,session:any){if(user?.role==='admin')return true;const rows=await base44.asServiceRole.entities.KotcSessionAccess.filter({session_id:session.id,user_id:user.id,status:'active'});return (rows||[]).some((a:any)=>validHostAccess(a,session.tenant_id,session.id));}
async function ensureShare(base44:any,session:any,user:any){let rows=await base44.asServiceRole.entities.KotcSessionShare.filter({session_id:session.id,status:'active'},'-created_date',5);let share=rows?.[0];if(!share)share=await base44.asServiceRole.entities.KotcSessionShare.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,tournament_id:session.tournament_id,token:randomToken(),status:'active',created_by_user_id:user.id,visible_tabs_json:JSON.stringify(['live','players','rounds','leaderboard','event_info']),scoring_access:'read_only',identification_mode:'host_code'});return share;}
function visible(row:any,session:any){if(!row||row.status!=='published')return false;const mode=row.expiry_mode||'manual';if(mode==='event_start'&&['in_progress','paused','completed','finalised','abandoned'].includes(session.status))return false;if(row.expires_at&&Date.parse(row.expires_at)<=Date.now())return false;return true;}

Deno.serve(async req=>{try{
 const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user)return Response.json({error:'Authentication required.'},{status:401});const body=await req.json().catch(()=>({}));const sessionId=clean(body.sessionId,180),action=clean(body.action||'status',40);if(!sessionId)return Response.json({error:'sessionId required'},{status:400});
 const session=(await base44.asServiceRole.entities.KotcSession.filter({id:sessionId}))?.[0];if(!session)return Response.json({error:'KOTC session not found.'},{status:404});if(!(await authorised(base44,user,session)))return Response.json({error:'Session Host access required.'},{status:403});
 const share=await ensureShare(base44,session,user);const current=async()=>{const rows=await base44.asServiceRole.entities.KotcSessionBroadcast.filter({session_id:session.id,status:'published'},'-published_at',10);return (rows||[]).find((r:any)=>visible(r,session))||null;};
 const participants=await base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id},'seed_rank',150);const playerIds=[...new Set((participants||[]).map((p:any)=>p.player_id).filter(Boolean))];const players=playerIds.length?await base44.asServiceRole.entities.Player.filter({id:{$in:playerIds}}):[];const byId=Object.fromEntries((players||[]).map((p:any)=>[p.id,p]));const recipientRows=(participants||[]).map((p:any)=>({name:p.display_name,email:clean(byId[p.player_id]?.email,320).toLowerCase()})).filter((r:any)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email));const seen=new Set<string>();const recipients=recipientRows.filter((r:any)=>!seen.has(r.email)&&(seen.add(r.email),true));const playerLink=`${APP_BASE_URL}/kotc-live/${share.token}`;
 if(action==='status')return Response.json({success:true,broadcast:await current(),eligiblePlayers:(participants||[]).length,emailRecipients:recipients.length,playerLinkUrl:playerLink,testRecipient:user.email||null,playerLinkDelivery:{recipientCount:Number(share.player_link_email_recipient_count||0),sentCount:Number(share.player_link_email_sent_count||0),failedCount:Number(share.player_link_email_failed_count||0),sentAt:share.player_link_email_sent_at||null}});
 if(action==='send_player_link'){const scope={scopeType:'tenant' as const,purpose:'club_comms',tenantId:String(session.tenant_id),clubId:session.club_id?String(session.club_id):null};let sent=0,failed=0;const failures:any[]=[];for(const r of recipients){try{const first=String(r.name||'Player').trim().split(/\s+/)[0]||'Player';const subject=`${session.name} — KOTC Player Link`;const text=`Hi ${first},\n\nYour King of the Court Player Link is ready. Keep this one link — it will update as the event moves from players and rounds through live scoring and final results.\n\n${playerLink}\n\nIf player scoring is enabled, choose your name in My KOTC and show the host the 4-digit verification code on your phone.\n\nPowered by RallyHub`;const html=`<div style="font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.55;color:#111827"><p>Hi ${first},</p><p>Your King of the Court Player Link is ready. Keep this one link — it updates through the event and becomes the final results view when play finishes.</p><p><a href="${playerLink}" style="display:inline-block;background:#1d4ed8;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px">Open KOTC Player Link</a></p><p style="font-size:13px;color:#6b7280">If player scoring is enabled, choose your name in My KOTC and show the host the 4-digit verification code on your phone.</p><p style="font-size:12px;color:#6b7280">Powered by RallyHub</p></div>`;await sendClubEmail(base44,scope,{to:r.email,subject,textBody:text,htmlBody:html});sent++;}catch(e){failed++;failures.push({email:r.email,error:clean((e as any)?.message||'Send failed',240)});}}const sentAt=new Date().toISOString();await base44.asServiceRole.entities.KotcSessionShare.update(share.id,{player_link_email_recipient_count:recipients.length,player_link_email_sent_count:sent,player_link_email_failed_count:failed,player_link_email_sent_at:sentAt});return Response.json({success:true,emailRecipients:recipients.length,sent,failed,failures:failures.slice(0,5),playerLinkUrl:playerLink,playerLinkDelivery:{recipientCount:recipients.length,sentCount:sent,failedCount:failed,sentAt}});}
 if(action==='remove'){const row=await current();if(row)await base44.asServiceRole.entities.KotcSessionBroadcast.update(row.id,{status:'removed'});return Response.json({success:true});}
 const message=clean(body.message,2000);if(!message)return Response.json({error:'Enter a KOTC update first.'},{status:400});
 if(action==='test_email'){const to=clean(user.email,320).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to))return Response.json({error:'Your RallyHub account has no valid email address for a test.'},{status:409});const scope={scopeType:'tenant' as const,purpose:'club_comms',tenantId:String(session.tenant_id),clubId:session.club_id?String(session.club_id):null};const subject=`TEST — KOTC Update · ${session.name}`;const text=`TEST EMAIL — NOT A BROADCAST\n\n${message}\n\nOpen your KOTC Player Link:\n${playerLink}\n\nPowered by RallyHub`;const safe=message.replace(/[&<>"']/g,(c:string)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));const html=`<div style="font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.55;color:#111827"><p style="font-weight:700">TEST EMAIL — NOT A BROADCAST</p><h2>KOTC Update</h2><p style="white-space:pre-line">${safe}</p><p><a href="${playerLink}">Open KOTC Player Link</a></p><p style="font-size:12px;color:#6b7280">Powered by RallyHub</p></div>`;await sendClubEmail(base44,scope,{to,subject,textBody:text,htmlBody:html});return Response.json({success:true,test:true,to,playerLinkUrl:playerLink});}
 if(action!=='publish')return Response.json({error:'Unknown broadcast action.'},{status:400});const requested=clean(body.expiryMode||'60m',20);const allowed=new Set(['manual','event_start','30m','60m','120m','custom']);const expiryMode=allowed.has(requested)?requested:'60m';const now=Date.now();let expiresAt:any=null;if(expiryMode==='30m')expiresAt=new Date(now+30*60000).toISOString();else if(expiryMode==='60m')expiresAt=new Date(now+60*60000).toISOString();else if(expiryMode==='120m')expiresAt=new Date(now+120*60000).toISOString();else if(expiryMode==='custom'){const mins=Math.max(5,Math.min(1440,Math.round(Number(body.customMinutes||60))));expiresAt=new Date(now+mins*60000).toISOString();}
 const prior=await current();if(prior)await base44.asServiceRole.entities.KotcSessionBroadcast.update(prior.id,{status:'removed'});const publishedAt=new Date().toISOString();let row=await base44.asServiceRole.entities.KotcSessionBroadcast.create({tenant_id:session.tenant_id,club_id:session.club_id,session_id:session.id,share_id:share.id,title:'KOTC Update',message,status:'published',published_at:publishedAt,published_by_user_id:user.id,expiry_mode:expiryMode,expires_at:expiresAt,email_recipient_count:recipients.length,email_sent_count:0,email_failed_count:0});
 let sent=0,failed=0;const failures:any[]=[];if(body.sendEmail===true&&recipients.length){const scope={scopeType:'tenant' as const,purpose:'club_comms',tenantId:String(session.tenant_id),clubId:session.club_id?String(session.club_id):null};for(const r of recipients){try{const subject=`KOTC Update · ${session.name}`;const text=`Hi ${String(r.name||'Player').trim().split(/\s+/)[0]||'Player'},\n\n${message}\n\nOpen your KOTC Player Link:\n${playerLink}\n\nPowered by RallyHub`;const html=`<div style="font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.55;color:#111827"><h2 style="margin:0 0 16px">KOTC Update</h2><p style="white-space:pre-line">${message.replace(/[&<>"']/g,(c:string)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}</p><p><a href="${playerLink}" style="display:inline-block;background:#1d4ed8;color:white;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px">Open KOTC Player Link</a></p><p style="font-size:12px;color:#6b7280">Powered by RallyHub</p></div>`;await sendClubEmail(base44,scope,{to:r.email,subject,textBody:text,htmlBody:html});sent++;}catch(e){failed++;failures.push({email:r.email,error:clean((e as any)?.message||'Send failed',240)});}}
   row=await base44.asServiceRole.entities.KotcSessionBroadcast.update(row.id,{email_sent_at:new Date().toISOString(),email_sent_count:sent,email_failed_count:failed});
 }
 return Response.json({success:true,broadcast:row,eligiblePlayers:(participants||[]).length,emailRecipients:recipients.length,sent,failed,failures:failures.slice(0,5),playerLinkUrl:playerLink});
}catch(error){console.error('kotcSessionBroadcast',error);return Response.json({error:(error as any)?.message||'Could not publish KOTC update.'},{status:500});}});
