import React,{useMemo,useState} from "react";
import {useAuth} from "@/lib/AuthContext";
import {simulateCampaign} from "@/services/communications/simulator.js";
const tabs=["Overview","Compose","Audiences","Templates & Brand","Workflows","Polls & Feedback","Delivery","Consent","Analytics","Settings"];
const samplePeople=[{person_id:"p1",club:"clare",email:"player1@example.test"},{person_id:"p2",club:"clare",email:"player2@example.test"},{person_id:"p3",club:"galway",email:"player3@example.test"}];
export default function CommunicationsCentre(){
 const {user}=useAuth();const [tab,setTab]=useState("Overview");const [subject,setSubject]=useState("KOTC results for {{name}}");const [html,setHtml]=useState("<h2>Your results are ready</h2><p>Hello {{name}}, your private results link is ready.</p>");const [plain,setPlain]=useState("Your results are ready\n\nHello {{name}}, your private results link is ready.");
 const sim=useMemo(()=>simulateCampaign({campaign:{kind:"operational",purpose:"competition",audience_definition:{include:[{field:"club",op:"eq",value:"clare"}]},sample_data:{name:"Test Player"}},people:samplePeople,template:{subjectTemplate:subject,htmlTemplate:html,plainTextTemplate:plain},brandKit:{name:"Tenant Brand"}}),[subject,html,plain]);
 if(user?.role!=="admin")return <div className="p-8"><h1 className="text-2xl font-bold">Communications Centre</h1><p className="mt-3">Administrator access required.</p></div>;
 return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6">
  <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-widest text-amber-700">Standalone build · external delivery disabled</div><h1 className="text-3xl font-black">Communications Centre</h1><p className="text-sm text-muted-foreground mt-1">Compose, target, automate, interact and audit from one tenant-safe communications engine.</p></div><div className="rounded-lg border px-3 py-2 text-sm"><b>Mode:</b> BUILD / SIMULATION</div></div>
  <div className="flex gap-2 overflow-x-auto pb-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={"whitespace-nowrap rounded-full px-4 py-2 text-sm border "+(tab===t?"bg-slate-900 text-white":"bg-white")}>{t}</button>)}</div>
  {tab==="Overview"&&<div className="grid md:grid-cols-4 gap-4">{[["Campaigns","Operational + marketing"],["Interactive","Polls · RSVP · feedback"],["Workflows","Goal-based journeys"],["Safety","Consent · pre-flight · audit"]].map(x=><div key={x[0]} className="rounded-xl border bg-white p-5"><div className="font-bold">{x[0]}</div><div className="text-sm text-muted-foreground mt-1">{x[1]}</div></div>)}</div>}
  {tab==="Compose"&&<div className="grid lg:grid-cols-2 gap-5"><div className="rounded-xl border bg-white p-5 space-y-4"><h2 className="font-bold text-lg">Composer</h2><label className="block text-sm font-medium">Subject<input className="mt-1 w-full border rounded-lg p-2" value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="block text-sm font-medium">HTML<textarea className="mt-1 w-full border rounded-lg p-2 min-h-36 font-mono text-xs" value={html} onChange={e=>setHtml(e.target.value)}/></label><label className="block text-sm font-medium">Plain text<textarea className="mt-1 w-full border rounded-lg p-2 min-h-32" value={plain} onChange={e=>setPlain(e.target.value)}/></label><div className="text-xs text-amber-700">Preview only. No Send action exists in standalone build mode.</div></div><div className="rounded-xl border bg-white p-5"><h2 className="font-bold text-lg mb-3">Simulation preview</h2><div className="text-sm mb-3"><b>{sim.eligible_count}</b> eligible · <b>{sim.duplicate_count}</b> duplicates · pre-flight <b>{sim.preflight.risk}</b></div><div className="border rounded-lg p-4"><div className="font-bold mb-3">{sim.rendered.subject}</div><iframe title="Email preview" className="w-full h-72 border rounded" srcDoc={sim.rendered.html}/></div><pre className="mt-3 whitespace-pre-wrap text-xs bg-slate-50 p-3 rounded">{sim.rendered.plainText}</pre></div></div>}
  {tab!=="Overview"&&tab!=="Compose"&&<FeaturePanel tab={tab}/>}
 </div>;
}
function FeaturePanel({tab}){const map={
 "Audiences":["Dynamic filters","AND / OR logic","Exclusions","Saved audiences","Exact eligible/excluded/suppressed counts","Deduplication"],
 "Templates & Brand":["RallyHub + tenant BrandKits","Reusable blocks","Versioned templates","HTML + plain text","Locked brand elements","Accessibility checks"],
 "Workflows":["Trigger → condition → action → wait → re-check → branch","Goal-based exits","Event-relative timing","Payment-stop rules","Simulation before activation","Pause / resume / escalation"],
 "Polls & Feedback":["Polls","Feedback","Suggestions","Surveys","RSVP","Availability","Anonymous or identified","Timed close + reminder workflow"],
 "Delivery":["Provider adapters","Queue + batches","Idempotency","Safety delay / cancel","Stop remaining","Retry + failure ledger","WhatsApp/SMS/push adapters"],
 "Consent":["Tenant vs platform permission","Preference centre","Double opt-in evidence","Persistent suppressions","Unsubscribe / complaints","Purpose-aware service vs marketing"],
 "Analytics":["Sent / delivered / failed","Open (indicative)","Clicks","RallyHub action completed","Bounce / complaint / opt-out","Conversion attribution","Communication pressure"],
 "Settings":["Channel configuration","Sender identity","Quiet hours","Rate limits","Domain health","Test mode","Role/approval policy"]
};return <div className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">{tab}</h2><div className="grid md:grid-cols-2 gap-3 mt-4">{(map[tab]||[]).map(x=><div key={x} className="rounded-lg bg-slate-50 border p-3 text-sm">{x}</div>)}</div><p className="mt-5 text-xs text-muted-foreground">Standalone capability surface. Activation and source-module adapters are deliberately outside this build.</p></div>}
