import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { CalendarDays, Mail, MapPin, MessageCircle } from 'lucide-react';
import Seo from '@/components/public/Seo';
import PublicDirectoryHeader from '@/components/public/PublicDirectoryHeader';

const filters=[['all','All'],['tournament','Tournaments'],['coaching','Coaching'],['holiday','Holidays'],['other','Other']];
const prettyDate=value=>{const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-IE',{weekday:'short',day:'numeric',month:'short',year:'numeric'})};
export default function Events() {
 const [filter,setFilter]=useState('all');
 const {data:events=[],isLoading}=useQuery({queryKey:['public-events'],queryFn:()=>base44.entities.Tournament.filter({event_public_visible:true,event_publish_status:'published'},'start_date',100),staleTime:60000});
 const visible=useMemo(()=>events.filter(e=>filter==='all'||e.event_category===filter),[events,filter]);
 return <><Seo title="Pickleball Events, Tournaments & Coaching in Ireland | RallyHub" description="Discover upcoming pickleball events, tournaments, competitions, social events and coaching opportunities in Ireland." path="/events" robots="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" />
 <div className="min-h-screen bg-white text-[#07184c]"><PublicDirectoryHeader/><main className="bg-[linear-gradient(135deg,#f8fcfd_0%,#f1faf6_100%)] px-4 py-12 sm:px-6 sm:py-16">
  <section className="mx-auto max-w-[1180px]"><div className="text-center"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#078e48]">RallyHub Events</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em] sm:text-5xl">Events, tournaments & coaching</h1><p className="mx-auto mt-4 max-w-[720px] text-base leading-7 text-[#52627d]">Discover upcoming playing opportunities. Clubs can publish events from RallyHub while the national Events page remains open to organisers who want an event considered for listing.</p></div>
  <div className="mt-7 flex flex-wrap justify-center gap-2">{filters.map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`rounded-full border px-4 py-2 text-sm font-bold ${filter===v?'border-[#078e48] bg-[#078e48] text-white':'border-[#cfdcdf] bg-white text-[#0c2257]'}`}>{l}</button>)}</div>
  <div className="mt-9 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{isLoading?<p className="col-span-full text-center text-sm text-[#52627d]">Loading events…</p>:visible.map(e=><article key={e.id} className="overflow-hidden rounded-[20px] border border-[#dbe6e8] bg-white shadow-[0_12px_35px_rgba(8,30,70,.08)]">{e.event_image_url?<div className="aspect-[1/1.4142] overflow-hidden bg-[#eef4f5]"><img src={e.event_image_url} alt="" className="h-full w-full object-cover" style={{objectPosition:`${Number(e.event_image_position_x??50)}% ${Number(e.event_image_position_y??50)}%`,transform:`scale(${Number(e.event_image_zoom??1)})`,transformOrigin:`${Number(e.event_image_position_x??50)}% ${Number(e.event_image_position_y??50)}%`}}/></div>:<div className="flex aspect-[1/1.4142] items-center justify-center bg-[#eef7f3]"><CalendarDays className="h-12 w-12 text-[#078e48]"/></div>}<div className="p-5"><span className="text-[10px] font-black uppercase tracking-wider text-[#078e48]">{e.event_category||'Event'}</span><h2 className="mt-1 text-xl font-black">{e.name}</h2><p className="mt-3 text-sm font-semibold">{prettyDate(e.start_date)} {e.event_start_time&&`· ${e.event_start_time}`}{e.event_end_time&&`–${e.event_end_time}`}</p>{e.location&&<p className="mt-2 flex gap-1.5 text-sm text-[#52627d]"><MapPin className="mt-0.5 h-4 w-4 shrink-0"/>{e.location}</p>}{e.description&&<p className="mt-4 line-clamp-5 whitespace-pre-line text-sm leading-6 text-[#52627d]">{e.description}</p>}</div></article>)}{!isLoading&&!visible.length&&<p className="col-span-full py-8 text-center text-sm text-[#52627d]">No events in this category yet.</p>}</div>
  <section className="mx-auto mt-12 max-w-[820px] rounded-[20px] border border-[#dbe6e8] bg-white p-6 text-center"><h2 className="text-xl font-black">Thinking about an event?</h2><p className="mx-auto mt-2 max-w-[620px] text-sm leading-6 text-[#52627d]">If your club is not yet publishing through RallyHub, get in touch and we can help you get your event listed.</p><div className="mt-5 flex flex-col justify-center gap-3 sm:flex-row"><a href="mailto:rallyhubapp@gmail.com" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border px-4 text-sm font-bold"><Mail className="h-4 w-4"/>Email Brian</a><a href="https://wa.me/353878100333" target="_blank" rel="noopener noreferrer" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[#078e48] px-4 text-sm font-bold text-white"><MessageCircle className="h-4 w-4"/>WhatsApp Brian</a></div></section>
  </section></main><footer className="bg-[#053c56] px-4 py-5 text-center text-xs text-white/75">© 2026 RallyHub All rights reserved. · <Link to="/directory">Directory</Link> · <Link to="/contact">Contact</Link></footer></div></>;
}
