import React, { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CheckCircle2, Loader2, ShieldCheck, Trophy } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import PublicCopyrightFooter from '@/components/public/PublicCopyrightFooter';

const EMPTY={fullName:'',fullPostalAddress:'',postalCode:'',email:'',mobile:'',dateOfBirth:'',previousSports:[],otherSportsText:'',playedTargetSportBefore:'',targetSportExperienceDuration:'',targetSportLevel:'',activityLevel:'',activityBackground:'',medicalResponse:'',medicalNotes:'',gdprConsent:false,photoVideoConsent:''};
const activityOptions=[['low','Not very active at present'],['occasional','Occasionally active'],['regular','Regularly active / sporty'],['very_active','Very active / play sport regularly']];
const experienceOptions=['Only tried it / very briefly','Under 3 months','3–6 months','6–12 months','1–2 years','More than 2 years'];

export default function PublicWaitingList(){
  const {clubSlug}=useParams();
  const [config,setConfig]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(null);
  const [form,setForm]=useState(EMPTY);
  const club=config?.club||{}; const sport=config?.targetSportName||'sport';
  useEffect(()=>{let live=true;base44.functions.invoke('waitingList',{action:'public_get',clubSlug}).then(r=>{if(r.data?.error)throw new Error(r.data.error);if(live)setConfig(r.data?.config||null)}).catch(e=>{if(live)setError(e?.message||'Waiting list unavailable.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[clubSlug]);
  const sports=useMemo(()=>config?.previousSportsOptions||[],[config]);
  const toggleSport=value=>setForm(p=>({...p,previousSports:p.previousSports.includes(value)?p.previousSports.filter(x=>x!==value):[...p.previousSports,value]}));
  const update=(key,value)=>setForm(p=>({...p,[key]:value}));
  const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{const r=await base44.functions.invoke('waitingList',{action:'public_submit',clubSlug,...form});if(r.data?.error)throw new Error(r.data.error);setDone(r.data);window.scrollTo({top:0,behavior:'smooth'})}catch(err){setError(err?.message||'Could not join the waiting list.')}finally{setBusy(false)}};
  if(loading)return <div className="min-h-screen bg-background flex items-center justify-center"><Loader2 className="w-8 h-8 animate-spin text-primary"/></div>;
  if(!config)return <div className="min-h-screen bg-background flex flex-col"><main className="flex-1 mx-auto max-w-2xl px-4 py-12"><div className="glass rounded-2xl p-6"><h1 className="text-xl font-bold">Waiting list unavailable</h1><p className="mt-2 text-sm text-muted-foreground">{error||'This club is not accepting waiting-list registrations right now.'}</p></div></main><PublicCopyrightFooter/></div>;
  if(done)return <div className="min-h-screen bg-background flex flex-col"><main className="flex-1 mx-auto w-full max-w-2xl px-4 py-10"><section className="rounded-3xl border border-emerald-500/30 bg-emerald-500/10 p-7 text-center"><CheckCircle2 className="mx-auto w-12 h-12 text-emerald-500"/><h1 className="mt-4 text-2xl font-black">You're on the waiting list</h1><p className="mt-3 text-sm text-muted-foreground">Thanks, {done.entry?.fullName}. Your waiting-list position is recorded from <strong className="text-foreground">{new Date(done.entry?.firstJoinedAt).toLocaleString('en-IE')}</strong>.</p><p className="mt-4 rounded-xl bg-background/60 p-4 text-sm"><strong>Important:</strong> joining the waiting list does not make you a club member. The club will contact you when a suitable place becomes available.</p><Link to={'/directory/'+clubSlug} className="mt-6 inline-flex"><Button variant="outline">Back to {club.name}</Button></Link></section></main><PublicCopyrightFooter/></div>;
  return <div className="min-h-screen bg-background text-foreground flex flex-col"><main className="flex-1"><div className="mx-auto max-w-3xl px-4 py-7 sm:py-10 space-y-6">
    <section className="rounded-3xl border border-border bg-card p-5 sm:p-7 text-center shadow-sm" style={{borderTop:'7px solid '+(club.primaryColour||'#2563eb')}}>{club.logoUrl&&<img src={club.logoUrl} alt={club.name+' logo'} className="mx-auto h-20 w-20 rounded-2xl bg-white object-contain p-1.5 shadow-sm"/>}<h1 className="mt-4 text-2xl sm:text-3xl font-black">{config.title}</h1>{config.programmeName&&<p className="mt-2 font-semibold">{config.programmeName}</p>}<p className="mt-2 text-sm text-muted-foreground">{config.description}</p><div className="mt-4 text-xs text-muted-foreground">Powered by <strong>RallyHub</strong></div></section>
    {error&&<div className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
    <form onSubmit={submit} className="space-y-5">
      <section className="rounded-2xl border bg-card p-5 sm:p-6 space-y-4"><h2 className="text-lg font-bold">Your details</h2><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Full name</Label><Input className="mt-1" value={form.fullName} onChange={e=>update('fullName',e.target.value)} autoComplete="name"/></div><div className="sm:col-span-2"><Label>Full postal address</Label><textarea className="mt-1 min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.fullPostalAddress} onChange={e=>update('fullPostalAddress',e.target.value)}/></div><div><Label>Eircode / postcode</Label><Input className="mt-1" value={form.postalCode} onChange={e=>update('postalCode',e.target.value)}/></div><div><Label>Date of birth</Label><Input type="date" className="mt-1" value={form.dateOfBirth} onChange={e=>update('dateOfBirth',e.target.value)}/></div><div><Label>Email</Label><Input type="email" className="mt-1" value={form.email} onChange={e=>update('email',e.target.value)}/></div><div><Label>Mobile</Label><Input className="mt-1" value={form.mobile} onChange={e=>update('mobile',e.target.value)}/></div></div></section>
      <section className="rounded-2xl border bg-card p-5 sm:p-6 space-y-4"><div className="flex gap-3"><Trophy className="w-5 h-5 text-primary shrink-0"/><div><h2 className="text-lg font-bold">Sport & activity background</h2><p className="text-sm text-muted-foreground">This helps the club understand previous experience. It does not automatically move anyone ahead on the list.</p></div></div><div><Label>Which sports have you ever played, even briefly or at school?</Label><div className="mt-2 grid grid-cols-2 sm:grid-cols-3 gap-2">{sports.map(s=><label key={s} className="flex items-center gap-2 rounded-lg border p-3 text-sm cursor-pointer"><input type="checkbox" checked={form.previousSports.includes(s)} onChange={()=>toggleSport(s)}/><span>{s}</span></label>)}</div></div>{form.previousSports.includes('Other')&&<div><Label>Other sport(s)</Label><Input className="mt-1" value={form.otherSportsText} onChange={e=>update('otherSportsText',e.target.value)}/></div>}
      {config.askTargetSportExperience&&<><div><Label>Have you played {sport} before?</Label><div className="mt-2 grid grid-cols-2 gap-2">{['yes','no'].map(v=><button type="button" key={v} onClick={()=>update('playedTargetSportBefore',v)} className={'rounded-xl border px-4 py-3 text-sm font-semibold '+(form.playedTargetSportBefore===v?'border-primary bg-primary text-primary-foreground':'bg-background')}>{v==='yes'?'Yes':'No'}</button>)}</div></div>{form.playedTargetSportBefore==='yes'&&<div className="grid gap-4 sm:grid-cols-2"><div><Label>How long have you played {sport}?</Label><select className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.targetSportExperienceDuration} onChange={e=>update('targetSportExperienceDuration',e.target.value)}><option value="">Choose…</option>{experienceOptions.map(v=><option key={v}>{v}</option>)}</select></div><div><Label>How would you describe your level? <span className="text-muted-foreground">(optional)</span></Label><Input className="mt-1" value={form.targetSportLevel} onChange={e=>update('targetSportLevel',e.target.value)} placeholder="e.g. beginner, social, improver"/></div></div>}</>}
      {config.askActivityBackground&&<><div><Label>How active are you generally?</Label><select className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.activityLevel} onChange={e=>update('activityLevel',e.target.value)}><option value="">Choose…</option>{activityOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><Label>Tell us briefly about any other sport or regular activity <span className="text-muted-foreground">(optional)</span></Label><textarea className="mt-1 min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.activityBackground} onChange={e=>update('activityBackground',e.target.value)}/></div></>}</section>
      {config.askMedicalInformation&&<section className="rounded-2xl border bg-card p-5 sm:p-6 space-y-4"><div className="flex gap-3"><ShieldCheck className="w-5 h-5 text-primary shrink-0"/><div><h2 className="text-lg font-bold">Health information</h2><p className="text-sm text-muted-foreground">This is private club-admin information and is used only to help support safe participation.</p></div></div><div><Label>Is there any medical condition, injury or health information the club should know about for safe participation?</Label><div className="mt-2 grid grid-cols-2 gap-2">{['yes','no'].map(v=><button type="button" key={v} onClick={()=>update('medicalResponse',v)} className={'rounded-xl border px-4 py-3 text-sm font-semibold '+(form.medicalResponse===v?'border-primary bg-primary text-primary-foreground':'bg-background')}>{v==='yes'?'Yes':'No'}</button>)}</div></div>{form.medicalResponse==='yes'&&<div><Label>Please give the relevant information</Label><textarea className="mt-1 min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.medicalNotes} onChange={e=>update('medicalNotes',e.target.value)}/></div>}</section>}
      <section className="rounded-2xl border bg-card p-5 sm:p-6 space-y-4"><h2 className="text-lg font-bold">Consent</h2><label className="flex items-start gap-3 cursor-pointer"><input type="checkbox" className="mt-1" checked={form.gdprConsent} onChange={e=>update('gdprConsent',e.target.checked)}/><span className="text-sm leading-6">{config.consentText}</span></label><div><p className="text-sm leading-6">{config.photoVideoText}</p><div className="mt-3 grid grid-cols-2 gap-2">{['yes','no'].map(v=><button type="button" key={v} onClick={()=>update('photoVideoConsent',v)} className={'rounded-xl border px-4 py-3 text-sm font-semibold '+(form.photoVideoConsent===v?'border-primary bg-primary text-primary-foreground':'bg-background')}>{v==='yes'?'Yes, I consent':'No, I do not consent'}</button>)}</div></div></section>
      <div className="rounded-xl border border-amber-300/40 bg-amber-500/10 p-4 text-sm"><strong>Waiting list only:</strong> submitting this form does not create club membership or RallyHub member access. Your first joining timestamp is kept if you later update your details.</div>
      <Button type="submit" disabled={busy} className="w-full min-h-12 text-base font-bold">{busy&&<Loader2 className="w-4 h-4 mr-2 animate-spin"/>}Join waiting list</Button>
    </form>
  </div></main><PublicCopyrightFooter/></div>;
}
