import React,{useEffect,useState} from 'react';
import { useParams } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { Badge } from '@/components/ui/badge';
import { AppearanceQuickButton } from '@/components/appearance/AppearanceControls';
import RallyHubPublicBrand from '@/components/branding/RallyHubPublicBrand';
import { Crown,RefreshCw,Trophy } from 'lucide-react';

function err(e){return e?.response?.data?.error||e?.data?.error||e?.message||'Your KOTC result is unavailable.';}
export default function PublicKotcParticipantResult(){
 const {token}=useParams();const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;(async()=>{try{const r=await base44.functions.invoke('kotcParticipantResult',{token});if(r.data?.error)throw new Error(r.data.error);if(alive)setData(r.data);}catch(e){if(alive)setError(err(e));}})();return()=>{alive=false;};},[token]);
 if(error)return <div className="min-h-screen bg-background text-foreground grid place-items-center p-4"><AppearanceQuickButton className="fixed top-3 right-3"/><div className="glass rounded-xl p-5 text-center max-w-md"><RallyHubPublicBrand moduleName="King of the Court" pageLabel="My Result"/><h1 className="font-bold mt-4">Personal result unavailable</h1><p className="text-sm text-muted-foreground mt-2">{error}</p></div></div>;
 if(!data)return <div className="min-h-screen bg-background text-foreground grid place-items-center"><RefreshCw className="w-6 h-6 animate-spin"/></div>;
 const p=data.player||{};
 return <div className="min-h-screen bg-background text-foreground p-3 sm:p-5"><AppearanceQuickButton className="fixed top-3 right-3 z-30"/><main className="max-w-4xl mx-auto space-y-4">
   <header className="glass rounded-xl p-5 text-center"><RallyHubPublicBrand moduleName="King of the Court" pageLabel="My Result" club={data.club_brand}/><Crown className="w-8 h-8 text-yellow-400 mx-auto mt-3"/><h1 className="text-2xl font-black mt-1">{p.name}</h1><p className="text-sm text-muted-foreground mt-1">{data.session?.name}</p></header>
   <section className="grid grid-cols-2 sm:grid-cols-5 gap-2"><div className="glass rounded-xl p-3 text-center col-span-2 sm:col-span-1"><p className="text-[10px] uppercase text-muted-foreground font-bold">Final Rank</p><p className="text-3xl font-black mt-1">#{p.rank||'—'}</p></div><div className="glass rounded-xl p-3 text-center"><p className="text-[10px] uppercase text-muted-foreground font-bold">Wins</p><p className="text-2xl font-black mt-1">{p.wins||0}</p></div><div className="glass rounded-xl p-3 text-center"><p className="text-[10px] uppercase text-muted-foreground font-bold">Losses</p><p className="text-2xl font-black mt-1">{p.losses||0}</p></div><div className="glass rounded-xl p-3 text-center"><p className="text-[10px] uppercase text-muted-foreground font-bold">Point Diff</p><p className="text-2xl font-black mt-1">{Number(p.differential||0)>0?'+':''}{p.differential||0}</p></div><div className="glass rounded-xl p-3 text-center"><p className="text-[10px] uppercase text-muted-foreground font-bold">Court 1</p><p className="text-2xl font-black mt-1">{p.court1_rounds||0}</p></div></section>
   {(data.podium||[]).length>0&&<section className="glass rounded-xl p-4"><div className="flex items-center gap-2 mb-3"><Trophy className="w-4 h-4 text-yellow-400"/><h2 className="font-semibold">Podium</h2></div><div className="grid grid-cols-3 gap-2">{data.podium.map((x,i)=><div key={`${x.rank}-${x.name}`} className="rounded-lg border p-3 text-center"><div className="text-2xl">{i===0?'🥇':i===1?'🥈':'🥉'}</div><p className="font-bold text-sm mt-1">{x.name}</p><p className="text-[10px] text-muted-foreground mt-1">{x.wins}W · {x.losses}L · {x.differential>0?'+':''}{x.differential}</p></div>)}</div></section>}
   <section className="glass rounded-xl overflow-hidden"><div className="p-3 border-b"><h2 className="font-semibold">My Rounds</h2><p className="text-xs text-muted-foreground mt-0.5">Your court, partner, opponents and saved result for each round.</p></div>{(data.rounds||[]).map(r=><div key={r.round_number} className="p-3 border-b last:border-b-0"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Badge variant="outline">Round {r.round_number}</Badge><Badge variant="outline">Court {r.court}</Badge></div><Badge className={r.result==='W'?'bg-green-600':'bg-muted text-foreground'}>{r.result}</Badge></div><p className="text-sm mt-2"><b>Partner:</b> {(r.partner||[]).join(' & ')||'—'}</p><p className="text-sm mt-1"><b>Opponents:</b> {(r.opponents||[]).join(' & ')||'—'}</p><p className="text-sm mt-1"><b>Score:</b> {r.my_score}–{r.opponent_score}</p></div>)}</section>
 </main></div>;
}
