import React,{useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import {base44} from '@/api/base44Client';
import {Badge} from '@/components/ui/badge';
import {Trophy,RefreshCw,ShieldCheck} from 'lucide-react';
import RallyHubPublicBrand from '@/components/branding/RallyHubPublicBrand';

function Podium({title,rows=[]}){return <section className="rounded-2xl border bg-card p-4"><p className="text-center text-xs font-black uppercase tracking-[.18em] text-muted-foreground">{title}</p><div className="mt-3 grid grid-cols-3 gap-2">{rows.map((p,i)=><div key={p.id} className="rounded-xl border p-3 text-center"><div className="text-2xl">{i===0?'🥇':i===1?'🥈':'🥉'}</div><p className="mt-1 text-sm font-bold leading-tight">{p.display_name}</p><p className="mt-1 text-[10px] text-muted-foreground">{p.pointsFor} pts · {p.wins}W</p></div>)}</div></section>}
export default function PublicInterclubParticipantResult(){
 const {token}=useParams();const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;base44.functions.invoke('getInterclubParticipantResult',{token}).then(r=>{if(!active)return;if(r.data?.error)throw new Error(r.data.error);setData(r.data);}).catch(e=>active&&setError(e?.response?.data?.error||e?.message||'Results unavailable'));return()=>{active=false};},[token]);
 if(error)return <div className="min-h-screen bg-background text-foreground grid place-items-center p-4"><div className="max-w-md w-full rounded-2xl border bg-card p-6 text-center"><RallyHubPublicBrand moduleName="Interclub" pageLabel="Private Player Results"/><p className="mt-5 font-bold">Private results unavailable</p><p className="mt-2 text-sm text-muted-foreground">{error}</p></div></div>;
 if(!data)return <div className="min-h-screen bg-background text-foreground grid place-items-center"><RefreshCw className="animate-spin"/></div>;
 const me=data.player,stats=me.stats||{},sideName=me.side==='club_a'?data.event.clubA:data.event.clubB;
 return <div className="min-h-screen bg-background text-foreground p-4 sm:p-7"><main className="mx-auto max-w-4xl space-y-4">
  <header className="rounded-2xl border bg-card p-5 text-center"><RallyHubPublicBrand moduleName="Interclub" pageLabel="Private Player Results"/><ShieldCheck className="mx-auto mt-3 h-6 w-6 text-primary"/><p className="mt-2 text-xs font-black uppercase tracking-[.18em] text-primary">For {me.name}</p><h1 className="mt-2 text-2xl font-black">{data.event.clubA} vs {data.event.clubB}</h1><p className="mt-2 text-sm text-muted-foreground">This private page shows your own performance and saved match history.</p></header>
  <section className="rounded-2xl border bg-card p-5"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><div className="font-black">{data.event.clubA}</div><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Final</p><p className="text-4xl font-black tabular-nums">{data.event.scoreA}–{data.event.scoreB}</p></div><div className="font-black">{data.event.clubB}</div></div></section>
  <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><Trophy className="h-5 w-5 text-primary"/><h2 className="font-black">Your result · {sideName}</h2></div><div className="mt-4 grid grid-cols-2 sm:grid-cols-5 gap-2">{[['Games',stats.gamesPlayed],['Points',stats.pointsFor],['Wins',stats.wins],['Losses',stats.losses],['Diff',`${Number(stats.pointDiff||0)>0?'+':''}${stats.pointDiff||0}`]].map(([label,value])=><div key={label} className="rounded-xl bg-secondary/50 p-3 text-center"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</div></section>
  <div className="grid md:grid-cols-2 gap-4"><Podium title={`${data.event.clubA} · Top 3`} rows={data.podiums.clubA}/><Podium title={`${data.event.clubB} · Top 3`} rows={data.podiums.clubB}/></div>
  <section className="rounded-2xl border bg-card overflow-hidden"><div className="border-b p-4"><h2 className="font-black">Your rounds</h2><p className="text-xs text-muted-foreground mt-1">Only matches you played are shown here.</p></div><div className="divide-y">{data.rounds.length?data.rounds.map((r,i)=><div key={`${r.round}-${i}`} className="grid grid-cols-[70px_1fr_auto] items-center gap-3 p-4"><Badge variant="outline">Round {r.round}</Badge><span className="text-sm">Court {r.court}</span><span className="font-black tabular-nums">{r.scoreA}–{r.scoreB}</span></div>):<div className="p-6 text-center text-sm text-muted-foreground">No completed rounds recorded for this player.</div>}</div></section>
 </main></div>;
}