import React from 'react';
import { useParams } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Trophy, CheckCircle2 } from 'lucide-react';

export default function PublicClubChallengeVote(){
  const { token }=useParams();
  const [data,setData]=React.useState(null),[error,setError]=React.useState(''),[voter,setVoter]=React.useState(''),[nominee,setNominee]=React.useState(''),[code,setCode]=React.useState(''),[saving,setSaving]=React.useState(false),[done,setDone]=React.useState(false);
  const load=React.useCallback(async()=>{try{const r=await base44.functions.invoke('getPublicClubChallengeVote',{token}); if(r.data?.error)throw new Error(r.data.error);setData(r.data);setError('');}catch(e){setError(e?.response?.data?.error||e?.message||'Voting unavailable');}},[token]);
  React.useEffect(()=>{load();},[load]);
  const cast=async()=>{if(!voter||!nominee||!code.trim())return;setSaving(true);try{const r=await base44.functions.invoke('castPublicClubChallengePotVote',{token,voterParticipantId:voter,nomineeParticipantId:nominee,voterCode:code.trim()});if(r.data?.error)throw new Error(r.data.error);setDone(true);setError('');}catch(e){setError(e?.response?.data?.error||e?.message||'Vote could not be recorded');}finally{setSaving(false);}};
  if(done)return <div className="min-h-screen bg-background text-foreground grid place-items-center p-6"><div className="max-w-md text-center rounded-xl border border-border bg-card p-8"><CheckCircle2 className="w-10 h-10 text-primary mx-auto"/><h1 className="text-xl font-bold mt-3">Vote recorded</h1><p className="text-sm text-muted-foreground mt-2">Thank you. Your Player of the Tournament vote has been securely recorded.</p></div></div>;
  return <div className="min-h-screen bg-background text-foreground p-4 grid place-items-center"><div className="w-full max-w-lg rounded-xl border border-border bg-card p-5 sm:p-7 space-y-5"><div className="text-center"><Trophy className="w-8 h-8 text-primary mx-auto"/><p className="text-xs uppercase tracking-wider text-primary font-bold mt-2">Player of the Tournament</p><h1 className="text-xl font-bold mt-1">{data?`${data.event.club_a_name} vs ${data.event.club_b_name}`:'Club Challenge'}</h1></div>{error&&<div className="rounded-lg bg-destructive/10 text-destructive p-3 text-sm">{error}</div>}{data&&data.event.pot_status!=='open'&&<div className="rounded-lg bg-secondary p-4 text-sm text-center">Voting is currently <b>{data.event.pot_status}</b>.</div>}{data&&data.event.pot_status==='open'&&<><div><Label>Your name</Label><Select value={voter} onValueChange={v=>{setVoter(v);setNominee('');}}><SelectTrigger className="mt-1"><SelectValue placeholder="Select your name"/></SelectTrigger><SelectContent>{data.participants.filter(p=>p.can_vote).map(p=><SelectItem key={p.id} value={p.id}>{p.display_name}</SelectItem>)}</SelectContent></Select></div><div><Label>Your personal access code</Label><Input className="mt-1 uppercase" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={8} placeholder="8-character code"/></div><div><Label>Your Player of the Tournament</Label><Select value={nominee} onValueChange={setNominee}><SelectTrigger className="mt-1"><SelectValue placeholder="Select player"/></SelectTrigger><SelectContent>{data.participants.filter(p=>p.id!==voter).map(p=><SelectItem key={p.id} value={p.id}>{p.display_name}</SelectItem>)}</SelectContent></Select></div><Button className="w-full h-11" onClick={cast} disabled={!voter||!nominee||!code.trim()||saving}>{saving?'Recording…':'Cast Vote'}</Button><p className="text-xs text-muted-foreground text-center">One vote per participant · no self-voting · individual votes remain private.</p></>}{data?.event.junior_display_mode&&<p className="text-xs text-muted-foreground text-center">Junior privacy mode is active.</p>}</div></div>;
}