import React from 'react';
import { useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Crown, Trophy } from 'lucide-react';

export default function PublicKotcResults(){
  const {token}=useParams();
  const {data,isLoading,error}=useQuery({queryKey:['public-kotc-results',token],queryFn:async()=> (await base44.functions.invoke('kotcResultsShare',{action:'public_state',token})).data,enabled:!!token,staleTime:15000});
  if(isLoading)return <div className="min-h-screen bg-background flex items-center justify-center text-sm text-muted-foreground">Loading results…</div>;
  if(error||!data?.session)return <div className="min-h-screen bg-background flex items-center justify-center p-4"><div className="glass rounded-xl p-5 max-w-md w-full"><h1 className="font-bold">Results unavailable</h1><p className="text-sm text-muted-foreground mt-2">This results link is invalid, expired or has been revoked.</p></div></div>;
  return <div className="min-h-screen bg-background p-3 sm:p-5"><main className="max-w-3xl mx-auto space-y-4"><div className="glass rounded-xl p-5 text-center"><Crown className="w-8 h-8 text-yellow-400 mx-auto mb-2"/><h1 className="text-xl font-bold">{data.session.name}</h1><p className="text-sm text-muted-foreground">{data.completed_rounds} completed round{data.completed_rounds===1?'':'s'} · {String(data.session.status||'').replaceAll('_',' ')}</p></div><div className="glass rounded-xl overflow-hidden"><div className="p-3 border-b flex items-center gap-2"><Trophy className="w-4 h-4 text-yellow-400"/><h2 className="font-semibold">Standings</h2></div><div className="grid grid-cols-[36px_1fr_42px_42px_58px] text-[10px] uppercase text-muted-foreground p-2 border-b"><span>#</span><span>Player</span><span>W</span><span>L</span><span>Diff</span></div>{(data.standings||[]).map(s=><div key={s.id} className="grid grid-cols-[36px_1fr_42px_42px_58px] p-2 border-b last:border-b-0 text-sm"><span>{s.rank}</span><span className="font-medium">{s.name}</span><span>{s.wins}</span><span>{s.losses}</span><span>{s.differential>0?'+':''}{s.differential}</span></div>)}</div><div className="glass rounded-xl p-3 space-y-3"><h2 className="font-semibold">Round history</h2>{(data.matches||[]).map((m,i)=><div key={`${m.round_number}-${m.court}-${i}`} className="rounded-lg border p-3 text-sm"><p className="text-xs text-muted-foreground mb-1">Round {m.round_number} · Court {m.court}</p><div className="flex items-center justify-between gap-3"><span>{m.team_a.join(' & ')}</span><strong>{m.team_a_score}</strong></div><div className="flex items-center justify-between gap-3"><span>{m.team_b.join(' & ')}</span><strong>{m.team_b_score}</strong></div></div>)}</div></main></div>;
}
