import React,{useEffect,useMemo,useRef,useState} from 'react';
import { useParams } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Crown,RefreshCw,WifiOff,CheckCircle2,LockKeyhole,Pencil,X } from 'lucide-react';

function msg(e){return e?.response?.data?.error||e?.data?.error||e?.message||'Scorer link error';}
function isRateLimit(e){return /rate limit|too many requests|\b429\b/i.test(msg(e));}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function scorerInvoke(payload,attempts=3){let last;for(let i=0;i<attempts;i++){try{const r=await base44.functions.invoke('kotcScorer',payload);if(r.data?.error){const error=new Error(r.data.error);if(!isRateLimit(error)||i===attempts-1)throw error;last=error;}else return r;}catch(e){last=e;if(!isRateLimit(e)||i===attempts-1)throw e;}await wait(350*Math.pow(2,i)+Math.floor(Math.random()*120));}throw last||new Error('Scorer action failed');}
function fmt(v){const n=Math.max(0,Number(v||0));return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;}
function getClientId(){const key='rallyhub-kotc-scorer-client';let id=sessionStorage.getItem(key);if(!id){id=`scorer_${crypto.randomUUID().replaceAll('-','')}`;sessionStorage.setItem(key,id);}return id;}

function CourtScore({match,session,token,clientId,onSaved}){
 const [a,setA]=useState(match.team_a_score??''),[b,setB]=useState(match.team_b_score??''),[serving,setServing]=useState(''),[saving,setSaving]=useState(false),[claiming,setClaiming]=useState(false),[editing,setEditing]=useState(false),[locked,setLocked]=useState(match.lock_status==='mine'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[localSaved,setLocalSaved]=useState(null);
 const heartbeat=useRef(null);
 const effectiveMatch=localSaved&&Number(localSaved.revision||0)>=Number(match.revision||0)?{...match,...localSaved}:match;
 const saved=['completed','retired','abandoned','not_played'].includes(effectiveMatch.status);
 const canCorrect=saved&&!!effectiveMatch.can_correct;
 const blocked=effectiveMatch.lock_status==='other'&&!locked;
 useEffect(()=>{const mine=match.lock_status==='mine';if(editing&&locked&&!mine){setEditing(false);setError(`Court ${match.court} is now being entered by the host or another scorer.`);}if(!editing||!mine){setA(match.team_a_score??'');setB(match.team_b_score??'');setServing(match.serving_side_at_horn||'');}if(localSaved&&Number(match.revision||0)>=Number(localSaved.revision||0))setLocalSaved(null);setLocked(mine);},[match.id,match.revision,match.team_a_score,match.team_b_score,match.serving_side_at_horn,match.lock_status]);
 useEffect(()=>{if(!locked){clearInterval(heartbeat.current);heartbeat.current=null;return;}heartbeat.current=setInterval(async()=>{try{await scorerInvoke({action:'heartbeat',token,matchId:match.id,clientId},2);}catch(e){if(isRateLimit(e))return;setLocked(false);setEditing(false);setError('Your court edit lock expired. Tap Score/Edit again.');}},30000);return()=>{clearInterval(heartbeat.current);heartbeat.current=null;};},[locked,match.id,token,clientId]);
 const claim=async(forCorrection=false)=>{if(claiming)return false;setClaiming(true);setError('');setNotice('');try{await scorerInvoke({action:'claim',token,matchId:match.id,clientId},3);setLocked(true);setEditing(true);setA(match.team_a_score??'');setB(match.team_b_score??'');setServing(match.serving_side_at_horn||'');setNotice(forCorrection?`Court ${match.court} ready for correction`:`Court ${match.court} locked to you — enter the score`);return true;}catch(e){setError(isRateLimit(e)?'RallyHub is busy. Tap the score box again.':msg(e));await onSaved();return false;}finally{setClaiming(false);}};
 const changeScore=async(side,raw)=>{const value=raw.replace(/\D/g,'').slice(0,2);if(saved||blocked||saving||claiming)return;if(locked&&editing){if(side==='A')setA(value);else setB(value);return;}if(value==='')return;const claimed=await claim(false);if(claimed){if(side==='A')setA(value);else setB(value);}};
 const release=async()=>{try{await scorerInvoke({action:'release',token,matchId:match.id,clientId},2);}catch{}setLocked(false);setEditing(false);setA(match.team_a_score??'');setB(match.team_b_score??'');setNotice('');await onSaved();};
 const submit=async()=>{if(!locked)return;if(session.scoring_mode==='timed'&&a!==''&&b!==''&&Number(a)===Number(b)&&!serving){setError('Choose which team was serving at the horn before saving a tied timed game.');return;}setSaving(true);setError('');setNotice('');try{const r=await scorerInvoke({action:saved?'correct':'save',token,matchId:match.id,clientId,expectedRevision:effectiveMatch.revision,teamAScore:Number(a),teamBScore:Number(b),servingSideAtHorn:Number(a)===Number(b)?serving:undefined},3);const savedMatch={...(r.data?.match||effectiveMatch),can_correct:true,lock_status:'free'};setLocalSaved(savedMatch);setLocked(false);setEditing(false);setNotice(r.data?.message||'Score saved');onSaved?.();}catch(e){setError(isRateLimit(e)?'RallyHub is busy. Your score has not been confirmed yet — tap Save Result again.':msg(e));onSaved?.();}finally{setSaving(false);}};
 const canInput=editing&&locked&&!blocked;
 const canAttemptInput=!saved&&!blocked&&!saving&&!claiming;
 return <div className={`rounded-xl border bg-card p-4 space-y-3 ${locked?'ring-2 ring-primary/30 border-primary/50':''}`} data-testid={`scorer-court-${match.court}`}>
  <div className="flex items-center justify-between"><div className="flex items-center gap-2">{match.court===1&&<Crown className="w-4 h-4 text-yellow-400"/>}<b>Court {match.court}</b></div><Badge variant="outline">{blocked?'LOCKED':saved?'SAVED':locked?'EDITING':String(match.status||'').toUpperCase()}</Badge></div>
  {blocked&&<div className="rounded-lg border border-amber-400/30 bg-amber-500/10 p-2 text-xs text-amber-600 flex gap-2 items-center"><LockKeyhole className="w-4 h-4 shrink-0"/>The host or another scorer is entering this court. It will unlock automatically when they save, cancel or their lock expires.</div>}
  <div className="grid grid-cols-[1fr_84px] gap-3 items-center"><span>{match.team_a.join(' & ')}</span><Input type="text" inputMode="numeric" pattern="[0-9]*" maxLength={2} className="h-12 text-center text-lg font-bold" value={a} disabled={saving||claiming||(!canInput&&!canAttemptInput)} onChange={e=>changeScore('A',e.target.value)}/></div>
  <div className="grid grid-cols-[1fr_84px] gap-3 items-center"><span>{match.team_b.join(' & ')}</span><Input type="text" inputMode="numeric" pattern="[0-9]*" maxLength={2} className="h-12 text-center text-lg font-bold" value={b} disabled={saving||claiming||(!canInput&&!canAttemptInput)} onChange={e=>changeScore('B',e.target.value)}/></div>
  {canInput&&session.scoring_mode==='timed'&&a!==''&&b!==''&&Number(a)===Number(b)&&<div className="rounded-lg border border-amber-400/30 bg-amber-500/10 p-2"><p className="text-xs font-semibold mb-1">Tie at the horn — who was serving?</p><Select value={serving} onValueChange={setServing}><SelectTrigger><SelectValue placeholder="Choose serving team"/></SelectTrigger><SelectContent><SelectItem value="A">Team A serving at horn</SelectItem><SelectItem value="B">Team B serving at horn</SelectItem></SelectContent></Select></div>}
  {notice&&<div className="rounded-lg bg-green-500/10 border border-green-500/20 p-2 text-sm font-semibold text-green-600 flex items-center justify-center gap-2"><CheckCircle2 className="w-4 h-4"/>{notice}</div>}
  {saved&&!editing&&<div className="rounded-lg bg-green-500/10 border border-green-500/20 p-2 text-center text-sm font-semibold text-green-600">✓ Score saved: {effectiveMatch.team_a_score}–{effectiveMatch.team_b_score}</div>}
  {!saved&&!editing&&!blocked&&<div className="rounded-lg border border-primary/20 bg-primary/5 p-2 text-center text-xs text-muted-foreground">Start typing in either score box to claim this court.</div>}
  {canCorrect&&!editing&&!blocked&&<Button variant="outline" className="w-full min-h-11" onClick={()=>claim(true)}><Pencil className="w-4 h-4 mr-2"/>Undo / Update Score{effectiveMatch.correction_seconds_remaining?` · ${effectiveMatch.correction_seconds_remaining}s`:''}</Button>}
  {saved&&!editing&&!canCorrect&&<div className="rounded-lg border bg-muted/40 p-2 text-center text-xs text-muted-foreground">Result already entered. Only the scorer device that saved it, or the host, can update this score.</div>}
  {editing&&<div className="grid grid-cols-2 gap-2"><Button className="min-h-12" onClick={submit} disabled={saving||a===''||b===''||(session.scoring_mode==='timed'&&Number(a)===Number(b)&&!serving)}>{saving?'Saving…':saved?'Save Updated Score':'Save Result'}</Button><Button variant="outline" className="min-h-12" onClick={release} disabled={saving}><X className="w-4 h-4 mr-1"/>Cancel</Button></div>}
  {error&&<div className="rounded-lg border border-destructive/30 bg-destructive/10 p-2 text-xs text-destructive">{error}</div>}
 </div>;
}

export default function PublicKotcScorer(){
 const {token}=useParams();const clientId=useMemo(()=>getClientId(),[]);const [data,setData]=useState(null),[error,setError]=useState(''),[offline,setOffline]=useState(false),[now,setNow]=useState(Date.now()),[refreshing,setRefreshing]=useState(false);
 const dataRef=useRef(null);useEffect(()=>{dataRef.current=data;},[data]);
 const load=async({manual=false}={})=>{if(manual)setRefreshing(true);try{const r=await scorerInvoke({action:'state',token,clientId},2);setData(r.data);setError('');setOffline(false);return r.data;}catch(e){if(isRateLimit(e)&&dataRef.current)return dataRef.current;if(dataRef.current)setOffline(true);else setError(msg(e));return null;}finally{if(manual)setRefreshing(false);}};
 useEffect(()=>{load();const t=setInterval(()=>setNow(Date.now()),1000);const off=()=>setOffline(true),on=()=>{setOffline(false);load();};window.addEventListener('offline',off);window.addEventListener('online',on);window.addEventListener('focus',load);return()=>{clearInterval(t);window.removeEventListener('offline',off);window.removeEventListener('online',on);window.removeEventListener('focus',load);};},[token]);
 if(error&&!data)return <div className="min-h-screen bg-background grid place-items-center p-4"><div className="glass rounded-xl p-5 max-w-md"><h1 className="font-bold">Scorer link unavailable</h1><p className="text-sm text-muted-foreground mt-2">{error}</p></div></div>;
 if(!data)return <div className="min-h-screen bg-background grid place-items-center"><RefreshCw className="animate-spin"/></div>;
 const t=data.timer||{};const remaining=t.running&&t.deadlineAt?Math.max(0,Math.ceil((Date.parse(t.deadlineAt)-now)/1000)):Number(t.remainingSeconds||0);const live=data.session.status==='in_progress'&&data.round?.status==='started';const allSaved=(data.matches||[]).length>0&&(data.matches||[]).every(m=>['completed','retired','abandoned','not_played'].includes(m.status));
 return <div className="min-h-screen bg-background p-3 sm:p-5"><main className="max-w-4xl mx-auto space-y-4">
  {offline&&<div className="rounded-lg bg-yellow-500 text-black p-3 text-center font-semibold"><WifiOff className="inline w-4 h-4 mr-2"/>Connection lost — do not submit until reconnected.</div>}
  <header className="glass rounded-xl p-4 text-center"><p className="text-[10px] uppercase tracking-[.2em] text-primary font-bold">KOTC Scorer</p><h1 className="text-xl font-bold mt-1">{data.session.name}</h1><div className="flex gap-2 justify-center mt-3"><Badge variant="outline">Round {data.session.current_round_number||'-'}</Badge><Badge variant="outline">{live?'LIVE':String(data.round?.status||data.session.status).replaceAll('_',' ').toUpperCase()}</Badge>{data.session.scoring_mode==='timed'&&<Badge className="tabular-nums">{fmt(remaining)}</Badge>}</div><p className="text-xs text-muted-foreground mt-3">Scorers can enter and correct current-round results only. The host controls players, bench, pairs, timer and round progression.</p><Button data-testid="scorer-refresh" variant="outline" className="mt-3 min-h-11" onClick={()=>load({manual:true})} disabled={refreshing}><RefreshCw className={`w-4 h-4 mr-2 ${refreshing?'animate-spin':''}`}/>{refreshing?'Refreshing…':'Refresh Round'}</Button><p className="text-[10px] text-muted-foreground mt-2">No background polling. Refresh when the host announces a new round or if another scorer changes a court.</p></header>
  {allSaved&&live&&<div className="rounded-xl border border-green-500/30 bg-green-500/10 p-4 text-center"><p className="font-bold text-green-600">✓ All court scores saved</p><p className="text-xs text-muted-foreground mt-1">Check your score now if needed. The session is waiting for the host to review and prepare the next round.</p></div>}
  {data.bench?.length>0&&<div className="rounded-xl border border-amber-400/30 bg-amber-500/10 p-3"><p className="text-[10px] uppercase text-amber-500 font-bold">Bench</p><p className="text-sm mt-1">{data.bench.join(' · ')}</p></div>}
  {!live&&<div className="glass rounded-xl p-4 text-center text-sm text-muted-foreground">Waiting for the host to start the round. This page updates automatically.</div>}
  <div className="grid lg:grid-cols-2 gap-4">{(data.matches||[]).map(m=><CourtScore key={m.id} match={m} session={data.session} token={token} clientId={clientId} onSaved={load}/>)}</div>
 </main></div>;
}