import React, { useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, CheckCircle2, Eye, ImagePlus, Loader2, MapPin, Plus, Save } from 'lucide-react';
import EventMediaEditor from '@/components/events/EventMediaEditor';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import PageHeader from '@/components/shared/PageHeader';
import { toast } from 'sonner';

const blank = { name:'', category:'other', date:'', start:'', end:'', venue_id:'', location:'', description:'', internal:'', contact:'', registration:'', image:'', imageX:50, imageY:50, imageZoom:1, imageOriginal:'', imageSourceType:'', member:true, public:false };
const labels={tournament:'Tournament',coaching:'Coaching',holiday:'Holiday',other:'Other'};

function EventPreview({draft}){
  return <div className="overflow-hidden rounded-2xl border bg-card shadow-sm">
    {draft.image ? <div className="mx-auto aspect-[1/1.4142] w-full max-w-[430px] overflow-hidden bg-secondary"><img src={draft.image} alt="Event poster preview" className="h-full w-full object-cover" style={{objectPosition:`${draft.imageX}% ${draft.imageY}%`,transform:`scale(${draft.imageZoom})`,transformOrigin:`${draft.imageX}% ${draft.imageY}%`}}/></div> : <div className="flex h-48 items-center justify-center bg-secondary text-muted-foreground"><ImagePlus className="mr-2 h-5 w-5"/>Event image</div>}
    <div className="p-5 space-y-3">
      <div className="flex items-center justify-between gap-3"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">{labels[draft.category]}</span><span className="text-xs text-muted-foreground">Member preview</span></div>
      <h2 className="text-2xl font-black">{draft.name || 'Event name'}</h2>
      <div className="space-y-1 text-sm text-muted-foreground"><p className="flex gap-2"><CalendarDays className="h-4 w-4"/>{draft.date || 'Date'} {draft.start && `· ${draft.start}`}{draft.end && `–${draft.end}`}</p><p className="flex gap-2"><MapPin className="h-4 w-4"/>{draft.location || 'Venue'}</p></div>
      {draft.description && <p className="whitespace-pre-wrap text-sm leading-6">{draft.description}</p>}
      {draft.internal && <div className="rounded-xl border border-primary/20 bg-primary/5 p-3"><p className="text-xs font-black uppercase tracking-wide text-primary">Member information</p><p className="mt-1 whitespace-pre-wrap text-sm">{draft.internal}</p></div>}
    </div>
  </div>
}

export default function TenantEvents(){
 const qc=useQueryClient(); const [draft,setDraft]=useState(blank); const [preview,setPreview]=useState(false); const [editingId,setEditingId]=useState(null);
 const {data:user}=useQuery({queryKey:['current-user'],queryFn:()=>base44.auth.me()});
 const canManage=user?.role==='admin'||user?.active_club_role==='club_admin'||user?.approval_status==='approved';
 const {data:venues=[]}=useQuery({queryKey:['event-venues',user?.active_tenant_id,user?.active_club_id],queryFn:()=>base44.entities.Venue.filter({tenant_id:user.active_tenant_id,club_id:user.active_club_id,status:'active'},'name',100),enabled:!!user?.active_tenant_id&&!!user?.active_club_id});
 const {data:events=[]}=useQuery({queryKey:['tenant-events',user?.active_tenant_id,user?.active_club_id],queryFn:()=>base44.entities.Tournament.filter({tenant_id:user.active_tenant_id,host_club_id:user.active_club_id},'-start_date',100),enabled:!!user?.active_tenant_id&&!!user?.active_club_id});
 const published=useMemo(()=>events.filter(e=>e.event_member_visible||e.event_publish_status==='published'),[events]);
 const editEvent=(e)=>{setEditingId(e.id);setDraft({...blank,name:e.name||'',category:e.event_category||'social',date:e.start_date||'',start:e.event_start_time||'',end:e.event_end_time||'',venue_id:e.venue_id||'',location:e.location||'',description:e.description||'',internal:e.event_internal_info||'',contact:e.event_contact||'',registration:e.event_registration_url||'',image:e.event_image_url||'',member:!!e.event_member_visible,public:!!e.event_public_visible});setPreview(false);window.scrollTo({top:0,behavior:'smooth'})};
 const save=useMutation({mutationFn:async(publish)=>{if(!draft.name||!draft.date)throw new Error('Event name and date are required'); if(!user?.active_tenant_id||!user?.active_club_id) throw new Error('No active club selected. Return to the club dashboard and try again.'); const venue=venues.find(v=>v.id===draft.venue_id); const payload={name:draft.name,format:'Club Challenge',status:'Draft',start_date:draft.date,end_date:draft.date,location:venue?.name||draft.location,venue_id:draft.venue_id||undefined,description:draft.description,tenant_id:user.active_tenant_id,host_club_id:user.active_club_id,event_category:draft.category,event_start_time:draft.start,event_end_time:draft.end,event_image_url:draft.image,event_image_position_x:draft.imageX,event_image_position_y:draft.imageY,event_image_zoom:draft.imageZoom,event_image_original_url:draft.imageOriginal,event_image_source_type:draft.imageSourceType,event_internal_info:draft.internal,event_contact:draft.contact,event_registration_url:draft.registration,event_member_visible:publish?draft.member:false,event_public_visible:publish?draft.public:false,event_publish_status:publish?'published':'draft',...(publish?{event_published_at:new Date().toISOString()}:{})}; return editingId?base44.entities.Tournament.update(editingId,payload):base44.entities.Tournament.create(payload)},onSuccess:async(_,publish)=>{await qc.invalidateQueries({queryKey:['tenant-events']}); toast.success(editingId?'Event changes saved':(publish?'Event published to members':'Draft saved')); setDraft(blank); setEditingId(null); setPreview(false)},onError:e=>toast.error(e.message||'Could not save event')});
 if(!canManage) return <div className="p-6">You do not have permission to manage events.</div>;
 return <div className="space-y-6"><PageHeader title="Events" description="Create once, preview it, then publish it to your members."/>
   <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
    <div className="glass rounded-xl p-5 space-y-5">
      <div className="flex items-center gap-2"><Plus className="h-5 w-5 text-primary"/><h2 className="font-bold">{editingId?'Edit event':'Create event'}</h2></div>
      <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Event name<Input className="mt-1" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="text-sm font-semibold">Category<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-semibold">Date<Input type="date" className="mt-1" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="text-sm font-semibold">Starts<Input type="time" className="mt-1" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label className="text-sm font-semibold">Ends<Input type="time" className="mt-1" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label><label className="text-sm font-semibold sm:col-span-2">Venue<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.venue_id} onChange={e=>{const v=venues.find(x=>x.id===e.target.value);setDraft({...draft,venue_id:e.target.value,location:v?.name||''})}}><option value="">Choose venue</option>{venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div>
      <label className="block text-sm font-semibold">Event description<textarea className="mt-1 min-h-28 w-full rounded-md border bg-background p-3 font-normal" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
      <label className="block text-sm font-semibold">Member-only information<textarea className="mt-1 min-h-24 w-full rounded-md border bg-background p-3 font-normal" placeholder="Fees, member instructions or other information that must not appear publicly." value={draft.internal} onChange={e=>setDraft({...draft,internal:e.target.value})}/></label>
      <EventMediaEditor value={draft.image} position={{x:draft.imageX,y:draft.imageY,zoom:draft.imageZoom}} onChange={media=>setDraft(d=>({...d,image:media.url,imageX:media.x,imageY:media.y,imageZoom:media.zoom,imageOriginal:media.originalUrl ?? d.imageOriginal,imageSourceType:media.sourceType ?? d.imageSourceType}))}/>
      <div className="rounded-xl border p-4 space-y-3"><p className="text-sm font-bold">Audience</p><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.member} onChange={e=>setDraft({...draft,member:e.target.checked})}/>Show to club members and in their calendar</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.public} onChange={e=>setDraft({...draft,public:e.target.checked})}/>Publish on RallyHub public Events</label></div>
      <div className="flex flex-col gap-2 sm:flex-row"><Button type="button" variant="outline" disabled={save.isPending} onClick={()=>save.mutate(false)}>{save.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Save className="mr-2 h-4 w-4"/>}{save.isPending?'Saving…':editingId?'Save changes':'Save draft'}</Button><Button type="button" variant="outline" disabled={save.isPending} onClick={()=>setPreview(true)}><Eye className="mr-2 h-4 w-4"/>Preview</Button><Button type="button" disabled={save.isPending||!draft.member} onClick={()=>save.mutate(true)}>{save.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<CheckCircle2 className="mr-2 h-4 w-4"/>}{save.isPending?'Publishing…':'Publish to members'}</Button></div>
      {save.isError&&<div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive"><strong>Could not save this event.</strong> {save.error?.message||'Please try again.'}</div>}
    </div>
    <div>{preview?<EventPreview draft={draft}/>:<div className="glass rounded-xl p-5"><h2 className="font-bold">Published member events</h2><div className="mt-4 space-y-3">{published.length===0?<p className="text-sm text-muted-foreground">No member events published yet.</p>:published.map(e=><div key={e.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{e.name}</p><p className="mt-1 text-xs text-muted-foreground">{e.start_date} {e.event_start_time&&`· ${e.event_start_time}`} · {e.location||'Venue TBC'}</p></div><Button type="button" size="sm" variant="outline" onClick={()=>editEvent(e)}>Edit</Button></div></div>)}</div></div>}</div>
   </div>
 </div>;
}