import React, { useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, CheckCircle2, Eye, Loader2, MapPin, Plus, Save, Trash2, Users, X } from 'lucide-react';
import EventMediaEditor from '@/components/events/EventMediaEditor';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import PageHeader from '@/components/shared/PageHeader';
import { toast } from 'sonner';
import { EVENT_AGE_GROUPS, EVENT_DISCIPLINES, EVENT_LEVELS, EVENT_TYPES, registrationState, slugifyEvent } from '@/lib/event-utils';

const blank = {
  name:'', category:'other', date:'', endDate:'', start:'', end:'', venue_id:'', location:'', county:'', country:'Ireland', setting:'',
  summary:'', description:'', internal:'', contact:'', registrationMode:'external', registration:'', regOpen:'', regClose:'', feeText:'', capacity:'', waitlist:false,
  levels:[], ageGroups:[], disciplines:[], eligibility:'', playerInfo:'', feesCancellation:'', schedule:[], sourceUrl:'', mapUrl:'', latitude:'', longitude:'',
  image:'', imageX:50, imageY:50, imageZoom:1, cardX:50, cardY:50, cardZoom:1, imageOriginal:'', imageSourceType:'',
  member:true, public:false, featured:false, featuredPublic:false, verifiedOrganiser:false,
};
const typeLabels=Object.fromEntries(EVENT_TYPES.filter(([key])=>key!=='all'));
const dateTimeLocal=value=>{if(!value)return '';const d=new Date(value);if(Number.isNaN(d.getTime()))return '';const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`};
const toIso=value=>{if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString()};
const numberOrNull=value=>value===''||value===null||value===undefined?null:Number(value);
const eventSort=(a,b)=>(a.start_date||'9999-12-31').localeCompare(b.start_date||'9999-12-31');

function TogglePills({values,selected,onChange}){
  const set=new Set(selected||[]);
  return <div className="flex flex-wrap gap-2">{values.map(value=><button key={value} type="button" onClick={()=>onChange(set.has(value)?selected.filter(v=>v!==value):[...selected,value])} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${set.has(value)?'border-primary bg-primary/10 text-primary':'border-border bg-background text-muted-foreground'}`}>{value}</button>)}</div>;
}

function EventPreview({draft,mode,onClose,hostName}){
  const image=draft.image;
  const publicCard=mode==='public-card';
  const member=mode==='member';
  if(publicCard)return <div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="relative aspect-[16/7] overflow-hidden bg-secondary">{image?<img src={image} alt="Event card preview" className="h-full w-full object-cover" style={{objectPosition:`${draft.cardX}% ${draft.cardY}%`,transform:`scale(${draft.cardZoom})`,transformOrigin:`${draft.cardX}% ${draft.cardY}%`}}/>:<div className="flex h-full items-center justify-center text-muted-foreground">Event artwork</div>}<span className="absolute left-3 top-3 rounded-full bg-primary px-2.5 py-1 text-[10px] font-black text-primary-foreground">PREVIEW</span></div><div className="space-y-3 p-5"><h2 className="text-xl font-black">{draft.name||'Event name'}</h2><p className="text-sm font-semibold">{draft.date||'Date'}{draft.start?` · ${draft.start}`:''}</p><p className="flex gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4"/>{draft.location||'Venue'}</p><p className="text-xs text-muted-foreground">Hosted by <strong className="text-foreground">{hostName||'Your club'}</strong></p><div className="grid grid-cols-2 gap-2"><Button>View event</Button><Button variant="outline">{draft.registrationMode==='none'?'Details':'Register'}</Button></div><Button variant="ghost" className="w-full" onClick={onClose}>Back to editor</Button></div></div>;

  return <div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="grid md:grid-cols-[42%_58%]">{image?<div className="flex min-h-64 max-h-[620px] items-center justify-center overflow-hidden bg-secondary"><img src={image} alt="Event poster preview" className="block max-h-[620px] w-full object-contain" style={{objectPosition:`${draft.imageX}% ${draft.imageY}%`,transform:`scale(${draft.imageZoom})`,transformOrigin:`${draft.imageX}% ${draft.imageY}%`}}/></div>:<div className="flex min-h-64 items-center justify-center bg-secondary text-muted-foreground">Full artwork</div>}<div className="space-y-4 p-5"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">{typeLabels[draft.category]||'Event'}</span><span className="text-xs text-muted-foreground">{member?'Member preview':'Public detail preview'}</span></div><h2 className="text-2xl font-black">{draft.name||'Event name'}</h2><div className="space-y-1 text-sm text-muted-foreground"><p className="flex gap-2"><CalendarDays className="h-4 w-4"/>{draft.date||'Date'}{draft.endDate&&draft.endDate!==draft.date?` – ${draft.endDate}`:''}{draft.start?` · ${draft.start}`:''}{draft.end?`–${draft.end}`:''}</p><p className="flex gap-2"><MapPin className="h-4 w-4"/>{draft.location||'Venue'}</p></div>{draft.summary&&<p className="text-sm leading-6">{draft.summary}</p>}{member&&draft.internal&&<div className="rounded-xl border border-primary/20 bg-primary/5 p-3"><p className="text-xs font-black uppercase tracking-wide text-primary">Member information</p><p className="mt-1 whitespace-pre-wrap text-sm">{draft.internal}</p></div>}<div className="grid grid-cols-2 gap-2"><Button>Register / Book</Button><Button variant="outline">Save event</Button></div><Button variant="ghost" className="w-full" onClick={onClose}>Back to editor</Button></div></div></div>;
}

export default function TenantEvents({directoryListingSlug='', embedded=false}){
  const directoryMode=!!directoryListingSlug;
  const freshBlank=()=>directoryMode?{...blank,member:false,public:true}:({...blank});
  const qc=useQueryClient();
  const [draft,setDraft]=useState(freshBlank);
  const [preview,setPreview]=useState(null);
  const [editingId,setEditingId]=useState(null);
  const [showOlder,setShowOlder]=useState(false);
  const [adminHostClubId,setAdminHostClubId]=useState('');
  const [saveState,setSaveState]=useState('');
  const {data:user}=useQuery({queryKey:['current-user'],queryFn:()=>base44.auth.me()});
  const isAdmin=user?.role==='admin';
  const {data:directoryContext,isLoading:directoryLoading,error:directoryError}=useQuery({queryKey:['directory-event-context',directoryListingSlug],queryFn:async()=>{const res=await base44.functions.invoke('directoryEvents',{action:'list',listingSlug:directoryListingSlug});if(res.data?.error)throw new Error(res.data.error);return res.data},enabled:directoryMode,staleTime:15000});
  const canManage=directoryMode?!!directoryContext?.canManage:(isAdmin||user?.active_club_role==='club_admin'||user?.approval_status==='approved');
  const {data:adminClubs=[]}=useQuery({queryKey:['admin-event-host-clubs'],queryFn:()=>base44.entities.Club.filter({status:'active'},'name',500),enabled:isAdmin&&!directoryMode,staleTime:30000});
  const directoryHostClubId=directoryContext?.host?.id||'';
  const directoryTenantId=directoryContext?.tenant?.id||'';
  const effectiveHostClubId=directoryMode?directoryHostClubId:(isAdmin?(adminHostClubId||user?.active_club_id||''):(user?.active_club_id||''));
  const selectedAdminHost=!directoryMode&&isAdmin?adminClubs.find(c=>c.id===effectiveHostClubId):null;
  const effectiveTenantId=directoryMode?directoryTenantId:(isAdmin?(selectedAdminHost?.tenant_id||(effectiveHostClubId===user?.active_club_id?user?.active_tenant_id:'')||''):(user?.active_tenant_id||''));
  const hostName=directoryMode?(directoryContext?.host?.name||directoryContext?.listing?.name):(isAdmin?selectedAdminHost?.name:user?.active_club_name);
  const {data:tenantVenues=[]}=useQuery({queryKey:['event-venues',effectiveTenantId,effectiveHostClubId],queryFn:()=>base44.entities.Venue.filter({tenant_id:effectiveTenantId,club_id:effectiveHostClubId,status:'active'},'name',100),enabled:!directoryMode&&!!effectiveTenantId&&!!effectiveHostClubId});
  const {data:tenantEvents=[]}=useQuery({queryKey:['tenant-events',effectiveTenantId,effectiveHostClubId],queryFn:()=>base44.entities.Tournament.filter({tenant_id:effectiveTenantId,host_club_id:effectiveHostClubId,status:{$ne:'Archived'}},'start_date',100),enabled:!directoryMode&&!!effectiveTenantId&&!!effectiveHostClubId,staleTime:30000});
  const venues=directoryMode?(directoryContext?.venues||[]):tenantVenues;
  const events=directoryMode?(directoryContext?.events||[]):tenantEvents;
  const {data:sharedData=[]}=useQuery({queryKey:['club-shared-public-events',effectiveTenantId,effectiveHostClubId],queryFn:async()=>{const payload={action:'club_shared'};if(isAdmin){payload.clubId=effectiveHostClubId;payload.tenantId=effectiveTenantId}const res=await base44.functions.invoke('eventEngagement',payload);return res.data?.items||[]},enabled:!directoryMode&&!!effectiveTenantId&&!!effectiveHostClubId,staleTime:30000});
  const today=new Date().toISOString().slice(0,10);
  const currentEvents=useMemo(()=>events.filter(e=>e.status!=='Archived'&&(e.end_date||e.start_date||'')>=today).sort(eventSort),[events,today]);
  const olderEvents=useMemo(()=>events.filter(e=>e.status!=='Archived'&&(e.end_date||e.start_date||'')<today).sort((a,b)=>(b.start_date||'').localeCompare(a.start_date||'')),[events,today]);
  const published=useMemo(()=>currentEvents.filter(e=>e.event_member_visible||e.event_public_visible||e.event_publish_status==='published'),[currentEvents]);
  const drafts=useMemo(()=>currentEvents.filter(e=>e.event_publish_status!=='published'&&!e.event_member_visible&&!e.event_public_visible),[currentEvents]);
  const visibleDrafts=showOlder?drafts:drafts.slice(0,3);
  const visiblePublished=showOlder?published:published.slice(0,5);

  const resetEditor=()=>{setEditingId(null);setDraft(freshBlank());setPreview(null);setSaveState('')};
  const removeEvent=async(e)=>{try{if(!window.confirm(`Delete “${e.name}”? This cannot be undone.`))return;if(directoryMode){const res=await base44.functions.invoke('directoryEvents',{action:'delete',listingSlug:directoryListingSlug,eventId:e.id});if(res.data?.error)throw new Error(res.data.error);await qc.invalidateQueries({queryKey:['directory-event-context',directoryListingSlug]})}else{const linkedInterclub=await base44.entities.ClubChallengeEvent.filter({tournament_id:e.id},'-updated_date',1).catch(()=>[]);if(linkedInterclub.length){toast.error('This calendar item is the live RallyHub Interclub competition. Archive it from the Interclub control centre instead so its teams, registrations and results remain connected.');return}await base44.entities.Tournament.delete(e.id);await qc.invalidateQueries({queryKey:['tenant-events']})}if(editingId===e.id)resetEditor();toast.success('Event deleted')}catch(err){toast.error(err?.message||'Could not delete event')}};
  const editEvent=e=>{if(!directoryMode&&isAdmin&&e.host_club_id)setAdminHostClubId(e.host_club_id);setEditingId(e.id);setDraft({...freshBlank(),name:e.name||'',category:e.event_category||'other',date:e.start_date||'',endDate:e.end_date||e.start_date||'',start:e.event_start_time||'',end:e.event_end_time||'',venue_id:e.venue_id||'',location:e.location||'',county:e.event_county||'',country:e.event_country||'Ireland',setting:e.event_indoor_outdoor||'',summary:e.event_public_summary||'',description:e.description||'',internal:directoryMode?'':(e.event_internal_info||''),contact:e.event_contact||'',registrationMode:e.event_registration_mode||(e.event_registration_url?'external':'none'),registration:e.event_registration_url||'',regOpen:dateTimeLocal(e.event_registration_open_at),regClose:dateTimeLocal(e.event_registration_close_at),feeText:e.event_fee_text||'',capacity:e.event_capacity??'',waitlist:!!e.event_waitlist_enabled,levels:e.event_levels||[],ageGroups:e.event_age_groups||[],disciplines:e.event_disciplines||[],eligibility:e.event_eligibility||'',playerInfo:e.event_player_info||'',feesCancellation:e.event_fees_cancellation||'',schedule:e.event_schedule||[],sourceUrl:e.event_source_url||'',mapUrl:e.event_map_url||'',latitude:e.event_latitude??'',longitude:e.event_longitude??'',image:e.event_image_url||'',imageX:Number(e.event_image_position_x??50),imageY:Number(e.event_image_position_y??50),imageZoom:Number(e.event_image_zoom??1),cardX:Number(e.event_card_position_x??50),cardY:Number(e.event_card_position_y??50),cardZoom:Number(e.event_card_zoom??1),imageOriginal:e.event_image_original_url||e.event_image_url||'',imageSourceType:e.event_image_source_type||'',member:directoryMode?false:!!e.event_member_visible,public:!!e.event_public_visible,featured:directoryMode?false:!!e.event_featured_member,featuredPublic:!!e.event_featured_public,verifiedOrganiser:!!e.event_verified_organiser});setPreview(null);setSaveState('');window.scrollTo({top:0,behavior:'smooth'})};

  const save=useMutation({mutationFn:async(mode)=>{
    if(!draft.name||!draft.date)throw new Error('Event name and start date are required.');
    if(!effectiveTenantId||!effectiveHostClubId)throw new Error('Choose the event host / organisation first.');
    if(mode!=='draft'&&!draft.member&&!draft.public)throw new Error('Choose at least one audience before publishing.');
    if(draft.registrationMode==='external'&&!draft.registration)throw new Error('Add the external registration link or choose a different registration method.');
    const venue=venues.find(v=>v.id===draft.venue_id);
    const existing=editingId?events.find(e=>e.id===editingId):null;
    const payload={
      name:draft.name,format:existing?.format||'Event',status:existing?.status||'Draft',start_date:draft.date,end_date:draft.endDate||draft.date,location:venue?.name||draft.location,venue_id:draft.venue_id||undefined,description:draft.description,
      tenant_id:effectiveTenantId,host_club_id:effectiveHostClubId,event_category:draft.category,event_slug:existing?.event_slug||slugifyEvent(draft.name),event_start_time:draft.start,event_end_time:draft.end,
      event_image_url:draft.image,event_image_position_x:draft.imageX,event_image_position_y:draft.imageY,event_image_zoom:draft.imageZoom,event_card_image_url:draft.image,event_card_position_x:draft.cardX,event_card_position_y:draft.cardY,event_card_zoom:draft.cardZoom,event_image_original_url:draft.imageOriginal,event_image_source_type:draft.imageSourceType,
      event_public_summary:draft.summary,event_internal_info:draft.internal,event_contact:draft.contact,event_registration_mode:draft.registrationMode,event_registration_url:draft.registrationMode==='external'?draft.registration:'',event_registration_open_at:toIso(draft.regOpen),event_registration_close_at:toIso(draft.regClose),event_fee_text:draft.feeText,event_capacity:numberOrNull(draft.capacity),event_waitlist_enabled:!!draft.waitlist,
      event_county:draft.county,event_country:draft.country,event_indoor_outdoor:draft.setting,event_levels:draft.levels,event_age_groups:draft.ageGroups,event_disciplines:draft.disciplines,event_schedule:draft.schedule,event_eligibility:draft.eligibility,event_player_info:draft.playerInfo,event_fees_cancellation:draft.feesCancellation,event_source_url:draft.sourceUrl,event_map_url:draft.mapUrl,event_latitude:numberOrNull(draft.latitude),event_longitude:numberOrNull(draft.longitude),
      event_member_visible:mode==='draft'?false:!!draft.member,event_public_visible:mode==='draft'?false:!!draft.public,event_featured_member:!!draft.featured,event_featured_public:isAdmin&&!!draft.featuredPublic,event_verified_organiser:isAdmin?!!draft.verifiedOrganiser:existing?.event_verified_organiser===true,event_publish_status:mode==='draft'?'draft':'published',...(mode!=='draft'?{event_published_at:existing?.event_published_at||new Date().toISOString()}:{})
    };
    if(directoryMode){const res=await base44.functions.invoke('directoryEvents',{action:'save',listingSlug:directoryListingSlug,eventId:editingId||'',mode,event:payload});if(res.data?.error)throw new Error(res.data.error);const result=res.data?.event;return {result,id:result?.id||editingId,mode}}
    const result=editingId?await base44.entities.Tournament.update(editingId,payload):await base44.entities.Tournament.create(payload);
    return {result,id:editingId||result?.id||result?.data?.id,mode};
  },onMutate:mode=>setSaveState(mode==='draft'?'Saving draft…':'Publishing…'),onSuccess:async(data)=>{if(directoryMode)await qc.invalidateQueries({queryKey:['directory-event-context',directoryListingSlug]});else await qc.invalidateQueries({queryKey:['tenant-events']});if(data?.id)setEditingId(data.id);setSaveState(data.mode==='draft'?'Saved ✓':'Published ✓');toast.success(data.mode==='draft'?'Draft saved':'Event published');setPreview(null)},onError:e=>{setSaveState('Could not save');toast.error(e.message||'Could not save event')}});

  const removeScheduleItem=index=>setDraft(d=>({...d,schedule:d.schedule.filter((_,i)=>i!==index)}));
  const updateSchedule=(index,key,value)=>setDraft(d=>({...d,schedule:d.schedule.map((row,i)=>i===index?{...row,[key]:value}:row)}));
  const unshare=async eventId=>{try{const payload={action:'unshare_from_club',eventId};if(isAdmin){payload.clubId=effectiveHostClubId;payload.tenantId=effectiveTenantId}const res=await base44.functions.invoke('eventEngagement',payload);if(res.data?.error)throw new Error(res.data.error);await qc.invalidateQueries({queryKey:['club-shared-public-events']});toast.success('Removed from your club calendar')}catch(e){toast.error(e?.message||'Could not remove shared event')}};

  if(directoryMode&&directoryLoading)return <div className="p-6 text-sm text-muted-foreground">Loading event manager…</div>;
  if(directoryMode&&directoryError)return <div className="p-6 text-sm text-destructive">{directoryError.message||'Could not load event manager.'}</div>;
  if(!canManage)return <div className="p-6">You do not have permission to manage events.</div>;
  return <div className="space-y-6"><PageHeader title={directoryMode?`Events · ${directoryContext?.listing?.name||'Directory club'}`:'Events'} description={directoryMode?'Create and maintain public RallyHub events here. The editor is the same one clubs use inside RallyHub Club, so there is nothing new to relearn later.':'Create once. Use the same event for members, RallyHub public Events and club sharing.'}/>
    <div className="grid gap-6 2xl:grid-cols-[1.18fr_.82fr]">
      <div className="glass rounded-xl p-5 space-y-6">
        <div className={`rounded-lg ${editingId?'border border-primary/30 bg-primary/5 p-3':''}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Plus className="h-5 w-5 text-primary"/><h2 className="font-bold">{editingId?`Editing: ${draft.name||'event'}`:'Create event'}</h2></div>{editingId&&<Button type="button" size="sm" variant="outline" onClick={resetEditor}><X className="mr-1 h-4 w-4"/>Close editor</Button>}</div>{editingId&&<p className="mt-1 text-xs text-muted-foreground">Edit the canonical event once; member and public views use the same record.</p>}</div>

        {!directoryMode&&isAdmin&&<section className="rounded-xl border p-4"><label className="text-sm font-semibold">Host / organisation<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={effectiveHostClubId} onChange={e=>{setAdminHostClubId(e.target.value);resetEditor()}}><option value="">Choose host / organisation</option>{adminClubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><span className="mt-1 block text-xs font-normal text-muted-foreground">Use a RallyHub club or internal organisation placeholder. Nothing here creates a public Directory listing by itself.</span></label></section>}

        <section className="space-y-4"><div><p className="text-sm font-black">1 · Basics</p><p className="text-xs text-muted-foreground">The information players need to identify the event quickly.</p></div><div className="grid gap-4 sm:grid-cols-2">
          <label className="text-sm font-semibold sm:col-span-2">Event name<Input className="mt-1" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
          <label className="text-sm font-semibold">Event type<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{EVENT_TYPES.filter(([v])=>v!=='all').map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
          <label className="text-sm font-semibold">Indoor / outdoor<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.setting} onChange={e=>setDraft({...draft,setting:e.target.value})}><option value="">Not specified</option><option value="indoor">Indoor</option><option value="outdoor">Outdoor</option><option value="mixed">Indoor / Outdoor</option></select></label>
          <label className="text-sm font-semibold">Starts<Input type="date" className="mt-1" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value,endDate:draft.endDate||e.target.value})}/></label>
          <label className="text-sm font-semibold">Ends<Input type="date" className="mt-1" value={draft.endDate} onChange={e=>setDraft({...draft,endDate:e.target.value})}/></label>
          <label className="text-sm font-semibold">Start time<Input type="time" className="mt-1" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label>
          <label className="text-sm font-semibold">End time<Input type="time" className="mt-1" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label>
          <label className="text-sm font-semibold sm:col-span-2">Club venue<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.venue_id} onChange={e=>{const v=venues.find(x=>x.id===e.target.value);setDraft({...draft,venue_id:e.target.value,location:v?.name||draft.location})}}><option value="">Manual / external venue</option>{venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
          <label className="text-sm font-semibold sm:col-span-2">Venue / location<Input className="mt-1" value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="e.g. Lagan Valley LeisurePlex, Lisburn"/></label>
          <label className="text-sm font-semibold">County / region<Input className="mt-1" value={draft.county} onChange={e=>setDraft({...draft,county:e.target.value})}/></label>
          <label className="text-sm font-semibold">Country<Input className="mt-1" value={draft.country} onChange={e=>setDraft({...draft,country:e.target.value})}/></label>
          <label className="text-sm font-semibold sm:col-span-2">Short public summary<textarea className="mt-1 min-h-20 w-full rounded-md border bg-background p-3 font-normal" value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})} placeholder="Two or three sentences for the public listing and event page."/></label>
        </div></section>

        <section className="space-y-3"><div><p className="text-sm font-black">2 · Artwork</p><p className="text-xs text-muted-foreground">Reuse the same poster for the full event page and a separately positioned card crop.</p></div><EventMediaEditor listingSlug={directoryListingSlug} value={draft.image} position={{x:draft.imageX,y:draft.imageY,zoom:draft.imageZoom}} cardPosition={{x:draft.cardX,y:draft.cardY,zoom:draft.cardZoom}} onChange={media=>setDraft(d=>({...d,image:media.url,imageX:media.x,imageY:media.y,imageZoom:media.zoom,cardX:media.cardX,cardY:media.cardY,cardZoom:media.cardZoom,imageOriginal:media.originalUrl??d.imageOriginal,imageSourceType:media.sourceType??d.imageSourceType}))}/></section>

        <section className="space-y-4"><div><p className="text-sm font-black">3 · Registration</p><p className="text-xs text-muted-foreground">RallyHub calculates Open, Opening soon, Closing soon and Closed from these dates.</p></div><div className="grid gap-4 sm:grid-cols-2">
          <label className="text-sm font-semibold">Registration method<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={draft.registrationMode} onChange={e=>setDraft({...draft,registrationMode:e.target.value})}><option value="external">External booking link</option><option value="rallyhub">RallyHub booking</option><option value="contact">Contact organiser</option><option value="none">No registration required</option></select></label>
          {draft.registrationMode==='external'&&<label className="text-sm font-semibold">Registration URL<Input className="mt-1" value={draft.registration} onChange={e=>setDraft({...draft,registration:e.target.value})} placeholder="https://…"/></label>}
          <label className="text-sm font-semibold">Registration opens<Input type="datetime-local" className="mt-1" value={draft.regOpen} onChange={e=>setDraft({...draft,regOpen:e.target.value})}/></label>
          <label className="text-sm font-semibold">Registration closes<Input type="datetime-local" className="mt-1" value={draft.regClose} onChange={e=>setDraft({...draft,regClose:e.target.value})}/></label>
          <label className="text-sm font-semibold">Entry fee / fee text<Input className="mt-1" value={draft.feeText} onChange={e=>setDraft({...draft,feeText:e.target.value})} placeholder="e.g. €45 per event"/></label>
          <label className="text-sm font-semibold">Capacity<Input type="number" min="1" className="mt-1" value={draft.capacity} onChange={e=>setDraft({...draft,capacity:e.target.value})}/></label>
          <label className="flex items-center gap-3 text-sm font-semibold sm:col-span-2"><input type="checkbox" checked={draft.waitlist} onChange={e=>setDraft({...draft,waitlist:e.target.checked})}/>Waitlist available when full</label>
        </div>{draft.regOpen&&<div className="rounded-lg bg-secondary/30 p-3 text-xs"><strong>Calculated registration state:</strong> {registrationState({event_registration_mode:draft.registrationMode,event_registration_url:draft.registration,event_registration_open_at:toIso(draft.regOpen),event_registration_close_at:toIso(draft.regClose)}).label}</div>}</section>

        <section className="space-y-4"><div><p className="text-sm font-black">4 · Who is it for?</p><p className="text-xs text-muted-foreground">Structured information powers the public filters rather than forcing players to read a long page.</p></div><div><p className="mb-2 text-xs font-bold">Playing levels</p><TogglePills values={EVENT_LEVELS} selected={draft.levels} onChange={levels=>setDraft({...draft,levels})}/></div><div><p className="mb-2 text-xs font-bold">Age groups</p><TogglePills values={EVENT_AGE_GROUPS} selected={draft.ageGroups} onChange={ageGroups=>setDraft({...draft,ageGroups})}/></div><div><p className="mb-2 text-xs font-bold">Disciplines</p><TogglePills values={EVENT_DISCIPLINES} selected={draft.disciplines} onChange={disciplines=>setDraft({...draft,disciplines})}/></div></section>

        <section className="space-y-4"><div><p className="text-sm font-black">5 · Event information</p><p className="text-xs text-muted-foreground">Optional detail stays collapsed on the public page until a player needs it.</p></div>
          <label className="block text-sm font-semibold">General event description<textarea className="mt-1 min-h-24 w-full rounded-md border bg-background p-3 font-normal" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
          <label className="block text-sm font-semibold">Eligibility & levels<textarea className="mt-1 min-h-20 w-full rounded-md border bg-background p-3 font-normal" value={draft.eligibility} onChange={e=>setDraft({...draft,eligibility:e.target.value})}/></label>
          <label className="block text-sm font-semibold">Player information<textarea className="mt-1 min-h-20 w-full rounded-md border bg-background p-3 font-normal" value={draft.playerInfo} onChange={e=>setDraft({...draft,playerInfo:e.target.value})}/></label>
          <label className="block text-sm font-semibold">Fees & cancellation<textarea className="mt-1 min-h-20 w-full rounded-md border bg-background p-3 font-normal" value={draft.feesCancellation} onChange={e=>setDraft({...draft,feesCancellation:e.target.value})}/></label>
          <label className="block text-sm font-semibold">Contact organiser<Input className="mt-1" value={draft.contact} onChange={e=>setDraft({...draft,contact:e.target.value})} placeholder="Email, phone or instructions"/></label>
          <label className="block text-sm font-semibold">Member-only information<textarea className="mt-1 min-h-20 w-full rounded-md border bg-background p-3 font-normal" placeholder="Information that must not appear publicly." value={draft.internal} onChange={e=>setDraft({...draft,internal:e.target.value})}/></label>
          <div className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">Day-by-day schedule</p><p className="text-xs text-muted-foreground">Optional. Keep each day short and scannable.</p></div><Button type="button" size="sm" variant="outline" onClick={()=>setDraft(d=>({...d,schedule:[...d.schedule,{day:'',time:'',title:''}]}))}><Plus className="mr-1 h-4 w-4"/>Add day</Button></div><div className="mt-3 space-y-3">{draft.schedule.map((row,index)=><div key={index} className="grid gap-2 rounded-lg bg-secondary/30 p-3 sm:grid-cols-[1fr_1fr_2fr_auto]"><Input value={row.day||''} onChange={e=>updateSchedule(index,'day',e.target.value)} placeholder="Thu 19 Nov"/><Input value={row.time||''} onChange={e=>updateSchedule(index,'time',e.target.value)} placeholder="09:30–15:00"/><Input value={row.title||''} onChange={e=>updateSchedule(index,'title',e.target.value)} placeholder="70+ Gender Doubles"/><Button type="button" size="icon" variant="ghost" onClick={()=>removeScheduleItem(index)} aria-label="Remove schedule item"><Trash2 className="h-4 w-4"/></Button></div>)}</div></div>
          <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Official/source URL<Input className="mt-1" value={draft.sourceUrl} onChange={e=>setDraft({...draft,sourceUrl:e.target.value})}/></label><label className="text-sm font-semibold">Map/directions URL<Input className="mt-1" value={draft.mapUrl} onChange={e=>setDraft({...draft,mapUrl:e.target.value})}/></label><label className="text-sm font-semibold">Latitude<Input type="number" step="any" className="mt-1" value={draft.latitude} onChange={e=>setDraft({...draft,latitude:e.target.value})}/></label><label className="text-sm font-semibold">Longitude<Input type="number" step="any" className="mt-1" value={draft.longitude} onChange={e=>setDraft({...draft,longitude:e.target.value})}/></label></div>
        </section>

        <section className="rounded-xl border p-4 space-y-3"><div><p className="text-sm font-black">6 · Audience & publishing</p><p className="text-xs text-muted-foreground">One canonical event can appear to members, publicly, or both.</p></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.member} onChange={e=>setDraft({...draft,member:e.target.checked})}/>Show to club members and in their Play calendar</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.public} onChange={e=>setDraft({...draft,public:e.target.checked})}/>Publish on RallyHub public Events</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.featured} onChange={e=>setDraft({...draft,featured:e.target.checked})}/>Feature on member home <span className="text-xs text-muted-foreground">for an important club fixture/event</span></label>{isAdmin&&<><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.featuredPublic} onChange={e=>setDraft({...draft,featuredPublic:e.target.checked})}/>Feature on RallyHub public Events</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.verifiedOrganiser} onChange={e=>setDraft({...draft,verifiedOrganiser:e.target.checked})}/>Verified organiser badge</label></>}</section>

        <section className="space-y-3"><div><p className="text-sm font-black">7 · Preview & publish</p><p className="text-xs text-muted-foreground">Preview the same poster/crop and information before publishing.</p></div><div className="grid gap-2 sm:grid-cols-3"><Button type="button" variant="outline" onClick={()=>setPreview('public-card')}><Eye className="mr-2 h-4 w-4"/>Public card</Button><Button type="button" variant="outline" onClick={()=>setPreview('public-detail')}><Eye className="mr-2 h-4 w-4"/>Public detail</Button><Button type="button" variant="outline" onClick={()=>setPreview('member')}><Eye className="mr-2 h-4 w-4"/>Member view</Button></div><div className="flex flex-col gap-2 sm:flex-row"><Button type="button" variant="outline" disabled={save.isPending} onClick={()=>save.mutate('draft')}>{save.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Save className="mr-2 h-4 w-4"/>}Save draft</Button><Button type="button" disabled={save.isPending||(!draft.member&&!draft.public)} onClick={()=>save.mutate('publish')}>{save.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<CheckCircle2 className="mr-2 h-4 w-4"/>}Publish selected audiences</Button></div>{saveState&&<div className={`rounded-lg border px-3 py-2 text-xs font-bold ${saveState.includes('✓')?'border-emerald-500/30 bg-emerald-500/10 text-emerald-700':saveState==='Could not save'?'border-destructive/30 bg-destructive/10 text-destructive':'border-primary/20 bg-primary/5 text-primary'}`}>{saveState}{saveState==='Published ✓'&&editingId&&draft.public&&<a href={`/events/${events.find(e=>e.id===editingId)?.event_slug||slugifyEvent(draft.name)}`} target="_blank" rel="noreferrer" className="ml-2 underline">View public event</a>}</div>}</section>
      </div>

      <aside className="space-y-5">{preview?<EventPreview draft={draft} mode={preview} onClose={()=>setPreview(null)} hostName={hostName}/>:<>
        <div className="glass rounded-xl p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Draft events</h2><span className="rounded-full bg-secondary px-2 py-0.5 text-xs font-bold">{drafts.length}</span></div><div className="mt-4 space-y-3">{drafts.length===0?<p className="text-sm text-muted-foreground">No draft events.</p>:visibleDrafts.map(e=><div key={e.id} className={`rounded-xl border p-3 ${editingId===e.id?'border-primary/40 bg-primary/5 ring-2 ring-primary/10':''}`}><div className="flex items-start justify-between gap-3"><div><div className="mb-1 inline-flex rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-black uppercase text-amber-800">Draft</div><p className="font-bold">{e.name}</p><p className="mt-1 text-xs text-muted-foreground">{e.start_date||'No date'} · {e.location||'Venue TBC'}</p></div><div className="flex gap-1"><Button type="button" size="sm" variant="outline" onClick={()=>editEvent(e)}>Edit</Button><Button type="button" size="icon" variant="outline" onClick={()=>removeEvent(e)} aria-label={`Delete ${e.name}`}><Trash2 className="h-4 w-4"/></Button></div></div></div>)}{drafts.length>3&&<Button type="button" variant="ghost" size="sm" className="w-full" onClick={()=>setShowOlder(v=>!v)}>{showOlder?'Show fewer':`View all drafts (${drafts.length})`}</Button>}</div></div>
        <div className="glass rounded-xl p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">Published events</h2><span className="rounded-full bg-secondary px-2 py-0.5 text-xs font-bold">{published.length}</span></div><div className="mt-4 space-y-3">{published.length===0?<p className="text-sm text-muted-foreground">No published events yet.</p>:visiblePublished.map(e=><div key={e.id} className={`rounded-xl border p-3 ${editingId===e.id?'border-primary/40 bg-primary/5 ring-2 ring-primary/10':''}`}><div className="flex items-start justify-between gap-3"><div><div className="mb-1 flex flex-wrap gap-1">{e.event_member_visible&&<span className="rounded-full bg-primary/10 px-2 py-0.5 text-[9px] font-black text-primary">MEMBERS</span>}{e.event_public_visible&&<span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[9px] font-black text-emerald-700">PUBLIC</span>}</div><p className="font-bold">{e.name}</p><p className="mt-1 text-xs text-muted-foreground">{e.start_date||'No date'} · {e.location||'Venue TBC'}</p></div><Button type="button" size="sm" variant="outline" onClick={()=>editEvent(e)}>Edit</Button></div></div>)}{published.length>5&&<Button type="button" variant="ghost" size="sm" className="w-full" onClick={()=>setShowOlder(v=>!v)}>{showOlder?'Show fewer':`View all published (${published.length})`}</Button>}</div></div>
        {sharedData.length>0&&<div className="glass rounded-xl p-5"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-primary"/><h2 className="font-bold">Shared with your club</h2></div><p className="mt-1 text-xs text-muted-foreground">These remain canonical public events; RallyHub has not duplicated them.</p><div className="mt-4 space-y-3">{sharedData.map(item=><div key={item.share.id} className="rounded-xl border p-3"><p className="font-bold">{item.event.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.event.start_date} · {item.event.location||'Venue TBC'}</p><div className="mt-2 flex gap-2"><a href={`/events/${item.event.event_slug}`} target="_blank" rel="noreferrer"><Button type="button" size="sm" variant="outline">View public</Button></a><Button type="button" size="sm" variant="ghost" onClick={()=>unshare(item.event.id)}>Remove from club</Button></div></div>)}</div></div>}
        {olderEvents.length>0&&<div className="glass rounded-xl p-5"><button type="button" className="flex w-full items-center justify-between text-left" onClick={()=>setShowOlder(v=>!v)}><span className="font-bold">Older events</span><span className="text-xs text-muted-foreground">{showOlder?'Hide':`Show ${olderEvents.length}`}</span></button>{showOlder&&<div className="mt-4 max-h-80 space-y-2 overflow-auto">{olderEvents.map(e=><div key={e.id} className="flex items-center justify-between gap-3 rounded-xl border p-3 opacity-80"><div><p className="text-sm font-bold">{e.name}</p><p className="text-xs text-muted-foreground">{e.start_date||'No date'} · {e.event_publish_status==='published'?'Published':'Draft'}</p></div><Button type="button" size="sm" variant="outline" onClick={()=>editEvent(e)}>Edit</Button></div>)}</div>}</div>}
      </>}</aside>
    </div>
  </div>;
}
