import React,{useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {base44} from '@/api/base44Client';
import {useAuth} from '@/lib/AuthContext';
import {ShieldCheck,Clock3} from 'lucide-react';

export default function TrialActivate(){
 const {user}=useAuth();const [params]=useSearchParams();const token=params.get('token')||'';
 const [state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checks,setChecks]=useState({authority:false,terms:false,sharing:false,ip:false});
 useEffect(()=>{if(!token){setError('This activation link is missing its trial token.');return;}base44.functions.invoke('trialJourney',{action:'activation_state',token}).then(r=>{if(r.data?.error)throw new Error(r.data.error);if(r.data?.alreadyActivated){window.location.href='/app';return;}setState(r.data)}).catch(e=>setError(e?.message||'Could not open this trial activation.'));},[token]);
 const activate=async()=>{setBusy(true);setError('');try{const a=state.agreement;const r=await base44.functions.invoke('trialJourney',{action:'accept_activate',token,authorityConfirmed:checks.authority,termsAccepted:checks.terms,restrictedSharingConfirmed:checks.sharing,ipAcknowledged:checks.ip,agreementId:a.id,agreementVersion:a.version,userAgent:navigator.userAgent});if(r.data?.error)throw new Error(r.data.error);window.location.href='/app';}catch(e){setError(e?.message||'Could not activate the trial.');setBusy(false)}};
 if(error&&!state)return <div className="min-h-screen bg-background px-4 py-16"><div className="mx-auto max-w-xl rounded-2xl border bg-card p-7"><h1 className="text-2xl font-black">Trial activation</h1><p className="mt-4 rounded-lg bg-destructive/10 p-4 text-sm text-destructive">{error}</p><p className="mt-4 text-sm text-muted-foreground">You are signed in as <strong>{user?.email||'this account'}</strong>. If the application used another email, sign out and use that address.</p></div></div>;
 if(!state)return <div className="min-h-screen grid place-items-center bg-background"><div className="h-9 w-9 animate-spin rounded-full border-4 border-primary border-t-transparent"/></div>;
 const app=state.application,a=state.agreement,all=Object.values(checks).every(Boolean);
 return <div className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-4xl space-y-5"><div className="rounded-2xl border bg-card p-5 sm:p-7"><div className="flex items-start gap-4"><div className="rounded-xl bg-primary/10 p-3"><ShieldCheck className="h-6 w-6 text-primary"/></div><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Approved controlled trial</p><h1 className="mt-1 text-2xl font-black">{app.club_name}</h1><p className="mt-2 text-sm text-muted-foreground">Review the agreement below. Your {app.trial_days}-day trial starts only when you accept and activate.</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-muted px-3 py-1"><Clock3 className="mr-1 inline h-3.5 w-3.5"/>Activation link valid until {app.activation_deadline?new Date(app.activation_deadline).toLocaleString('en-IE'):'—'}</span>{(app.selected_capability_keys||[]).map(k=><span key={k} className="rounded-full bg-primary/10 px-3 py-1 text-primary">{k.replace('tournament.','').replace('integration.','').replaceAll('_',' ')}</span>)}</div></div></div></div><section className="rounded-2xl border bg-card"><div className="border-b p-5"><h2 className="text-xl font-black">{a.title}</h2><p className="mt-1 text-xs text-muted-foreground">Version {a.version} · Governing law: {a.jurisdiction}</p></div><div className="max-h-[55vh] overflow-y-auto whitespace-pre-wrap p-5 text-sm leading-6 text-foreground/90">{a.body_text}</div></section><section className="space-y-3 rounded-2xl border bg-card p-5"><h2 className="font-black">Required confirmations</h2>{[
  ['authority','I confirm that I am authorised to accept these terms for my club.'],
  ['terms','I have read and accept the RallyHub Trial & Evaluation Agreement.'],
  ['sharing','I understand that trial access and confidential RallyHub information must not be shared with another club or unauthorised person.'],
  ['ip','I acknowledge that RallyHub retains its intellectual property and that the trial does not transfer ownership rights.']
 ].map(([key,label])=><label key={key} className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input className="mt-1" type="checkbox" checked={checks[key]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/><span>{label}</span></label>)}{error&&<p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<button disabled={!all||busy} onClick={activate} className="w-full rounded-xl bg-primary px-4 py-3 font-black text-primary-foreground disabled:opacity-50">{busy?'Activating…':'Accept & Activate Trial'}</button><p className="text-center text-xs text-muted-foreground">Signed in as {user?.email}. Your acceptance is recorded with the agreement version and confirmations above.</p></section></div></div>;
}
