import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

function nowIso(){return new Date().toISOString();}
function validAccess(a:any,tenantId:string,sessionId:string){if(!a||a.status!=='active'||String(a.tenant_id)!==String(tenantId)||String(a.session_id)!==String(sessionId)||a.role!=='session_host')return false;const now=Date.now();if(a.starts_at&&Date.parse(a.starts_at)>now)return false;if(a.ends_at&&Date.parse(a.ends_at)<now)return false;return true;}

Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user)return Response.json({error:'Unauthorized'},{status:401});
 const body=await req.json().catch(()=>({}));const sessionId=String(body.sessionId||''),roundId=String(body.roundId||''),commandId=String(body.commandId||'');
 if(!sessionId||!roundId||!commandId)return Response.json({error:'sessionId, roundId and commandId are required'},{status:400});
 let session=(await base44.asServiceRole.entities.KotcSession.filter({id:sessionId}))?.[0];if(!session)return Response.json({error:'KOTC session not found'},{status:404});
 let allowed=user.role==='admin';if(!allowed){const grants=await base44.asServiceRole.entities.KotcSessionAccess.filter({session_id:session.id,user_id:user.id,status:'active'});allowed=(grants||[]).some((a:any)=>validAccess(a,session.tenant_id,session.id));}if(!allowed)return Response.json({error:'Primary session host access required'},{status:403});
 if(Number(body.expectedSessionRevision)!==Number(session.revision||0))return Response.json({error:'Session changed since you opened it. Refresh and try again.',conflict:true,currentSessionRevision:Number(session.revision||0)},{status:409});
 const round=(await base44.asServiceRole.entities.KotcRound.filter({id:roundId,session_id:session.id}))?.[0];if(!round)return Response.json({error:'Round not found'},{status:404});
 if(round.status!=='proposed')return Response.json({error:`Round cannot start from ${round.status}.`},{status:409});
 if(Number(body.expectedProposalRevision)!==Number(round.proposal_revision||1))return Response.json({error:'Round proposal changed since you opened it. Refresh and try again.',conflict:true,currentProposalRevision:Number(round.proposal_revision||1)},{status:409});
 const slots=(await base44.asServiceRole.entities.KotcRoundSlot.filter({round_id:round.id,session_id:session.id})).sort((a:any,b:any)=>Number(a.ladder_court_rank)-Number(b.ladder_court_rank)||String(a.team_side).localeCompare(String(b.team_side))||Number(a.slot_number)-Number(b.slot_number));
 const participants=await base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id});const eligible=new Set((participants||[]).filter((p:any)=>['registered','confirmed','present','leaving_early'].includes(p.status)).map((p:any)=>String(p.id)));
 const requested=body.slotParticipantIds||{};const nextIds=slots.map((s:any)=>String(requested[s.id]||s.participant_id));const expected=Number(round.active_court_count||0)*4;
 if(slots.length!==expected||nextIds.length!==expected)return Response.json({error:`Round not ready: expected ${expected} court positions.`},{status:409});
 if(new Set(nextIds).size!==nextIds.length)return Response.json({error:'Round not ready: a player appears more than once.'},{status:409});
 if(nextIds.some((id:string)=>!eligible.has(id)))return Response.json({error:'Round not ready: an unavailable player is assigned.'},{status:409});
 const teams:any={};for(let i=0;i<slots.length;i++){const s=slots[i],key=`${s.ladder_court_rank}-${s.team_side}`;(teams[key]||(teams[key]=[])).push(nextIds[i]);}
 for(const team of Object.values(teams) as any[])if(team.length!==2)return Response.json({error:'Round not ready: every team must contain two players.'},{status:409});
 const locks=(await base44.asServiceRole.entities.KotcFixedPair.filter({session_id:session.id,status:'active'})).filter((p:any)=>p.pair_source==='host_selected');
 for(const l of locks){const a=String(l.participant1_id),b=String(l.participant2_id);if(nextIds.includes(a)&&nextIds.includes(b)&&!Object.values(teams).some((t:any)=>t.includes(a)&&t.includes(b)))return Response.json({error:`Round not ready: locked pair ${l.pair_name||''} is split.`},{status:409});}
 const changedCourts=new Set<number>();for(let i=0;i<slots.length;i++){const s=slots[i],id=nextIds[i];if(id!==String(s.participant_id)){await base44.asServiceRole.entities.KotcRoundSlot.update(s.id,{participant_id:id,assignment_type:'manual_override',assignment_revision:Number(s.assignment_revision||1)+1});changedCourts.add(Number(s.ladder_court_rank));}}
 if(changedCourts.size){const matches=await base44.asServiceRole.entities.KotcMatch.filter({round_id:round.id,session_id:session.id});for(const m of matches){const rank=Number(m.ladder_court_rank);if(!changedCourts.has(rank))continue;const court=slots.map((s:any,i:number)=>({...s,participant_id:nextIds[i]})).filter((s:any)=>Number(s.ladder_court_rank)===rank);await base44.asServiceRole.entities.KotcMatch.update(m.id,{team_a_participant_ids:court.filter((s:any)=>s.team_side==='A').sort((a:any,b:any)=>Number(a.slot_number)-Number(b.slot_number)).map((s:any)=>s.participant_id),team_b_participant_ids:court.filter((s:any)=>s.team_side==='B').sort((a:any,b:any)=>Number(a.slot_number)-Number(b.slot_number)).map((s:any)=>s.participant_id),revision:Number(m.revision||0)+1,command_id:commandId});}}
 const now=nowIso();const updatedRound=await base44.asServiceRole.entities.KotcRound.update(round.id,{status:'started',confirmed_at:now,confirmed_by_user_id:user.id,started_at:now});
 const update:any={status:session.status==='ready'?'in_progress':session.status,revision:Number(session.revision||0)+1,last_command_id:commandId,current_round_number:round.round_number,current_round_id:round.id};if(!session.actual_first_round_start)update.actual_first_round_start=now;
 session=await base44.asServiceRole.entities.KotcSession.update(session.id,update);if(session.tournament_id)await base44.asServiceRole.entities.Tournament.update(session.tournament_id,{status:'In Progress'});
 try{await base44.asServiceRole.entities.AuditLog.create({tenant_id:session.tenant_id,club_id:session.club_id,user_id:user.id,action:'kotc_round_started',entity_type:'KotcRound',entity_id:round.id,scope_type:'KotcSession',scope_id:session.id,after_state:JSON.stringify({round_number:round.round_number,started_at:now,manual_courts:[...changedCourts]})});}catch{}
 return Response.json({success:true,session,round:updatedRound});
}catch(error){return Response.json({error:error?.message||'Unexpected KOTC start error'},{status:500});}});