import assert from "node:assert/strict";
import fs from "node:fs";
const i=fs.readFileSync("base44/functions/interclubResultsEmail/resultsEmailTemplate.ts","utf8");
const k=fs.readFileSync("base44/functions/kotcResultsShare/entry.ts","utf8");
assert.match(i,/Production standard: protected Clare enriched shell/);
assert.match(i,/clare-logo-transparent\.png/);
assert.match(i,/header-right-clean\.png/);
assert.match(i,/footer-top\.png/);
assert.match(i,/social-rallyhub\.png/);
assert.match(i,/Looking forward to the return fixture/);
assert.match(i,/Photos from today/);
assert.match(i,/More pickleball with RallyHub/);
assert.match(i,/View My Results/);
assert.match(i,/utilityLinks\(resultUrl,root\)/);
assert.doesNotMatch(i,/Share RallyHub with a friend/);
assert.match(k,/presentationOptions:/);
console.log("PASS communicationsPresentationTemplateGate: protected Clare shell + purpose-specific Interclub body + KOTC presentation controls");
