import assert from "node:assert/strict";import fs from "node:fs";
import {resolveAudience,dedupeContacts} from "../src/services/communications/audience.js";
import {resolvePermission,doubleOptInEvidence} from "../src/services/communications/consent.js";
import {simulateWorkflow} from "../src/services/communications/workflow.js";
import {preflight,communicationPressure,safetyWindow} from "../src/services/communications/deliverability.js";
import {validateQuestions,aggregateResponses} from "../src/services/communications/polls.js";
import {campaignMetrics} from "../src/services/communications/analytics.js";
import {simulateCampaign} from "../src/services/communications/simulator.js";
const entities=["CommunicationPreference","CommunicationSuppression","CommunicationChannelConfig","CommunicationEvent","CommunicationConversation","CommunicationContentBlock","CommunicationWorkflowRun"];
entities.forEach(n=>assert.ok(fs.existsSync("base44/entities/"+n+".jsonc"),"missing "+n));
const people=[{person_id:"1",club:"clare",email:"a@x.ie"},{person_id:"2",club:"galway",email:"b@x.ie"},{person_id:"1",club:"clare",email:"a@x.ie"}];
assert.equal(resolveAudience({people,definition:{include:[{field:"club",op:"eq",value:"clare"}]}}).length,2);
assert.equal(dedupeContacts(people).duplicates.length,1);
assert.equal(resolvePermission({purpose:"marketing",channel:"email",records:[]}).allowed,false);
assert.equal(resolvePermission({purpose:"operational",channel:"email",records:[]}).allowed,true);
assert.equal(doubleOptInEvidence({requested_at:"a",confirmed_at:"b",wording_version:"v1",source:"web",channel:"email"}).complete,true);
const payment={steps:[{type:"send",template:"payment_request"},{type:"wait",minutes:10080},{type:"send",template:"reminder_1"},{type:"wait",minutes:10080},{type:"send",template:"final"}]};
const stopped=simulateWorkflow({workflow:payment,scenario:{goal_after_step:2}});assert.equal(stopped.at(-1).reason,"goal_achieved");
const interclub={steps:[{type:"send",template:"confirmation"},{type:"wait",minutes:2880},{type:"send",template:"event_info"},{type:"wait",minutes:1440},{type:"send",template:"event_day"},{type:"wait",minutes:360},{type:"send",template:"results"}]};
assert.ok(simulateWorkflow({workflow:interclub}).some(x=>x.template==="results"));
assert.equal(preflight({campaign:{kind:"campaign",purpose:"marketing",audience_definition:{}},message:{channel:"email",html_body:"x",plain_text_body:"x"},audience:{eligible_count:600}}).allowed,false);
assert.equal(preflight({campaign:{kind:"operational",purpose:"competition"},message:{channel:"email",html_body:"x",plain_text_body:"x"},audience:{eligible_count:14}}).risk,"green");
assert.equal(communicationPressure({last24Hours:4}),"over_contacted");assert.equal(safetyWindow({queuedAt:"2026-01-01T00:00:00Z",now:new Date("2026-01-01T00:00:31Z")}).releasable,true);
const questions=[{id:"q1",type:"single_choice",prompt:"Preferred night?",options:["Mon","Wed"]},{id:"q2",type:"rating",prompt:"Rate session"}];
assert.equal(validateQuestions(questions).ok,true);const agg=aggregateResponses({questions,responses:[{answers:[{question_id:"q1",value:"Mon"},{question_id:"q2",value:5}]},{answers:[{question_id:"q1",value:"Wed"},{question_id:"q2",value:3}]}]});assert.equal(agg.questions.q2.average,4);
const m=campaignMetrics([{status:"delivered"},{status:"clicked"},{status:"action_completed"},{status:"failed"}]);assert.equal(m.delivered,3);assert.equal(m.action_completed,1);
const sim=simulateCampaign({campaign:{kind:"operational",purpose:"competition",audience_definition:{include:[{field:"club",op:"eq",value:"clare"}]},sample_data:{name:"Brian"}},people,template:{subjectTemplate:"KOTC results - {{name}}",htmlTemplate:"<p>Results for {{name}}</p>",plainTextTemplate:"Results for {{name}}"},brandKit:{name:"Clare Pickleball"}});
assert.equal(sim.mode,"SIMULATION_ONLY");assert.equal(sim.eligible_count,1);assert.match(sim.rendered.subject,/Brian/);
const protectedFiles=["base44/functions/guestSessionBooking/entry.ts","base44/functions/kotcResultsShare/entry.ts","base44/functions/interclubResultsEmail/entry.ts"];
for(const p of protectedFiles)assert.ok(!fs.readFileSync(p,"utf8").includes("communicationsEngine"),p+" unexpectedly activated");
console.log("PASS communicationsDomainGate: audience + consent + workflows + deliverability + polls + analytics + KOTC/Interclub/payment simulations + no activation");
