import fs from 'node:fs';
const rows=JSON.parse(fs.readFileSync('docs/directory-branding/RALLYHUB_LOGO_CANDIDATES_EASY_SOURCE_2026-09-30.json','utf8'));
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const cards=rows.map(r=>{
 const image=r.filename?`<img src="./${esc(r.filename)}" alt="${esc(r.name)} candidate logo">`:`<div class="missing">No reliable candidate</div>`;
 const cls=r.decision==='APPROVE'?'approve':'hold';
 return `<article class="card ${cls}"><div class="num">${String(r.number).padStart(2,'0')}</div><div class="image">${image}</div><h2>${esc(r.name)}</h2><p class="county">${esc(r.county)}</p><div class="decision">${esc(r.decision)}</div><p class="meta">${esc(r.confidence)} · ${esc(r.method||r.status)}</p><p class="note">${esc(r.reviewNote||'')}</p>${r.sourcePage?`<a href="${esc(r.sourcePage)}" target="_blank" rel="noopener">Official source</a>`:''}</article>`;
}).join('\n');
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RallyHub Logo Review</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#0c2257;background:#f6f8fb}body{margin:0}.wrap{max-width:1400px;margin:auto;padding:24px}.hero{background:#0c2257;color:white;border-radius:20px;padding:24px;margin-bottom:20px}.hero h1{margin:0 0 8px}.hero p{margin:4px 0;color:#d8e3f4}.legend{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.pill{padding:6px 10px;border-radius:999px;font-weight:800;font-size:12px}.pill.a{background:#dcfce7;color:#166534}.pill.h{background:#fef3c7;color:#92400e}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:16px}.card{position:relative;background:white;border:2px solid #e5e7eb;border-radius:18px;padding:14px;box-shadow:0 6px 18px rgba(15,23,42,.06)}.card.approve{border-color:#86efac}.card.hold{border-color:#fde68a}.num{position:absolute;top:10px;left:10px;background:#0c2257;color:white;font-weight:900;border-radius:999px;min-width:34px;height:34px;display:grid;place-items:center;padding:0 4px}.image{height:170px;display:grid;place-items:center;background:#f8fafc;border-radius:13px;overflow:hidden}.image img{max-width:92%;max-height:92%;width:auto;height:auto;object-fit:contain}.missing{color:#94a3b8;font-weight:800;text-align:center}.card h2{font-size:17px;margin:13px 0 2px}.county,.meta,.note{font-size:12px}.county,.meta{color:#64748b}.decision{display:inline-block;font-size:11px;font-weight:900;padding:5px 9px;border-radius:999px;background:#fef3c7;color:#92400e}.approve .decision{background:#dcfce7;color:#166534}.note{min-height:44px;line-height:1.4}.card a{font-size:12px;font-weight:800;color:#0874c9;text-decoration:none}@media(max-width:600px){.wrap{padding:12px}.hero{padding:18px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.image{height:120px}.card{padding:10px}.card h2{font-size:14px}.note{display:none}}
</style></head><body><div class="wrap"><section class="hero"><h1>RallyHub Directory Logo Review</h1><p>Easy-source batch · 30 September 2026</p><p><strong>Exception approval:</strong> APPROVE means import by default. Only note numbers you want changed to REJECT or HOLD.</p><div class="legend"><span class="pill a">APPROVE ${rows.filter(r=>r.decision==='APPROVE').length}</span><span class="pill h">HOLD ${rows.filter(r=>r.decision==='HOLD').length}</span></div></section><main class="grid">${cards}</main></div></body></html>`;
fs.writeFileSync('public/directory/logo-candidates/2026-09-30/review.html',html);
console.log(`review page: ${rows.length} clubs, ${rows.filter(r=>r.decision==='APPROVE').length} approve, ${rows.filter(r=>r.decision==='HOLD').length} hold`);
