import assert from "node:assert/strict";
import fs from "node:fs";
const cc=fs.readFileSync("src/pages/CommunicationsCentre.jsx","utf8");
const entry=fs.readFileSync("base44/functions/interclubResultsEmail/entry.ts","utf8");
const tpl=fs.readFileSync("base44/functions/interclubResultsEmail/resultsEmailTemplate.ts","utf8");
assert.match(cc,/Personalised tournament alerts signup/);
assert.match(cc,/RallyHub Directory/);
assert.match(cc,/RallyHub Events/);
assert.match(cc,/Feedback \/ Contact/);
assert.match(cc,/Clare v Galway photo folder/);
assert.match(cc,/Custom link…/);
assert.match(cc,/Opening paragraph/);
assert.match(cc,/Return fixture panel/);
assert.match(cc,/Closing paragraph/);
assert.match(cc,/\{\{FIRST_NAME\}\}/);
assert.match(entry,/shortClub/);
assert.match(entry,/resultsContent\(body,event\)/);
assert.match(tpl,/const shortClub=/);
assert.match(tpl,/button1Url/);
assert.match(tpl,/closingText/);
console.log("PASS interclubEditorialControlGate: full visible body editing + named destinations + shortened club display names");
