import assert from "node:assert/strict";
import fs from "node:fs";
const tpl=fs.readFileSync("base44/functions/interclubResultsEmail/resultsEmailTemplate.ts","utf8");
assert.match(tpl,/white-space:nowrap/);
assert.match(tpl,/headerTitleLines/);
assert.match(tpl,/font-size:13px!important/);
assert.match(tpl,/height:138px!important/);
assert.match(tpl,/width="27%"/);
assert.match(tpl,/width="43%"/);
assert.match(tpl,/width="30%"/);
console.log("PASS interclubGmailHeaderGate: approved outer geometry retained with Gmail-safe middle text");
