import assert from 'node:assert/strict';
import fs from 'node:fs';

const view=fs.readFileSync('src/components/kotc/KotcView.jsx','utf8');
const v2=fs.readFileSync('src/components/kotc/KotcV2SessionView.jsx','utf8');
const command=fs.readFileSync('base44/functions/kotcCommand/entry.ts','utf8');
const create=fs.readFileSync('base44/functions/createKotcV2Session/entry.ts','utf8');
const get=fs.readFileSync('base44/functions/getKotcV2State/entry.ts','utf8');
let checks=0;const ok=(v,m)=>{checks++;assert.ok(v,m)};
ok(view.includes('KotcV2SessionView'),'KotcView must mount V2 UI');
ok(!view.includes("./KotcRoundView"),'legacy live view must not be mounted');
ok(!view.includes("./KotcSetup"),'legacy setup must not be mounted');
ok(!v2.includes('kingOfCourtEngine'),'V2 React must not import legacy sporting engine');
ok(v2.includes("functions.invoke('createKotcV2Session'"),'session creation is server-side');
ok(v2.includes("functions.invoke('getKotcV2State'"),'state read is server-authoritative');
ok(v2.includes("functions.invoke('kotcCommand'"),'mutations use command endpoint');
ok(v2.includes("'correct_match':'complete_match'"),'score completion wired');
ok(v2.includes("doCommand('confirm_round'"),'round confirmation wired');
ok(v2.includes("doCommand('start_round'"),'round start wired');
ok(v2.includes("doCommand('generate_next_round'"),'next-round generation wired');
ok(v2.includes("doCommand('pause_session'"),'pause wired');
ok(v2.includes("doCommand('resume_session'"),'resume wired');
ok(v2.includes("doCommand('finish_after_round'"),'finish-after-round wired');
ok(v2.includes("doCommand('finish_session_now'"),'finish-now wired');
ok(command.includes("commandType === 'generate_next_round'"),'server command must own next-round generation');
ok(command.includes('Fairness substitution invariant failed'),'server fairness invariant guard present');
ok(command.includes('current-round match result(s) unresolved'),'unresolved results block generation');
ok(create.includes("ENGINE_VERSION='2.0.0-rc.1'"),'new sessions pin accepted RC engine');
ok(create.includes('KotcSessionParticipant.create'),'participants persisted independently');
ok(create.includes('KotcRoundSlot.create'),'round slots persisted independently');
ok(create.includes('KotcMatch.create'),'matches persisted independently');
ok(get.includes('KotcSessionAccess'),'secure state read checks session access');
ok(get.includes('KotcHostLease'),'host lease surfaced to UI state');
console.log(`KOTC Gate 2.8 UI integration: PASS\n${checks} architecture/integration checks, 0 failures.`);