const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const dir = '/app/public/directory/logo-candidates/2026-09-30';
const approve = [
[2,'Ards Blair Mayne Pickleball Club','02-ards-blair-mayne-pickleball-club.jpg'],[4,'Balbriggan Pickleball','04-balbriggan-pickleball.jpg'],[15,'Duhallow Pickleball','15-duhallow-pickleball.png'],[18,'ezPICKLEBALL','18-ezpickleball.png'],[21,'Lisburn Pickleball Club','21-lisburn-pickleball-club.png'],[25,'Multyfarnham Pickleball Club','25-multyfarnham-pickleball-club.jpg'],[31,'Portarlington Pickleball','31-portarlington-pickleball.jpg'],[34,'Sandyford Pickleball Club','34-sandyford-pickleball-club.jpg'],[36,'Southside Pickleball Club','36-southside-pickleball-club.png'],[38,'Terenure Pickleball Club','38-terenure-pickleball-club.jpg'],[39,'Wallace Park Pickleball Club','39-wallace-park-pickleball-club.jpg']];
const holds = [[6,'Better Pickleball Club','06-better-pickleball-club.jpg','Parent organisation branding'],[10,'Castlerahan Pickleball Club','10-castlerahan-pickleball-club.png','Community centre branding'],[23,'Moate Pickleball Club','23-moate-pickleball-club.jpg','Sports centre branding'],[35,'Sligo Tennis Pickleball Club','35-sligo-tennis-pickleball-club.png','Racquet club branding'],[37,'Sports Lab Pickleball','37-sports-lab-pickleball.png','Parent branding']];
function imgSrc(file){const ext=path.extname(file).toLowerCase(); const mime=ext==='.jpg'||ext==='.jpeg'?'image/jpeg':ext==='.webp'?'image/webp':'image/png'; return `data:${mime};base64,${fs.readFileSync(path.join(dir,file)).toString('base64')}`;}
const css=`body{font-family:Arial,sans-serif;margin:0;background:#f4f7fb;color:#0c2257}.page{width:1420px;padding:34px;box-sizing:border-box}h1{font-size:30px;margin:0 0 8px}.sub{font-size:17px;color:#52627d;margin:0 0 24px}.notice{background:#e8eef8;padding:12px 16px;border-radius:12px;margin:0 0 24px;font-weight:700}.section{font-size:22px;margin:28px 0 14px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.card{position:relative;background:#fff;border:2px solid #dbe6e8;border-radius:18px;padding:14px;min-height:310px;box-sizing:border-box;box-shadow:0 2px 8px #0c225712}.num{position:absolute;left:10px;top:10px;background:#0c2257;color:white;border-radius:999px;padding:6px 9px;font-size:16px;font-weight:800;z-index:2}.thumb{height:205px;display:flex;align-items:center;justify-content:center;border-radius:12px;border:1px solid #e4eaef;background:#fff;overflow:hidden}.thumb img{max-width:92%;max-height:92%;object-fit:contain}.name{font-size:18px;font-weight:800;line-height:1.2;margin:12px 0 8px;min-height:44px}.badge{display:inline-block;padding:6px 11px;border-radius:999px;font-size:14px;font-weight:800}.approve{background:#dcfce7;color:#166534}.hold{background:#fef3c7;color:#92400e}.reason{font-size:13px;color:#7c5a16;margin-top:8px}`;
function cards(rows,hold=false){return rows.map(r=>`<div class="card"><div class="num">#${r[0]}</div><div class="thumb"><img src="${imgSrc(r[2])}"></div><div class="name">${r[1]}</div><span class="badge ${hold?'hold':'approve'}">${hold?'HOLD':'APPROVE'}</span>${hold?`<div class="reason">${r[3]}</div>`:''}</div>`).join('')}
(async()=>{const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1420,height:2200}}); const html=`<style>${css}</style><div class="page"><h1>RallyHub Logo Visual Review</h1><p class="sub">Exception review — green imports by default. Yellow stays on HOLD unless promoted.</p><div class="notice">Fast reply example: “Reject 4 and 31. Promote 35.”</div><div class="section">Default APPROVE — ${approve.length} logos</div><div class="grid">${cards(approve)}</div><div class="section">HOLD candidates — ${holds.length} logos</div><div class="grid">${cards(holds,true)}</div></div>`; await page.setContent(html,{waitUntil:'load'}); await page.waitForTimeout(300); await page.screenshot({path:'/tmp/rallyhub-logo-review-embedded.jpg',type:'jpeg',quality:86,fullPage:true}); console.log(await page.evaluate(()=>({height:document.documentElement.scrollHeight,broken:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).length,images:[...document.images].map(i=>({w:i.naturalWidth,h:i.naturalHeight}))}))); await browser.close();})();
