export const LEGACY_APPROVED_TEMPLATES=Object.freeze([
{id:"kotc_results",module:"King of the Court",name:"KOTC — Personal Results",status:"approved",channel:"email",brand:"Tenant / Clare Pickleball",source:"kotcResultsShare",renderer:"portable",subject:"{{session.name}} — your KOTC result",plainText:"Hi {{recipient.first_name}},\n\nThanks for playing in {{session.name}}.\n\nYour private {{competition.format}} player summary is ready. It shows your final rank, wins/losses, point differential and every round you played.\n\nOpen your private KOTC player summary: {{links.private_results}}\n\nThe shared event link remains available for the final podium and completed round results:\nOpen the shared KOTC results: {{links.shared_results}}\n\nThanks for playing. Looking forward to seeing you on court again soon.\n\nRegards,\n{{host.name}}\nSession Host\n{{club.name}}\n\n—\nPowered by RallyHub"},
{id:"kotc_player_link",module:"King of the Court",name:"KOTC — Player Link",status:"approved",channel:"email",brand:"Tenant",source:"kotcSessionBroadcast",renderer:"legacy-approved",subject:"{{session.name}} — KOTC Player Link",summary:"Existing Player Link email; keeps one live link through players, rounds, scoring and final results."},
{id:"kotc_update",module:"King of the Court",name:"KOTC — Event Update",status:"approved",channel:"email + player_link",brand:"Tenant",source:"kotcSessionBroadcast",renderer:"legacy-approved",subject:"KOTC Update · {{session.name}}",summary:"Existing host broadcast with Player Link CTA and expiry controls."},
{id:"interclub_results",module:"Interclub",name:"Interclub — Personal Results",status:"approved-locked",channel:"email",brand:"Clare Pickleball + RallyHub",source:"interclubResultsEmail/resultsEmailTemplate.ts",renderer:"specialised-approved",subject:"{{club_a.name}} v {{club_b.name}} Interclub | Your Results",summary:"Signed-off Clare v Galway artwork/template. Preserve exact dedicated renderer, clickable footer, personal results and RallyHub actions."},
{id:"interclub_update",module:"Interclub",name:"Interclub — Tournament Update",status:"approved",channel:"email + player_link",brand:"Tenant",source:"interclubTournamentUpdate",renderer:"legacy-approved",summary:"Existing Tournament Update communication to Player Link with optional email."},
{id:"guest_approved",module:"Session Bookings",name:"Guest Request — Approved",status:"approved",channel:"email",brand:"Tenant",source:"guestAccessJourney",renderer:"legacy-approved",subject:"{{club.name}} · Guest request approved · {{session.date}} {{session.start}}",summary:"Approved request with date/time/venue/fee and private booking/payment link."},
{id:"guest_pending_admin",module:"Session Bookings",name:"Guest Request — Admin Approval Needed",status:"approved",channel:"email",brand:"Tenant",source:"guestAccessJourney",renderer:"legacy-approved",subject:"Action required · {{club.name}} guest session request · {{guest.full_name}}",summary:"Admin alert with guest/session summary and Review Session Booking CTA."},
{id:"session_private_invite",module:"Session Bookings",name:"Guest Session — Private Invitation",status:"approved",channel:"email",brand:"Tenant",source:"guestSessionBooking",renderer:"legacy-approved",subject:"{{club.name}} · Guest session · {{session.date}} {{session.start}}",summary:"Private invitation tied to intended guest, with session details and booking link."},
{id:"session_booking_guest",module:"Session Bookings",name:"Session Booking — Participant Confirmation",status:"approved",channel:"email",brand:"Tenant",source:"guestSessionBooking",renderer:"legacy-approved",subject:"{{club.name}} · {{participant.type}} booking confirmed · {{session.date}} {{session.start}}",summary:"Existing member/guest booking confirmation."},
{id:"session_booking_host",module:"Session Bookings",name:"Session Booking — Host Notification",status:"approved",channel:"email",brand:"Tenant",source:"guestSessionBooking",renderer:"legacy-approved",subject:"Session booking confirmed · {{participant.full_name}} · {{venue.name}} · {{session.start}}",summary:"Existing host booking alert."},
{id:"session_refund",module:"Session Bookings",name:"Session Booking — Refund Issued",status:"approved",channel:"email",brand:"Tenant",source:"guestSessionBooking",renderer:"legacy-approved",subject:"{{club.name}} · Refund issued · {{refund.label}}",summary:"Existing refund confirmation."},
{id:"membership_received",module:"Membership",name:"Membership — Application Received",status:"approved",channel:"email",brand:"Tenant",source:"membershipApplication",renderer:"legacy-approved",summary:"Existing applicant confirmation and separate admin notification."},
{id:"membership_invitation",module:"Membership",name:"Membership — Invitation / Approved Request",status:"approved",channel:"email + whatsapp",brand:"Tenant",source:"membershipApplication",renderer:"legacy-approved",summary:"Private membership invitation/approval with authorised contact and payment/confirmation link."},
{id:"membership_confirmed",module:"Membership",name:"Membership — Confirmed",status:"approved",channel:"email",brand:"Tenant",source:"membershipApplication/paymentGatewayWebhook",renderer:"legacy-approved",summary:"Existing membership confirmation after successful completion/payment."},
{id:"membership_payment_reminder",module:"Membership",name:"Membership — Payment Reminder",status:"approved",channel:"email + whatsapp",brand:"Tenant",source:"membershipApplication",renderer:"legacy-approved",subject:"{{club.name}} membership payment reminder",summary:"Existing reminder content available for email and WhatsApp."},
{id:"waiting_list_confirmation",module:"Waiting List",name:"Waiting List — Confirmation",status:"approved",channel:"email",brand:"Tenant",source:"waitingList",renderer:"legacy-approved",subject:"You're on the {{club.name}} waiting list",summary:"Existing applicant confirmation; explicitly distinguishes waiting list from membership."},
{id:"waiting_list_admin",module:"Waiting List",name:"Waiting List — Admin Notification",status:"approved",channel:"email",brand:"Tenant",source:"waitingList",renderer:"legacy-approved",subject:"New {{club.name}} waiting-list entry",summary:"Existing admin notification."},
{id:"directory_claim",module:"Directory",name:"Directory — Claim Invitation",status:"approved",channel:"email + whatsapp",brand:"RallyHub",source:"directoryClaim",renderer:"legacy-approved",summary:"Existing secure 72-hour claim invitation and owner/editor variants."},
{id:"directory_broadcast",module:"Directory",name:"Directory — Contact Broadcast",status:"approved",channel:"email",brand:"RallyHub",source:"directoryClaim",renderer:"legacy-approved",summary:"Existing Directory broadcast with test-send and personalised delivery."},
{id:"directory_enquiry",module:"Directory",name:"Directory — Club Enquiry Relay",status:"approved",channel:"email",brand:"RallyHub",source:"directoryContactAction",renderer:"legacy-approved",subject:"RallyHub enquiry – {{listing.name}}",summary:"Existing protected enquiry relay with Reply-To and throttling."},
{id:"event_future_invite",module:"Events",name:"Event — Future Invitation Enquiry",status:"approved",channel:"email",brand:"RallyHub",source:"eventInterest",renderer:"legacy-approved",subject:"RallyHub enquiry – Future {{event.host}} invitation",summary:"Existing future-invitation enquiry relayed to organiser with Reply-To."}
]);
export function legacyTemplateModules(){return [...new Set(LEGACY_APPROVED_TEMPLATES.map(t=>t.module))]}
export function legacyTemplatesFor(module){return LEGACY_APPROVED_TEMPLATES.filter(t=>!module||t.module===module)}
