// Generated pre-launch fallback snapshot. Public-only data; no private contacts or tokens.
// Used only when Base44 is temporarily busy so public browsing remains available.
export const publicDirectoryFallbackSnapshot = {
  "vamos-pickleball": {
    "base": {
      "id": "vamos-pickleball",
      "slug": "vamos-pickleball",
      "name": "VAMOS Pickleball",
      "sport": "Pickleball",
      "county": "Galway",
      "town": "Claregalway",
      "region": null,
      "status": "active",
      "membershipStatus": "Contact the club for joining information",
      "affiliation": null,
      "logoUrl": null,
      "website": null,
      "facebook": null,
      "instagram": "https://www.instagram.com/vamospball/",
      "waitingListUrl": null,
      "joiningCtaLabel": "Contact club",
      "policyLabel": "Club information",
      "description": "VAMOS Pickleball is listed in the RallyHub Club Directory for County Galway. This listing has not yet been claimed and can be updated by an authorised club representative.",
      "guestPolicy": "Contact the club before attending a session.",
      "contact": {
        "name": "JP O Connell",
        "phone": "0877717277",
        "phoneHref": "tel:0877717277",
        "whatsapp": "https://wa.me/353877717277",
        "email": "johnpaulsport@gmail.com"
      },
      "venues": [],
      "sessions": [],
      "source": "RallyHub admin-curated directory listing",
      "sourceCheckedAt": "2026-09-18"
    },
    "profile": {
      "description": "VAMOS Pickleball is listed in the RallyHub Club Directory for County Galway. This listing has not yet been claimed and can be updated by an authorised club representative.",
      "membershipStatus": "Contact the club for joining information",
      "guestPolicy": "Contact the club before attending a session.",
      "policyLabel": "Club information",
      "website": null,
      "facebook": null,
      "instagram": "https://www.instagram.com/vamospball/",
      "waitingListUrl": null,
      "joiningCtaLabel": "Contact club",
      "logoUrl": "https://base44.app/api/apps/6a01dc00702b7dd2a2978c28/files/mp/public/6a01dc00702b7dd2a2978c28/488c4c398_vamos-pickleball-logo.webp",
      "contact": {
        "name": "JP O Connell",
        "phone": "0877717277",
        "phoneHref": "tel:+353877717277",
        "email": "johnpaulsport@gmail.com",
        "whatsapp": "https://wa.me/353877717277"
      },
      "venues": [
        {
          "id": "spond-1789724715716-1",
          "name": "Coláiste Bhaile Chláir - Claregalway College",
          "shortName": "Coláiste Bhaile Chláir - Claregalway College",
          "address": "Lakeview, Claregalway",
          "eircode": null,
          "indoor": null,
          "courts": null,
          "latitude": 53.3365978,
          "longitude": -8.9364787,
          "mapUrl": null,
          "websiteUrl": null,
          "playType": "Contact club",
          "source": "Spond"
        },
        {
          "id": "spond-1789724715716-2",
          "name": "Spond venue",
          "shortName": "Spond venue",
          "address": null,
          "eircode": null,
          "indoor": null,
          "courts": null,
          "latitude": 53.3404819,
          "longitude": -8.9462388,
          "mapUrl": null,
          "websiteUrl": null,
          "playType": "Contact club",
          "source": "Spond"
        },
        {
          "id": "spond-1789724715716-3",
          "name": "Ballybane Community Resource Centre",
          "shortName": "Ballybane Community Resource Centre",
          "address": "Castlepark Rd, Ballybane Rd, Galway",
          "eircode": null,
          "indoor": null,
          "courts": null,
          "latitude": null,
          "longitude": null,
          "mapUrl": null,
          "websiteUrl": null,
          "playType": "Contact club",
          "source": "Spond"
        }
      ],
      "sessions": [
        {
          "id": "session-cf4e17e2-02ac-43de-b55e-165493b932f9",
          "venueId": "spond-1789724715716-1",
          "day": "Friday",
          "start": "20:00",
          "end": "22:00",
          "meetTime": null,
          "level": "Claregalway Fridays",
          "price": null,
          "paymentMethod": null,
          "capacity": 16,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "session-27f581cf-8074-4b76-b48f-56eff66465ce",
          "venueId": "spond-1789724715716-1",
          "day": "Saturday",
          "start": "11:00",
          "end": "13:00",
          "meetTime": null,
          "level": "Social Saturday's",
          "price": null,
          "paymentMethod": null,
          "capacity": 16,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "session-ee46a9f8-07fc-4692-ba9a-da657fb12543",
          "venueId": "spond-1789724715716-1",
          "day": "Sunday",
          "start": "19:00",
          "end": "21:00",
          "meetTime": null,
          "level": "Sunday fixed partners",
          "price": null,
          "paymentMethod": null,
          "capacity": 8,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "session-c44fead5-122f-479f-b0ec-977634caa99b",
          "venueId": "spond-1789724715716-3",
          "day": "Thursday",
          "start": "18:00",
          "end": "20:00",
          "meetTime": null,
          "level": "Ballybane Thursday, 6pm",
          "price": null,
          "paymentMethod": null,
          "capacity": 8,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "session-95b7f10c-1057-4460-8965-975bec485d7c",
          "venueId": "spond-1789724715716-2",
          "day": "Saturday",
          "start": "11:00",
          "end": "13:00",
          "meetTime": null,
          "level": "Claregalway Saturday's",
          "price": null,
          "paymentMethod": null,
          "capacity": 15,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        }
      ]
    },
    "verificationStatus": "verified"
  },
  "terenure-pickleball-club": {
    "base": null,
    "profile": {
      "description": "At Terenure Pickleball Club, we’re more than a club—we’re a family of players who love the game, the friendships, and the laughs that come with every match.\n\nWe believe in community building, social play, and some seriously competitive pickling, with coaching opportunities throughout the year—led by one of Ireland’s top players—to help everyone up their game.\n\nNestled in the OLS Sports Dome at Our Lady's School, Terenure, we’re a lively community of pickleball enthusiasts who know how to have fun on the court! Whether you're a total beginner or a seasoned pro, there's a place for you here.\n\nWe started this adventure in January 2023 in collaboration with Pickleball Ireland and Dublin City Sport and Wellbeing Partnership with a simple mission: bring people together through the magic of pickleball. And here we are—growing, thriving, and ready to take it to the next level! \n\nWe are a non-profit, volunteer-run club, built by members for members. Our sole aim is to cover the costs of running the club—nothing more. \n\nSo what are you waiting for? Grab a paddle, bring your best game, and let’s hit the courts together!",
      "membershipStatus": "Unclaimed listing — contact club",
      "guestPolicy": "Contact the club directly before attending. Session times, access arrangements and membership details have not yet been verified by RallyHub.",
      "policyLabel": "Attendance information",
      "website": "https://www.terenurepickleballclub.ie/",
      "facebook": "https://www.facebook.com/Terenure.Pickleball.Club/",
      "instagram": null,
      "waitingListUrl": null,
      "joiningCtaLabel": "Contact club",
      "logoUrl": null,
      "contact": {
        "name": "Oliver Jennings",
        "phone": "+353 87 972 6860",
        "phoneHref": "tel:+353879726860",
        "email": "terenure.pickleball@gmail.com",
        "whatsapp": null
      },
      "venues": [
        {
          "id": "the-dome",
          "name": "Our Lady’s School Sports Dome",
          "shortName": "Our Lady’s School Sports Dome",
          "address": "Our Lady's School Terenure, Templeogue Road, Terenure, Dublin 6W",
          "eircode": null,
          "indoor": true,
          "courts": 15,
          "latitude": 53.3003006,
          "longitude": -6.2968598,
          "mapUrl": "https://maps.app.goo.gl/GwhokAaxAhCxBqfu8?g_st=ic",
          "websiteUrl": null,
          "playType": "Members and invited guests",
          "source": null
        }
      ],
      "sessions": [
        {
          "id": "session-eced4fe7-fbc6-49f2-874d-fa0d2d6e36b3",
          "venueId": "the-dome",
          "day": "Tuesday",
          "start": "20:00",
          "end": "22:00",
          "meetTime": "20:00",
          "level": "Club Session",
          "price": 10,
          "paymentMethod": "Online",
          "capacity": 64,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": null
        }
      ]
    },
    "verificationStatus": "verified"
  },
  "limerick-city-pickleball": {
    "base": null,
    "profile": {
      "description": "Weekly indoor pickleball match play in Limerick City at St. Munchin’s College and the UL Sport Arena.",
      "membershipStatus": "Contact the club before attending",
      "guestPolicy": "Contact Mick before attending. Session places are managed by the club through Spond.",
      "policyLabel": "Attendance information",
      "website": null,
      "facebook": null,
      "instagram": null,
      "waitingListUrl": null,
      "joiningCtaLabel": "Contact club",
      "logoUrl": "https://media.base44.com/images/public/6a01dc00702b7dd2a2978c28/212f5ecc1_limerick-city-pickleball-logo.webp",
      "contact": {
        "name": "Mick Kelliher",
        "phone": "087 240 0424",
        "phoneHref": "tel:+353872400424",
        "email": "mick.m.kelliher@gmail.com",
        "whatsapp": "https://wa.me/353872400424"
      },
      "venues": [
        {
          "id": "st-munchins",
          "name": "St. Munchin’s College",
          "shortName": "St. Munchin’s",
          "address": "Corbally Road, Corbally, Limerick",
          "eircode": "V94 HXW5",
          "indoor": true,
          "courts": null,
          "latitude": 52.6768,
          "longitude": -8.6134,
          "mapUrl": "https://maps.google.com/?q=V94+HXW5",
          "websiteUrl": "https://stmunchinscollege.com/",
          "playType": null,
          "source": null
        },
        {
          "id": "ul-arena",
          "name": "UL Sport Arena",
          "shortName": "UL Arena",
          "address": "University of Limerick, Castletroy, Limerick",
          "eircode": "V94 XT66",
          "indoor": true,
          "courts": null,
          "latitude": 52.6744,
          "longitude": -8.5708,
          "mapUrl": "https://maps.google.com/?q=V94+XT66",
          "websiteUrl": "https://www.ulsport.ie/",
          "playType": null,
          "source": null
        }
      ],
      "sessions": [
        {
          "id": "lc-mon-st-munchins-1930",
          "venueId": "st-munchins",
          "day": "Monday",
          "start": "19:30",
          "end": null,
          "meetTime": null,
          "level": "Match Play",
          "price": 5,
          "paymentMethod": null,
          "capacity": 20,
          "host": "Sarah Carey and two co-hosts",
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "lc-wed-ul-2000",
          "venueId": "ul-arena",
          "day": "Wednesday",
          "start": "20:00",
          "end": null,
          "meetTime": "19:45",
          "level": "Match Play",
          "price": 5,
          "paymentMethod": null,
          "capacity": 20,
          "host": "Sarah Carey and two co-hosts",
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        }
      ]
    },
    "verificationStatus": "verified"
  },
  "ashbourne-pickleball": {
    "base": null,
    "profile": {
      "description": "Ashbourne Pickleball Club play in 3 locations over 5 days a week and have 97 members.  Three of our sessions are for social play and 2 are streamed. \n\nIf you are an experienced player and find yourself in our area, and would like to come to play pickleball with us please e-mail ashbournepickleballclub@gmail.com",
      "membershipStatus": "Contact club",
      "guestPolicy": "Contact the club directly before attending. Session times, access arrangements and membership details have not yet been verified by RallyHub.",
      "policyLabel": "Attendance information",
      "website": "https://ashbournepickleballclub.com/",
      "facebook": "https://www.facebook.com/profile.php?id=61560911367711",
      "instagram": "https://www.instagram.com/ashbournepickleball/",
      "waitingListUrl": "https://ashbournepickleballclub.com/contact-us/",
      "joiningCtaLabel": "Contact club",
      "logoUrl": "https://media.base44.com/images/public/6a01dc00702b7dd2a2978c28/5e87182dc_ashbourne-pickleball-logo.webp",
      "contact": {
        "name": "David Molloy",
        "phone": null,
        "phoneHref": null,
        "email": "ashbournepickleball@gmail.com",
        "whatsapp": null
      },
      "venues": [
        {
          "id": "spond-1790010213550-3",
          "name": "Ashbourne Community School",
          "shortName": "ACS",
          "address": "Dublin Road, Deerpark, Milltown, Ashbourne, County Meath",
          "eircode": null,
          "indoor": true,
          "courts": null,
          "latitude": 53.5037828,
          "longitude": -6.3879078,
          "mapUrl": null,
          "websiteUrl": null,
          "playType": "Contact club",
          "source": "Spond"
        },
        {
          "id": "spond-1790010213550-4",
          "name": "Ashbourne Community Centre HES Civil",
          "shortName": "CC",
          "address": "Deerpark, Milltown, Ashbourne, County Meath",
          "eircode": null,
          "indoor": null,
          "courts": null,
          "latitude": null,
          "longitude": null,
          "mapUrl": null,
          "websiteUrl": null,
          "playType": "Contact club",
          "source": "Spond"
        },
        {
          "id": "spond-1790010213550-5",
          "name": "Spond venue",
          "shortName": "Spond venue",
          "address": null,
          "eircode": null,
          "indoor": null,
          "courts": null,
          "latitude": 53.6497514,
          "longitude": -6.5884245,
          "mapUrl": null,
          "websiteUrl": null,
          "playType": "Contact club",
          "source": "Spond"
        },
        {
          "id": "spond-1790010213550-6",
          "name": "Rolestown National School",
          "shortName": "Rolestown National School",
          "address": "Rowlestown West, County Dublin",
          "eircode": null,
          "indoor": null,
          "courts": null,
          "latitude": null,
          "longitude": null,
          "mapUrl": null,
          "websiteUrl": null,
          "playType": "Contact club",
          "source": "Spond"
        }
      ],
      "sessions": [
        {
          "id": "session-a3fd1636-0279-41ff-a627-d04594a2a1b5",
          "venueId": "spond-1790010213550-3",
          "day": "Monday",
          "start": "19:00",
          "end": "21:00",
          "meetTime": null,
          "level": "Monday Night Social PB - ACS",
          "price": null,
          "paymentMethod": null,
          "capacity": 24,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "session-ccb0bced-29d7-49fe-a07f-706ac27d9655",
          "venueId": "spond-1790010213550-6",
          "day": "Wednesday",
          "start": "19:00",
          "end": "21:00",
          "meetTime": null,
          "level": "Wednesday Rolestown Streaming",
          "price": null,
          "paymentMethod": null,
          "capacity": 20,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "session-7c717d60-fbf3-4abc-bc3a-2939c9369370",
          "venueId": "spond-1790010213550-5",
          "day": "Friday",
          "start": "18:30",
          "end": "20:30",
          "meetTime": null,
          "level": "Friday Streaming ACS",
          "price": null,
          "paymentMethod": null,
          "capacity": 18,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        },
        {
          "id": "session-84f6fcca-6057-4786-8261-15ae115174b4",
          "venueId": "spond-1790010213550-4",
          "day": "Sunday",
          "start": "09:30",
          "end": "11:30",
          "meetTime": null,
          "level": "Sunday Morning Social - CC",
          "price": null,
          "paymentMethod": null,
          "capacity": 18,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null,
          "source": "Spond"
        }
      ]
    },
    "verificationStatus": "verified"
  },
  "clare-pickleball": {
    "base": null,
    "profile": {
      "description": "A welcoming, members-only pickleball club with indoor sessions across County Clare.",
      "membershipStatus": "Full – waiting list open",
      "guestPolicy": "Experienced pickleball players from other clubs or visiting from abroad are most welcome. No beginner walk-in sessions.",
      "policyLabel": "Guest policy",
      "website": "https://clarepickleball.ie/",
      "facebook": "https://www.facebook.com/profile.php?id=61576112630693",
      "instagram": "https://www.instagram.com/clarepickleball",
      "waitingListUrl": "https://forms.gle/gWYZHHLBeUwyU3u17",
      "joiningCtaLabel": "Join waiting list",
      "logoUrl": "https://clarepickleball.ie/wp-content/uploads/2025/06/491439977_17843980809473841_8409446969161026129_n-removebg-preview.png",
      "contact": {
        "name": "Brian Moore",
        "phone": "087 810 0333",
        "phoneHref": "tel:+353878100333",
        "email": "info@clarepickleball.ie",
        "whatsapp": "https://wa.me/353878100333"
      },
      "venues": [
        {
          "id": "doora-barefield",
          "name": "St Joseph's Doora Barefield GAA Sports Hall",
          "shortName": "Doora Barefield",
          "address": "Gurteen, Quin Road, Co. Clare",
          "eircode": "V95 PD36",
          "indoor": true,
          "courts": 4,
          "latitude": 52.8426,
          "longitude": -8.9282,
          "mapUrl": "https://maps.google.com/?q=V95+PD36",
          "websiteUrl": null,
          "playType": "Contact club"
        },
        {
          "id": "corofin",
          "name": "Corofin GAA Sports Hall",
          "shortName": "Corofin",
          "address": "Corofin, Co. Clare",
          "eircode": "V95 XD56",
          "indoor": true,
          "courts": 3,
          "latitude": 52.9442,
          "longitude": -9.0646,
          "mapUrl": "https://maps.google.com/?q=V95+XD56",
          "websiteUrl": null,
          "playType": "Contact club"
        },
        {
          "id": "ennistymon",
          "name": "Ennistymon Community Centre",
          "shortName": "Ennistymon",
          "address": "Parliament Street, Ennistymon, Co. Clare",
          "eircode": "V95 X8XC",
          "indoor": true,
          "courts": 3,
          "latitude": 52.9394,
          "longitude": -9.2922,
          "mapUrl": "https://maps.app.goo.gl/xgPBCUfrBp35vu116",
          "websiteUrl": null,
          "playType": "Contact club"
        }
      ],
      "sessions": [
        {
          "id": "db-mon-social",
          "venueId": "doora-barefield",
          "day": "Monday",
          "start": "19:00",
          "end": "20:30",
          "meetTime": null,
          "level": "Social & Recreational",
          "price": 5.5,
          "paymentMethod": "Contact club",
          "capacity": 18,
          "host": "Brian Moore",
          "showPublicJoinLink": false,
          "publicJoinUrl": null
        },
        {
          "id": "db-mon-advanced",
          "venueId": "doora-barefield",
          "day": "Monday",
          "start": "20:30",
          "end": "22:00",
          "meetTime": null,
          "level": "Improver & Advanced",
          "price": 5.5,
          "paymentMethod": "Contact club",
          "capacity": 18,
          "host": "Brian Moore",
          "showPublicJoinLink": false,
          "publicJoinUrl": null
        },
        {
          "id": "db-thu-social",
          "venueId": "doora-barefield",
          "day": "Thursday",
          "start": "19:00",
          "end": "20:30",
          "meetTime": null,
          "level": "Social & Recreational",
          "price": 5.5,
          "paymentMethod": null,
          "capacity": 18,
          "host": "Brian Moore",
          "showPublicJoinLink": false,
          "publicJoinUrl": null
        },
        {
          "id": "db-thu-advanced",
          "venueId": "doora-barefield",
          "day": "Thursday",
          "start": "20:30",
          "end": "22:00",
          "meetTime": null,
          "level": "Improver & Advanced",
          "price": 5.5,
          "paymentMethod": null,
          "capacity": 18,
          "host": "Brian Moore",
          "showPublicJoinLink": false,
          "publicJoinUrl": null
        },
        {
          "id": "corofin-wed-daytime",
          "venueId": "corofin",
          "day": "Wednesday",
          "start": "11:30",
          "end": "13:30",
          "meetTime": null,
          "level": "Club Session",
          "price": 5,
          "paymentMethod": "Cash",
          "capacity": 14,
          "host": "Brian Moore",
          "showPublicJoinLink": false,
          "publicJoinUrl": null
        },
        {
          "id": "ennistymon-1",
          "venueId": "ennistymon",
          "day": "Wednesday",
          "start": "19:00",
          "end": "20:00",
          "meetTime": null,
          "level": "Club Session",
          "price": null,
          "paymentMethod": "Contact club",
          "capacity": 14,
          "host": "Brian Moore",
          "showPublicJoinLink": false,
          "publicJoinUrl": null
        },
        {
          "id": "ennistymon-2",
          "venueId": "ennistymon",
          "day": "Wednesday",
          "start": "20:00",
          "end": "21:00",
          "meetTime": null,
          "level": "Club Session",
          "price": null,
          "paymentMethod": "Contact club",
          "capacity": 14,
          "host": null,
          "showPublicJoinLink": false,
          "publicJoinUrl": null
        }
      ]
    },
    "verificationStatus": "verified"
  },
  "galway-pickleball": {
    "base": null,
    "profile": null,
    "verificationStatus": "verified"
  }
};
