import React,{useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Button} from '@/components/ui/button';

export default function EnnisDiamondSpondPilot(){
 const [info,setInfo]=useState(null),[groups,setGroups]=useState([]),[group,setGroup]=useState(''),[events,setEvents]=useState([]),[choices,setChoices]=useState({}),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const invoke=async(action,extra={})=>{const r=await base44.functions.invoke('guestAccessJourney',{action,...extra});if(r.data?.error)throw new Error(r.data.error);return r.data};
 const refresh=async()=>{setBusy('refresh');try{setInfo(await invoke('admin_spond_bindings'));setMessage('Ennis Diamond pilot connections loaded.')}catch(e){setMessage(e.message)}finally{setBusy('')}};
 useEffect(()=>{refresh()},[]);
 const loadGroups=async()=>{setBusy('groups');try{const r=await base44.functions.invoke('spondIntegrationWorking',{action:'directory_get_groups',listingSlug:info.listingSlug});if(r.data?.error)throw new Error(r.data.error);setGroups(r.data?.groups||[]);const clare=(r.data?.groups||[]).find(g=>String(g.name).trim().toLowerCase()==='clare pickleball');if(clare)setGroup(String(clare.id));setMessage('Choose Clare Pickleball, then load the events.')}catch(e){setMessage(e?.response?.data?.error||e.message||'Spond connection unavailable. Connect the authorised account first in Directory Spond settings.')}finally{setBusy('')}};
 const loadEvents=async()=>{if(!group)return;setBusy('events');try{const r=await base44.functions.invoke('spondIntegrationWorking',{action:'directory_get_events',listingSlug:info.listingSlug,groupId:group});if(r.data?.error)throw new Error(r.data.error);setEvents(r.data?.events||[]);setMessage('Select the correct recurring event for each time. Only matching weekdays and times can be saved.')}catch(e){setMessage(e?.response?.data?.error||e.message)}finally{setBusy('')}};
 const save=async(session)=>{setBusy(session.id);try{await invoke('admin_spond_bind',{sessionId:session.id,groupId:group,eventId:choices[session.id]});setInfo(await invoke('admin_spond_bindings'));setMessage(`${session.venueName} ${session.start} connection saved. Next-week availability will use the saved recurring match.`)}catch(e){setMessage(e?.response?.data?.error||e.message)}finally{setBusy('')}};
 return <section className="glass rounded-2xl p-5 space-y-3"><h2 className="text-lg font-black">Ennis Diamond · Spond pilot</h2><p className="text-sm text-muted-foreground">One-time connection for 7 pm and 8 pm only. Shannon and Clarecastle are not enabled. Select the group and its exact recurring events; bookings remain subject to club approval.</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={refresh} disabled={!!busy}>Refresh mappings</Button><Button variant="outline" onClick={loadGroups} disabled={!!busy||!info}>Connect to existing Spond account</Button></div>{groups.length>0&&<div className="flex flex-wrap gap-2"><select aria-label="Spond group" className="rounded-lg border bg-background p-2 text-sm" value={group} onChange={e=>{setGroup(e.target.value);setEvents([])}}><option value="">Choose Spond group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><Button onClick={loadEvents} disabled={!group||!!busy}>Load Spond events</Button></div>}{(info?.sessions||[]).map(s=>{const binding=info.bindings?.find(b=>b.directory_session_key===s.id&&b.active);const candidates=events.filter(e=>{const d=new Date(e.startTimestamp);return Number.isFinite(d.getTime())&&new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Dublin',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d)===s.start&&new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Dublin',weekday:'long'}).format(d)===s.day});return <div key={s.id} className="rounded-xl border p-3 space-y-2"><p className="font-semibold">{s.venueName} · {s.day} {s.start}</p><p className="text-xs text-muted-foreground">{binding?`Saved Spond event: ${binding.spond_heading||binding.spond_event_id} · Group ${binding.spond_group_id}`:'Not yet connected'}</p>{events.length>0&&<div className="flex flex-wrap gap-2"><select aria-label={`Spond event for ${s.start}`} className="min-w-0 max-w-full rounded-lg border bg-background p-2 text-sm" value={choices[s.id]||''} onChange={e=>setChoices(v=>({...v,[s.id]:e.target.value}))}><option value="">Choose matching Spond event</option>{candidates.map(e=><option key={`${e.id}-${e.startTimestamp}`} value={e.id}>{e.heading} · {new Date(e.startTimestamp).toLocaleDateString('en-IE')} {s.start}</option>)}</select><Button disabled={!choices[s.id]||!!busy} onClick={()=>save(s)}>Save connection</Button></div>}</div>})}{info?.sessions?.length===0&&<p className="text-sm text-amber-600">No matching Ennis Diamond 7 pm/8 pm sessions were found in this club's Directory configuration. Nothing has been connected.</p>}<p role="status" className="text-sm">{busy?'Working… ':''}{message}</p></section>;
}
