import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

const RUNTIME_VERSION='kotc-end-2026-09-10-r8';
function nowIso(){return new Date().toISOString();}
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
function isRateLimit(error:any){return /rate limit|too many requests|\b429\b/i.test(String(error?.message||error||''));}
async function retry<T>(label:string,fn:()=>Promise<T>,attempts=5){let last:any;for(let i=0;i<attempts;i++){try{return await fn();}catch(error){last=error;if(!isRateLimit(error)||i===attempts-1)throw error;const delay=Math.min(1600,180*Math.pow(2,i))+Math.floor(Math.random()*80);console.warn('KOTC end rate limit — retrying',{label,attempt:i+1,delay});await sleep(delay);}}throw last;}
function standings(matches:any[],participants:any[]){const s:any=Object.fromEntries((participants||[]).map((p:any)=>[p.id,{id:p.id,name:p.display_name,w:0,l:0,pf:0,pa:0,c1:0}]));for(const m of (matches||[]).filter((x:any)=>x.status==='completed')){const a=m.team_a_participant_ids||[],b=m.team_b_participant_ids||[];for(const id of [...a,...b])if(s[id]&&Number(m.ladder_court_rank)===1)s[id].c1++;for(const id of a)if(s[id]){s[id].pf+=Number(m.team_a_score||0);s[id].pa+=Number(m.team_b_score||0);m.winner_side==='A'?s[id].w++:s[id].l++;}for(const id of b)if(s[id]){s[id].pf+=Number(m.team_b_score||0);s[id].pa+=Number(m.team_a_score||0);m.winner_side==='B'?s[id].w++:s[id].l++;}}return Object.values(s).sort((x:any,y:any)=>y.w-x.w||((y.pf-y.pa)-(x.pf-x.pa))||y.c1-x.c1||String(x.name).localeCompare(String(y.name))).map((x:any,i:number)=>({...x,rank:i+1}));}
function allowedAccess(a:any,tenantId:string,sessionId:string){if(!a||a.status!=='active'||String(a.tenant_id||'')!==String(tenantId||'')||String(a.session_id||'')!==String(sessionId||''))return false;if(a.role!=='session_host')return false;const now=Date.now();if(a.starts_at&&Date.parse(a.starts_at)>now)return false;if(a.ends_at&&Date.parse(a.ends_at)<now)return false;return true;}

Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user)return Response.json({error:'Unauthorized',runtimeVersion:RUNTIME_VERSION},{status:401});
 const body=await req.json().catch(()=>({}));const sessionId=String(body.sessionId||''),action=String(body.action||'');if(!sessionId||!['finish','abandon','reset_setup'].includes(action))return Response.json({error:'sessionId and valid action are required',runtimeVersion:RUNTIME_VERSION},{status:400});
 let session=(await retry('session read',()=>base44.asServiceRole.entities.KotcSession.filter({id:sessionId})))?.[0];if(!session)return Response.json({error:'KOTC session not found',runtimeVersion:RUNTIME_VERSION},{status:404});
 let allowed=user.role==='admin';if(!allowed){const grants=await retry('access read',()=>base44.asServiceRole.entities.KotcSessionAccess.filter({session_id:session.id,user_id:user.id,status:'active'}));allowed=(grants||[]).some((a:any)=>allowedAccess(a,session.tenant_id,session.id));}if(!allowed)return Response.json({error:'Primary session host access required',runtimeVersion:RUNTIME_VERSION},{status:403});
 if(['completed','finalised','abandoned','cancelled'].includes(session.status)){const matches=await retry('ended matches',()=>base44.asServiceRole.entities.KotcMatch.filter({session_id:session.id}));const rounds=await retry('ended rounds',()=>base44.asServiceRole.entities.KotcRound.filter({session_id:session.id}));const participants=await retry('ended participants',()=>base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id}));return Response.json({success:true,alreadyEnded:true,session,matches,rounds,participants,runtimeVersion:RUNTIME_VERSION});}
 if(action==='reset_setup'){
   if(session.status!=='ready'||Number(session.current_round_number||1)!==1||session.actual_first_round_start)return Response.json({error:'Back to Setup is only available before Round 1 starts.',runtimeVersion:RUNTIME_VERSION},{status:409});
   const preRounds=await retry('setup rounds',()=>base44.asServiceRole.entities.KotcRound.filter({session_id:session.id}));const round1=(preRounds||[]).find((r:any)=>Number(r.round_number)===1);if(round1&&round1.status!=='proposed')return Response.json({error:'Back to Setup is only available while Round 1 is still proposed.',runtimeVersion:RUNTIME_VERSION},{status:409});
   const preMatches=await retry('setup matches',()=>base44.asServiceRole.entities.KotcMatch.filter({session_id:session.id}));if((preMatches||[]).some((m:any)=>m.team_a_score!=null||m.team_b_score!=null||m.autosaved_at||m.status==='completed'))return Response.json({error:'A score has already been entered. Setup can no longer be reopened.',runtimeVersion:RUNTIME_VERSION},{status:409});
   const now=nowIso();if(round1)await retry('abandon proposed round',()=>base44.asServiceRole.entities.KotcRound.update(round1.id,{status:'abandoned',abandonment_reason:'Host returned to setup before Round 1 start'}));
   const updated=await retry('cancel setup session',()=>base44.asServiceRole.entities.KotcSession.update(session.id,{status:'cancelled',actual_session_end:now,revision:Number(session.revision||0)+1,last_command_id:String(body.commandId||`reset-setup-${Date.now()}`),abandonment_reason:'Returned to setup before Round 1 start'}));
   if(session.tournament_id)try{await retry('reset tournament',()=>base44.asServiceRole.entities.Tournament.update(session.tournament_id,{status:'Draft'}));}catch(error){console.warn('KOTC setup tournament update skipped',{error:String((error as any)?.message||error)});}
   try{await base44.asServiceRole.entities.AuditLog.create({tenant_id:session.tenant_id,club_id:session.club_id,user_id:user.id,action:'kotc_returned_to_setup',entity_type:'KotcSession',entity_id:session.id,scope_type:'KotcSession',scope_id:session.id,before_state:JSON.stringify({status:session.status}),after_state:JSON.stringify({status:'cancelled'}),reason:'Host returned to setup before Round 1 start'});}catch{}
   return Response.json({success:true,session:updated,returnedToSetup:true,runtimeVersion:RUNTIME_VERSION});
 }
 if(!['ready','in_progress','paused'].includes(session.status))return Response.json({error:`Session cannot be ended from ${session.status}`,runtimeVersion:RUNTIME_VERSION},{status:409});
 const now=nowIso();let matches=await retry('matches read',()=>base44.asServiceRole.entities.KotcMatch.filter({session_id:session.id}));
 if(action==='finish'){
   const unresolved=(matches||[]).filter((m:any)=>!['completed','retired','abandoned','not_played'].includes(m.status));const updates=unresolved.map((m:any)=>({id:m.id,status:'not_played',result_method:'not_played',completed_at:now,revision:Number(m.revision||0)+1}));if(updates.length)await retry('unfinished matches bulk close',()=>base44.asServiceRole.entities.KotcMatch.bulkUpdate(updates));const byId=Object.fromEntries(updates.map((m:any)=>[m.id,m]));matches=(matches||[]).map((m:any)=>byId[m.id]?{...m,...byId[m.id]}:m);
 }
 let rounds=await retry('rounds read',()=>base44.asServiceRole.entities.KotcRound.filter({session_id:session.id}));const roundUpdates=(rounds||[]).filter((r:any)=>['proposed','confirmed','started'].includes(r.status)).map((r:any)=>{const rm=(matches||[]).filter((m:any)=>String(m.round_id)===String(r.id));const played=rm.some((m:any)=>m.status==='completed');return{id:r.id,status:played?'completed':'abandoned',completed_at:played?now:undefined,abandonment_reason:played?undefined:(action==='finish'?'Session finished before this round was played':String(body.reason||'Session abandoned by host'))};});if(roundUpdates.length)await retry('rounds bulk close',()=>base44.asServiceRole.entities.KotcRound.bulkUpdate(roundUpdates));const roundById=Object.fromEntries(roundUpdates.map((r:any)=>[r.id,r]));rounds=(rounds||[]).map((r:any)=>roundById[r.id]?{...r,...roundById[r.id]}:r);
 const sessionUpdate:any={status:action==='finish'?'completed':'abandoned',actual_session_end:now,revision:Number(session.revision||0)+1,last_command_id:String(body.commandId||`end-${Date.now()}`)};if(action==='abandon')sessionUpdate.abandonment_reason=String(body.reason||'Session abandoned by host');
 session=await retry('session finish save',()=>base44.asServiceRole.entities.KotcSession.update(session.id,sessionUpdate));
 let participants=await retry('participants read',()=>base44.asServiceRole.entities.KotcSessionParticipant.filter({session_id:session.id}));
 if(action==='finish'){
   const rankUpdates=standings(matches||[],participants||[]).map((row:any)=>({id:row.id,final_rank:row.rank,podium_group:row.rank===1?'gold':row.rank===2?'silver':row.rank===3?'bronze':'none'}));if(rankUpdates.length)await retry('podium ranks bulk save',()=>base44.asServiceRole.entities.KotcSessionParticipant.bulkUpdate(rankUpdates));const rankById=Object.fromEntries(rankUpdates.map((r:any)=>[r.id,r]));participants=(participants||[]).map((p:any)=>rankById[p.id]?{...p,...rankById[p.id]}:p);
 }
 if(session.tournament_id)try{await retry('tournament finish',()=>base44.asServiceRole.entities.Tournament.update(session.tournament_id,{status:action==='finish'?'Completed':'Cancelled',finalised_at:action==='finish'?now:undefined}));}catch(error){console.warn('KOTC tournament finish update skipped',{sessionId:session.id,error:String((error as any)?.message||error)});}
 try{await base44.asServiceRole.entities.AuditLog.create({tenant_id:session.tenant_id,club_id:session.club_id,user_id:user.id,action:action==='finish'?'kotc_session_finished':'kotc_session_abandoned',entity_type:'KotcSession',entity_id:session.id,scope_type:'KotcSession',scope_id:session.id,before_state:JSON.stringify({status:'live'}),after_state:JSON.stringify({status:session.status,revision:session.revision}),reason:action==='finish'?'Host finished session and preserved completed results':String(body.reason||'Session abandoned by host')});}catch(error){console.warn('KOTC finish audit skipped',{sessionId:session.id,error:String((error as any)?.message||error)});}
 return Response.json({success:true,session,matches,rounds,participants,completedMatches:(matches||[]).filter((m:any)=>m.status==='completed').length,runtimeVersion:RUNTIME_VERSION});
}catch(error){return Response.json({error:(error as any)?.message||'Unexpected session-end error',runtimeVersion:RUNTIME_VERSION},{status:isRateLimit(error)?503:500});}});